### ISSUE TITLE
Missing LocARNA PP format

### ISSUE THREAD

**Issue by germa** [edamontology/edamontology#100]
http://www.bioinf.uni-freiburg.de/Software/LocARNA/PP/

**Comment by joncison** [comment]
Format for multiple aligned or single sequences together with the probabilistic description of the (consensus) RNA secondary structure ensemble by probabilities of base pairs, base pair stackings, and base pairs and unpaired bases in the loop of base pairs.

**Comment by joncison** [comment]
Done in EDAM_1.14
"LocARNA PP"
http://edamontology.org/format_3728
