### ISSUE TITLE
Missing SBOL format

### ISSUE THREAD

**Issue by germa** [edamontology/edamontology#103]
http://sbolstandard.org/downloads/specification-data-model-2-0/

**Comment by joncison** [comment]
Definition:
"Synthetic Biology Open Language (SBOL) format for the specification and exchange of biological design information in synthetic biology."

**Comment by joncison** [comment]
Unsure about parent, but more relevant text:
"SBOL introduces a standardized format for the electronic exchange of information on the structural and functional aspects of biological designs."

**Comment by joncison** [comment]
Done in EDAM_1.14
"SBOL"
http://edamontology.org/format_3725
