### ISSUE TITLE
New operation "Metabolic labeling" + "sub-operations"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#107]
Definition: Labeling all proteins and (possibly) all amino acids using C-13 or N-15 enriched grown medium or feed

Parent: http://edamontology.org/operation_3635

Sub-operation "N-15 metabolic labeling"
Definition: Labeling all proteins and (possibly) all amino acids using N-15 enriched grown medium or feed
Synonym: N-15 labeling

Sub-operation "C-13 metabolic labeling"
Definition: labeling all proteins and (possibly) all amino acids using C-13 enriched grown medium or feed
Synonym: C-13 labeling

**Comment by joncison** [comment]
Thanks!  I think "C-13 ..." "N-15" go in as "narrow synonym"

**Comment by veitveit** [comment]
Agreed

**Comment by joncison** [comment]
@veitveit - you'll noticed I've tagged all your requests.  Cool if you do this when you add them (see "Labels" option in the sidebar

**Comment by veitveit** [comment]
Can I do that? I have no list of Labels to choose  from, see screenshot.
Maybe an issue of user rights?


2016-02-15 13:49 GMT+01:00 Jon Ison <notifications@github.com>:

> @veitveit <https://github.com/veitveit> - you'll noticed I've tagged all
> your requests. Cool if you do this when you add them (see "Labels" option
> in the sidebar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edamontology/edamontology/issues/107#issuecomment-184192378>
> .
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
sorry - check your email and join the relevant team.  then it should be OK, if not, I fiddle more ...

**Comment by veitveit** [comment]
solved :-)

**Comment by joncison** [comment]
Done in EDAM_1.14
"Metabolic labeling"
http://edamontology.org/operation_3715
