### ISSUE TITLE
New format "MaxQuant APL peaklist"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#108]
Definition: Peak list files from Andromeda search engine (MaxQuant) that consist of arbitrarily many spectra		
Parent: http://edamontology.org/format_3245		
Synonym: MaxQuant APL

**Comment by joncison** [comment]
@veitveit  again, link to docs and binary/text please

**Comment by veitveit** [comment]
text format, vagely described in paper:
http://pubs.acs.org/doi/pdf/10.1021/pr101065j



2016-02-23 13:06 GMT+01:00 Jon Ison <notifications@github.com>:

> @veitveit <https://github.com/veitveit> again, link to docs and
> binary/text please
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edamontology/edamontology/issues/108#issuecomment-187674250>
> .
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
Thanks
