### ISSUE TITLE
New format "Mascot .dat file"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#109]
Definition: "raw" result file from Mascot database search		
Parent: http://edamontology.org/format_3245

**Comment by joncison** [comment]
Done in EDAM_1.14
""Mascot .dat file"

@veitveit  is it binary or text?  pls. provide a link to the docs

**Comment by veitveit** [comment]
text file, indirectly described here:
https://github.com/compomics/mascotdatfile

2016-02-23 12:54 GMT+01:00 Jon Ison <notifications@github.com>:

> Closed #109 <https://github.com/edamontology/edamontology/issues/109>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edamontology/edamontology/issues/109#event-561492092>.
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
Thanks!
