### ISSUE TITLE
New format "Thermo RAW"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#110]
Definition: Proprietary file format for mass spectrometry data from Thermo Scientific		Parent: http://edamontology.org/format_3245

**Comment by joncison** [comment]
Done in EDAM_1.14
"Thermo RAW"
http://edamontology.org/format_3712

@veitveit again , binary or textual?  And pls. provide a link to documentation.

**Comment by veitveit** [comment]
Binary format and it is proprietary meaning there is no useful documentation

2016-02-23 12:51 GMT+01:00 Jon Ison <notifications@github.com>:

> Closed #110 <https://github.com/edamontology/edamontology/issues/110>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edamontology/edamontology/issues/110#event-561487862>.
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
OK thanks
