### ISSUE TITLE
New format "X!Tandem XML"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#111]
Definition: Output format used by X! series search engines that is based on the XML language BIOML (www.bioml.com).		
Parent: http://edamontology.org/format_3245

**Comment by joncison** [comment]
Done in EDAM_1.14
"X!Tandem XML"
http://edamontology.org/format_3711

@veitveit is this binary or text format?

**Comment by veitveit** [comment]
xml text format. decribed here:
http://www.thegpm.org/docs/X_series_output_form.pdf

2016-02-23 12:47 GMT+01:00 Jon Ison <notifications@github.com>:

> Closed #111 <https://github.com/edamontology/edamontology/issues/111>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edamontology/edamontology/issues/111#event-561482912>.
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
Thanks!
