### ISSUE TITLE
New format "WIFF format"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#112]
Definition: Mass spectrum file format from QSTAR and QTRAP instruments (ABI/Sciex)		
Parent: http://edamontology.org/format_3245		
Synonym: wiff

**Comment by joncison** [comment]
Done in EDAM_1.14
"WIFF format"
http://edamontology.org/format_3710
@veitveit I've set this as binary format, let me know if I got it wrong

**Comment by veitveit** [comment]
Not really clear whether it is a binary format. But it requires a
closed-source library from the vendor which is a strong indicator.

2016-02-23 12:27 GMT+01:00 Jon Ison <notifications@github.com>:

> Done in EDAM_1.14
> "WIFF format"
> http://edamontology.org/format_3710
> @veitveit <https://github.com/veitveit> I've set this as binary format,
> let me know if I got it wrong
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edamontology/edamontology/issues/112#issuecomment-187660693>
> .
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
OK I set it to binary
