### ISSUE TITLE
new operation "spectral library search"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#118]
Definition:  Determination of best matches between a (tandem) mass spectrum and a database of spectra
Synonyms: Spectral library search of peptides
Parent: http://edamontology.org/operation_3646

**Comment by joncison** [comment]
Done in EDAM_1.14
"Spectral library search"
http://edamontology.org/operation_3725

**Comment by joncison** [comment]
bit worrying that this term didn't exist (http://edamontology.org/format_3725 is "SBOL" format)
no idea what happened
anyhow now in EDAM_dev.owl
"Spectral library search" (http://edamontology.org/operation_3801)
