### ISSUE TITLE
need for tooling to handle updating EDAM-annotated resources

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#12]
There is a need to provide tools to handle EDAM annotations that refer to deprecated terms, as well as clear guidelines for annotators to handle such cases.

**Comment by ManonGros** [comment]
I've noticed that some of the deprecated terms are not in the newest ontology. For example, the term labeled as 'Normalized microarray data' is a class in the ontology 1.6 but not in the 1.8 (even tagged as a deprecated term). If all the terms were kept as classes in the newest ontology, it would make automated updates easier (at least for me). Would it be possible to do so? or is it too heavy?

**Comment by hmenager** [comment]
Actually the Normalized microarray data class did not dissapear, it was renamed. Its id is http://edamontology.org/data_3112, with the label set to _Normalized microarray data_ in EDAM 1.6 but to _Gene expression matrix_ in 1.8 (though it mentions _Normalised microarray data_ as an exact synonym). If you ever find a term which actually completely dissapears from EDAM, please tell us, as it would indeed be a major issue!

**Comment by ManonGros** [comment]
I apologize, I didn't check the IDs. Thanks for the answer =)
