### ISSUE TITLE
clean up TSV CSV DSV formats

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#120]
Currently we only have one format, called TSV
What we need is DSV (Delimiter separated values) as a superclass
- https://en.wikipedia.org/wiki/Delimiter-separated_values
  and two distinct subclasses, CSV and TSV

**Comment by matuskalas** [comment]
For the coming release 1.5, I refined and corrected the existing [TSV](http://edamontology.org/format_3475) format with adequate synonyms, extensions, media types.

```
    <owl:Class rdf:about="http://edamontology.org/format_3475">
        <rdfs:label>TSV</rdfs:label>
        <oboInOwl:hasExactSynonym>Tab-separated values</oboInOwl:hasExactSynonym>
        <oboInOwl:hasBroadSynonym>Tabular format</oboInOwl:hasBroadSynonym>
        <oboInOwl:hasBroadSynonym>Delimiter-separated values</oboInOwl:hasBroadSynonym>
        <oboInOwl:hasBroadSynonym>DSV</oboInOwl:hasBroadSynonym>
        <oboInOwl:hasRelatedSynonym>Comma-separated values</oboInOwl:hasRelatedSynonym>
        <oboInOwl:hasRelatedSynonym>CSV</oboInOwl:hasRelatedSynonym>
        <rdfs:subClassOf rdf:resource="http://edamontology.org/format_2330"/>
        <oboInOwl:hasDefinition>Tabular data represented as tab-separated values in a text file.</oboInOwl:hasDefinition>
        <created_in>1.7</created_in>
        <oboInOwl:inSubset rdf:resource="&oboOther;edam#edam"/>
        <oboInOwl:inSubset rdf:resource="&oboOther;edam#formats"/>
        <file_extension>tsv|tab</file_extension>
        <oboInOwl:hasDbXRef rdf:resource="http://filext.com/file-extension/TSV"/>
        <media_type rdf:resource="http://www.iana.org/assignments/media-types/text/tab-separated-values"/>
        <rdfs:seeAlso>https://en.wikipedia.org/wiki/Delimiter-separated_values</rdfs:seeAlso>
        <rdfs:seeAlso>http://filext.com/file-extension/CSV</rdfs:seeAlso>
        <rdfs:seeAlso>http://www.iana.org/assignments/media-types/text/csv</rdfs:seeAlso>
    </owl:Class>
```

For the case we __really__ need a finer distinction, or for further refinements, I'm leaving this issue as a compromise open, unassigned, but marked _done - staged for release_.

To consider:
- Bioinformaticians are more familiar with "Tabular" and "TSV" than the other terms, what should influence the choice of primary label and hierarchy.
- What is the definition of a TSV? Is "tabular" less strict than TSV? Are bioinformatics "tabular" formats TSVs? Are they really "tabular"? Should they then be under the _TSV_/_Tabular_ concept? All a matter of definitions.
- Should the _TSV_/_Tabular_ concept be at all represented in EDAM? It's only useful for "custom" "tabular" formats.

**Comment by veitveit** [comment]
Why not giving it the label _Delimiter-separated file_? TSV is too specific and aims to describe files with values separated by tabs. This is normally not the case (got commas, semicolons, ...) and then they are not TSV files. I.e., I disagree with saying "Bioinformaticians are more familiar with Tabular and TSV than with the other terms".

Voting for a superclass as @hmenager proposed. TSV and CSV can be added as subclasses if needed.

**Comment by joncison** [comment]
Done in EDAM_1.16

DSV
CSV is_a DSV
TSV is_a DSV

**Comment by veitveit** [comment]
We can close this one, right?

**Comment by joncison** [comment]
I'm closing.  There may still be fine-grained changes but @matuskalas can always reopen / fix if not happy.
