### ISSUE TITLE
mauve xmfa format

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#122]
http://darlinglab.org/mauve/user-guide/files.html

**Comment by veitveit** [comment]
Name: eXtended Multi-FastA (XMFA) file format.
Synonyms: XMFA format, .alignment format
Definition:  Standard file format used by genome alignment systems that align sequences with rearrangements. The XMFA file format supports the storage of several collinear sub-alignments.
Documentation: http://darlinglab.org/mauve/user-guide/files.html

_Observation_: The link contains information about quite a few additional file formats that are more specific to the Mauve software.
