### ISSUE TITLE
Update mention of EDAM in Debian Med policy

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#123]
Andreas says ... "I'd be happy if someone would take over the job suggested by Fabian to mention EDAM fields in our policy.  I personally do not feel capable to do this since I'm simply lacking the biologic background.  We also should have a record inside Debian Wiki to document what we drop
into the debian/upstream dir.  I started creating a paragraph at
https://wiki.debian.org/UpstreamMetadata#Fields-1

but this needs enhancement!  Please everybody who feels concerned about EDAM classification try to enhance and lets not wait until next years sprint."

jison@cbs.dtu.dk wrote:

> Folks
> 
> The link to OLS was to a deprecated ontology browser running an ancient version of EDAM.
> 
> Please use this one instead (it's in beta, so go steady):
> http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=EDAM
> 
> Alternatively you can use this:
> http://bioportal.bioontology.org/ontologies/EDAM/
> 
> ps. both now include EDAM_1.13 just released post-hackathon.  Thanks for the hard work !
> 
> > Hi Fabian,
> > 
> > thanks for the very helpful and needed hint.  I was waiting a bit since Michael intended to work on the structure of the policy a bit and I did not wanted to shot on a moving target.  Michael, could you comment on this how and where you would like to see this information?
> > 
> > Kind regards
> > 
> > ```
> >  Andreas.
> > ```
> > 
> > On Sat, Feb 06, 2016 at 04:36:34PM +0100, Fabian Kl�tzl wrote:
> > 
> > > The new edam files should also be mentioned in our team policy. Below is
> > > a quick mock up; But we might also need to write a proper spec.
> > > 
> > > Best,
> > > Fabian
> > > ## debian/upstream/edam
> > > 
> > > This is a machine-readable file to categorize where in life-science this package has its application. The categories themselves come from EDAM and are arranged in YAML format. Check the [EDAM Ontology Browser](http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=EDAM) for terms that might fit the package.

**Comment by joncison** [comment]
@matuskalas @hmenager  - is this still relevant ?  can action be taken?

**Comment by matuskalas** [comment]
We should look at this, time permitting (we - I mean the Debian Med enthusiasts)
