### ISSUE TITLE
Add neuromics / eurenomics 

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#125]

**Comment by veitveit** [comment]
Both terms do not appear to be related to -omes or molecule types like transcriptomics (transcripts, mRNA), ... 
There is now neurome or eurenome.

Neuromics is a reasearch project: Neuromics aims to revolutionize diagnostics and develop new treatments for ten major neuromuscular and neurodegenerative diseases.

Eurenomics is a consortium devoted to improving the lives of patients affected by rare kidney diseases

Hence, I don't think these terms should be included

**Comment by joncison** [comment]
Cool, thanks - so I close this.
