### ISSUE TITLE
Migrate issues from NGS hackathon

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#128]
https://docs.google.com/spreadsheets/d/1OL0zoPwZhR5UaHDNsfxwhxno18vLHDJnJtwJ2pHXahA/edit#gid=0

**Comment by veitveit** [comment]
Most of the issues are already solved.

Added issue #258, 

Issues not clear whether still relevant:
- Class annotation of "deprecation candidate" for things we're not certain should stay	(comment: Could hack this into "deprecated" )
- Class annotation of "addition candidate" for things we're not certain we should add	(comment: Could hack this into "deprecated" )
- Add topic for QTL mapping for other molecular phenotypes in addition to gene expression (TF binding, chromatin accessibility, histone modifications)   (comment: probably too specific)

**Comment by joncison** [comment]
@veitveit : thanks!  We now have ``<deprecation_candidate>`` annotation and I'm not sure we need ``<addition_candidate>``.

The outstanding issue is:

- _Add topic for QTL mapping for other molecular phenotypes in addition to gene expression (TF binding, chromatin accessibility, histone modifications) (comment: probably too specific)_

Could you please create a separate issue for this (clarifying what action to take a bit) - see _Genetic mapping_ (http://edamontology.org/operation_0282) where _QTL mapping_ is narrowSynonym - and then close this issue.

**Comment by veitveit** [comment]
For QTL mapping, see #335
