### ISSUE TITLE
Different concepts with the same exact synonym or preferred label

### ISSUE THREAD

**Issue by krdav** [edamontology/edamontology#131]
I am reading the CSV version (version 1.14) of EDAM and I see that
some entries share the same exact synonym or share preferred label
and exact synonym.

Here is the list of labels where the problem occurs and also the lines in the CSV file where the reoccurrence has been seen:
Preferred label: Image data, Seen both in line: 142 and 266
Preferred label: Audiovestibular medicine, Seen both in line: 369 and 395
Preferred label: Audiovestibular medicine, Seen both in line: 395 and 1105
Preferred label: DNA sequences, Seen both in line: 535 and 1134
Preferred label: Sequence feature name, Seen both in line: 393 and 1292
Preferred label: Diagnostic markers, Seen both in line: 1015 and 1411
Preferred label: MSF, Seen both in line: 999 and 1422
Preferred label: Image data, Seen both in line: 266 and 1740
Preferred label: Amino acid data, Seen both in line: 755 and 1740
Preferred label: Hidden Markov model, Seen both in line: 1584 and 1995
Preferred label: Diagnostic markers, Seen both in line: 1411 and 2334
Preferred label: biobanking, Seen both in line: 2214 and 2610
Preferred label: Data handling, Seen both in line: 658 and 2801
Preferred label: SRA, Seen both in line: 899 and 2907
Preferred label: Chemical biology, Seen both in line: 2131 and 2977
Preferred label: Text, Seen both in line: 1935 and 3007
Preferred label: Ontology comparison, Seen both in line: 145 and 3086

**Comment by joncison** [comment]
Fixing these now.  In future, we need auto-checks (https://github.com/edamontology/edamontology/issues/170).

**Comment by joncison** [comment]
OK, all fixed in EDAM_1.15.  There were a lot of bugs - great if we can catch these in future @hmenager  :)
