### ISSUE TITLE
Topics and operations with the same preferred label

### ISSUE THREAD

**Issue by krdav** [edamontology/edamontology#132]
Topics and operations preferred labels that are the same or have the same
exact synonyms. There can be a rational behind having the same
label because it can have different meaning in the context of being
either a topic or an operation. However it is still a rather confusing
mix, so I will just provide the list of concepts so you know them and
can flag them. If they could be distinguished by a small change in name I think this could add to usability.

The list comes here:

{'data handling',
  'dna mapping',
  'exome sequence analysis',
  'gene expression analysis',
  'mapping',
  'nucleic acid analysis',
  'nucleic acid structure analysis',
  'protein analysis',
  'protein secondary structure',
  'protein structure analysis',
  'sequence analysis',
  'sequence assembly',
  'structure analysis',
  'structure prediction',
  'text mining'}

**Comment by joncison** [comment]
I've improved this a bit in EDAM_1.15 ... but the issue cannot (and should not) be made to go away completely (EDAM is 4 ontologies in one file after all).  

@hmenager : to auto-catch such cases in future, see https://github.com/edamontology/edamontology/issues/171
