### ISSUE TITLE
Missing Genome data

### ISSUE THREAD

**Issue by dvallenet** [edamontology/edamontology#134]
The term Genome is missing in Data while "Genome report" is present.

**Comment by joncison** [comment]
In EDAM_1.15, "Genome sequence" is a narrowSynonym of "Nucleic acid sequence" (http://edamontology.org/data_2977).

The concept "Genome" I take more as a biological entity or phenomenon, it is therefore out of the current scope of EDAM (i.e. data types including identifiers, data formats, operations and topics).  We used to model entity / phenomenon in the early days, but moved away from doing so.
