### ISSUE TITLE
EDAM term missclassification : Differential Expression Analysis

### ISSUE THREAD

**Issue by tdayris** [edamontology/edamontology#136]
Hi,

I think "Differential Expression Analysis" should not be classified under "Gene expression profile", as Differential Expression Analysis can apply to any genomic object (Transcripts, ...), with their own statistical challenges and biological questions.

Thanks

**Comment by veitveit** [comment]
Valid point. The term can also be applied to other omics objects such as proteins/lipids and metabolites.

An easy solution would be rename the term to _Differential gene expression analysis_

Probably better: 
Make _Differential expression analysis_ subclass of _Comparison_, and then add _Differential gene expression analysis_, _Differential protein analysis_ et al.

There methods that are generally applicable and there are the ones strongly biased towards a specific data type.

**Comment by joncison** [comment]
In EDAM_1.15

"Differential expression analysis" (http://edamontology.org/operation_3223) is renamed to "Differential gene expression analysis" and moved one level up (now a child of "Nucleic acid comparison" (http://edamontology.org/operation_2998) 

"Differential protein expression analysis" (http://edamontology.org/operation_3741) added under "Protein comparison" (http://edamontology.org/operation_2997)

Both child of new "Differential expression analysis" (http://edamontology.org/operation_3742) under "Comparison" (http://edamontology.org/operation_2424)

I wonder though ... is is OTT and be simplified in future :)  Let's see ... thoughts welcome.
