### ISSUE TITLE
new data "protein identification"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#139]
definition: Identifying a protein, e.g. by inference from one or more peptide identifications or other method.
parent: http://edamontology.org/data_0897

**Comment by joncison** [comment]
I'm a bit confused.  Are you after a type of data, or an operation ?

We have:

Peptide mass fingerprint
http://edamontology.org/data_0944

Protein fragment weight comparison
http://edamontology.org/operation_2929

please advise

**Comment by veitveit** [comment]
It is a data type. Probably better definition:
Identification of a protein, e.g. by inference from one or more peptide identifications or other method.

**Comment by joncison** [comment]
Hmm, I think this is covered by "Protein report" (http://edamontology.org/data_0896) or one of its kids.  Otherwise, we can create a new concept under there ... but we need to be very conservative about doing so (in the past there were **far** too many *report concepts).  I'd prefer a synonym if possible.  

Back to you ... :)

**Comment by veitveit** [comment]
This is a tricky one then. "Protein report" states that it needs to be
human-readable and this is not necessarily the case. "Protein
identification" is intimately related to "Peptide identification" which is
child of "Peptdie property". "Protein property" would also fit as one can
understand "Protein identification" as the set of typical spectra one
obtains when running the protein through a mass spectrometer.

We could change the definition to:
"Identifying a protein, e.g. by inference from one or more peptide
identifications by mass spectra or other method."

Or am I pushing too much? :)

2016-05-10 10:58 GMT+02:00 Jon Ison <notifications@github.com>:

> Hmm, I think this is covered by "Protein report" (
> http://edamontology.org/data_0896) or one of its kids. Otherwise, we can
> create a new concept under there ... but we need to be very conservative
> about doing so (in the past there were *far* too many *report concepts).
> I'd prefer a synonym if possible.
>
> Back to you ... :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/edamontology/edamontology/issues/139#issuecomment-218098681>
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
:)

Done in EDAM_1.16

So I adjusted the definition of  _Peptide identification_ (http://edamontology.org/data_0945) (which already almost covered the concept) to now say ....

"Protein or peptide identifications with evidence supporting the identifications, for example from comparing a peptide mass fingerprint (from mass spectrometry) to a sequence database, or  the set of typical spectra one obtains when running a protein through a mass spectrometer."

and defined exact_synonym of "Protein identification"

Hope this a pragmatic solution ?

**Comment by veitveit** [comment]
Looks good for me!
