### ISSUE TITLE
Easy reference document for EDAM

### ISSUE THREAD

**Issue by tetron** [edamontology/edamontology#14]
EDAM should provide a simple searchable text or HTML document that lists the label, identifier and description for each term in a simplified hierarchy.

**Comment by jongithub** [comment]
Go here:
http://bioportal.bioontology.org/ontologies/EDAM/

See "Submissions" section, "Downloads" column, "CSV"

and take a look.  Will it do ?

Cheers
Jon

**Comment by tetron** [comment]
No, the CSV file provided by bioportal is still not usable with only basic text editor or web browser.  I'm looking for something that's formated for human readability that can serve as a reference for someone who is using EDAM for annotations within some other system (specifically, https://github.com/common-workflow-language/common-workflow-language) and wants to find the correct identifier for something without having to plow through bioportal or load up Protege.  For example tagging a file with it's EDAM format.  I've been discussing this with Hervé and he asked me to bring the discussion here.

**Comment by jongithub** [comment]
Can you pls. make a proposal (mock-up or example file format) of what you want - that we can take a look at ?  Thanks.

**Comment by pekrau** [comment]
In my opinion, the EDAM ontology should have its primary existence on the web, as a web service. It should serve HTML by default and JSON if specified in the request header. One HTML page (= JSON document) for each term, with links to all related (up/down, etc). Of course, aggregate pages could also be designed. The URL ought to be the unique identifier for a term.

If I have time, I might whip up a prototype implementation. The main stumbling block is, I suspect, the update policy. If a term can change meaning, in principle, this will cause problems. Not sure if this is just a theoretical problem.

**Comment by tetron** [comment]
@pekrau yes, from an outside perspective it's very strange that http://edamontology.org/page doesn't present the actual terms of the ontology in a nice HTML reference page.  How about using a documentation tool such as https://github.com/modelfabric/yowl ?

**Comment by jongithub** [comment]
Thanks for these suggestions both, we will look towards a HTML and JSON rendering of each concept and all of each EDAM, maybe using YOWL.  Generation of such files needs to be part of the routine maintenance process.

**Comment by hmenager** [comment]
I wrote a draft script the other day that generates an extremely simple file for each EDAM kind of terms (topic, operation, data, format), showing the term hierarchy. It is here: https://gist.github.com/hmenager/6eeca9911e625db09af4
I tried to use yowl, and couldn't get any result out of it using EDAM :(

**Comment by pekrau** [comment]
Thanks! Looks useful.
/Per K

2015-04-09 22:16 GMT+02:00 Hervé Ménager <notifications@github.com>:

> I wrote a draft script the other day that generates an extremely simple
> file for each EDAM kind of terms (topic, operation, data, format), showing
> the term hierarchy. It is here:
> https://gist.github.com/hmenager/6eeca9911e625db09af4
> I tried to use yowl, and couldn't get any result out of it using EDAM :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edamontology/edamontology/issues/14#issuecomment-91345593>
> .
>



-- 
Per Kraulis, Ph.D.
Systems Architect, National Genomics Infrastructure (NGI), SciLifeLab.
Dept Biochemistry and Biophysics, Stockholm University.
+46 (0)8 5248 1465 http://www.scilifelab.se/
Visiting address: Tomtebodavägen 23A, Karolinska Institutet Science Park,
Solna
Mailing address: SciLifeLab Stockholm, Box 1031, 171 21 Solna, Sweden

**Comment by joncison** [comment]
I'm closing this now ... let us know if more is needed
