### ISSUE TITLE
Shotgun metagenomics

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#143]
narrow synonym of metagenomics (Topic)

**Comment by joncison** [comment]
Done in EDAM 1.15

**Comment by matuskalas** [comment]
Strictly speaking, it should probably be an _exact synonym_.

On the other hand, many wrongly use the term _metagenomics_ when they mean __environmental/biome sequencing__ or even more generally __environmental/biome omics__.

If nothing else, these should be added as _broad synonyms_.

And most correctly either: 

a) __Environmental omics__ as the preferred term, with all the other mentioned terms as _narrow synonyms_.

b) __Environmental sequencing__ as the preferred term, with __environmental omics__ as a _broad synonym_, __biome sequencing__ as an _exact synonym_, and with all the other mentioned terms as _narrow synonyms_.

**Comment by matuskalas** [comment]
Fixed for now in 54ff0e9bca646bc1880e4fd556785f2fe053622f (thus re-labelled _done - staged for release_), but the discussion about a better primary term stays open (thus not _**Closed**_).

**Comment by joncison** [comment]
_Environmental sequencing_ and _Biome sequencing_ added as narrow_synonym.  and _Environmental omics_ added as broad_synonym to _Metagenomics_ 

_Environmental omics_  is not a common term (3700 hits) and has no Wikipedia page, compared to _Metagenomics_ (708,000 hits)  hence it cannot be the parent.

**Comment by matuskalas** [comment]
Ok, thanks for adding! :+1: 

But if _Metagenomics_ is the primary label, then it should have:

- _broad synonyms_: _Environmental sequencing_, _Biome sequencing_, _Environmental omics_
- _exact_ (or maybe _narrow_) _synonym_: _Shotgun metagenomics_

I can also double-check and update those when I'm doing my edits...
