### ISSUE TITLE
Missing biodiversity concepts

### ISSUE THREAD

**Issue by luispedro** [edamontology/edamontology#152]

**Comment by luispedro** [comment]
Alpha/beta diversity.

**Comment by joncison** [comment]
In EDAM_1.15:

Alpha diversity
http://edamontology.org/data_3737

Beta diversity
http://edamontology.org/data_3738

Gamma diversity
http://edamontology.org/data_3739

all children of:
Ecological data
http://edamontology.org/data_3736

This is maybe stretching the "bioinformatics" scope of EDAM, or maybe not :)  Need to discuss with the EDAM core-dev ...
