### ISSUE TITLE
Missing "sequence depth normalization"

### ISSUE THREAD

**Issue by mlangill** [edamontology/edamontology#156]

**Comment by veitveit** [comment]
Possible parent: Read depth analysis and/or Standardization and normalization
Definition: Adjustment of sequencing data sets by means of scaling factor to enable their comparison.

**Comment by joncison** [comment]
"Gene calling" in EDAM_1.15 defined as exactSynonym of "Gene prediction" (http://edamontology.org/operation_2454)

If this is not OK, please write back.
