### ISSUE TITLE
Inconsistency of bio.tools with the EDAM?

### ISSUE THREAD

**Issue by lpravda** [edamontology/edamontology#161]
Do you guys reflect changes made to the EDAM ontology to the bio.tools registry? Today I have played with the MOLE (https://bio.tools/tool/ELIXIR-CZ/MOLE/2.0) and tried to store changes made. Didn't work as it seems that the original topic with the id Protein-ligand interaction (topic_3514) has gone obsolete from the EDAM ontology since v. 1.13, however, the entry in the registry remained untouched after this. I think if this is the case, it is a serious issue which introduces inconsistencies to the database and the pain will grow over time.

What are your thoughts, or how are you dealing with these situations?

**Comment by joncison** [comment]
short answer is no, not yet.  and yes, this def. needs to be done ! 

The issue / thought are here:
 https://biotools.sifterapp.com/issues/67

**Comment by lpravda** [comment]
I can't access it. Which kind of login do I need for accessing this page? Or do I have to make a new registration somewhere?

**Comment by joncison** [comment]
sorry Lukas, I created a sifterapp account for you just now

**Comment by joncison** [comment]
Closing this - which is a bio.tools issue, and tracked in sifter (not yet in roadmap, it should be!)
