### ISSUE TITLE
New format "protXML"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#166]
Definition: A format for storage, exchange, and processing of protein identifications created from ms/ms-derived peptide sequence data. 
Parent: format_3245
Documentation: http://tools.proteomecenter.org/formats/protXML/protXML_xmlspy_docs.html
Relation to PSI-MS ontology:  (http://purl.obolibrary.org/obo/MS_1001422)

**Comment by matuskalas** [comment]
Added as @veitveit defined in , towards the release 1.15 (thus labelled _done - staged for release_).

However, as no human-consumable information about this format is available (see http://tools.proteomecenter.org/wiki/index.php?title=Formats:protXML), this format should either be amended with useful information in EDAM, or removed from EDAM (thus not _**Closed**_).

**Comment by veitveit** [comment]
The link I provided leads to a xsd schema,
http://tools.proteomecenter.org/formats/protXML/protXML_xmlspy_docs.html
Isn't that sufficiently human-consumable?

**Comment by veitveit** [comment]
Just found the publication describing protXML, but also pepXML:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1681455/

**Comment by joncison** [comment]
Yes!  With an XSD it's def. in scope.

**Comment by matuskalas** [comment]
@veitveit, @joncison: XSD is not a human-consumable documentation. And an auto-generated webpage from the XSD isn't either.

http://doi.org/10.1038/msb4100024 is very interesting, but it looks more like a test and review of the formats, not introducing them really, does it?

Is there any serious site containing any serious info about protXML?

**Comment by veitveit** [comment]
As for documentation (not introduction of the concept) the paper http://doi.org/10.1038/msb4100024 should be sufficiently concise, no?

There, protXML is described as:
protXML is a file format for storage of protein identifications inferred from MS/MS data and their subsequent protein‐level analysis. There are several different methods to infer protein identifications from database search results. For example, ProteinProphet uses statistical models to combine together the peptide evidence for each protein in order to compute its probability of being present in the sample. Importantly, it apportions identified peptides among all their corresponding proteins in such a way as to derive the simplest set of protein identifications that explain the observed peptides. Another program, QScore, assesses the chance likelihood of protein identifications based upon their size and number of corresponding identified peptides, as well as the effective database and data set sizes (Moore et al, 2002). The database search program Mascot groups together peptides and assigns each protein a score reflecting its confidence (Perkins et al, 1999). These methods output their results in a variety of formats. protXML was developed as an open file format to store the results of protein inference based on MS/MS spectra, and subsequent protein‐level analyses.

The protXML file format (available at http://sashimi.sourceforge.net/schema_revision/protXML/protXML_v3.xsd; see Supplementary information) includes a protein_summary_header element that contains information regarding the contributing peptide identifications, and a program_details element that has information on the particular method used for inferring protein identifications, and a wildcard element that can contain details specific for that method. For example, ProteinProphet substitutes in place of the wildcard a proteinprophet_details element containing parameter settings and summary information specific to its analysis. This organization makes the format easily extensible to new programs for inferring protein identifications.

Protein identifications are contained in protein_group elements that store one or multiple protein elements for sets of related protein family members. Assembly of proteins into groups is chiefly aimed at helping biologists organize data in a useful way by associating together related proteins into a single entry, and could be implemented in different ways. ProteinProphet, for example, groups together identified proteins that are highly related, yet have no unshared corresponding peptides, and hence no unambiguous evidence to discriminate among them. Protein elements have attributes for protein name, number of corresponding peptides, peptide coverage, and percent of data set spectrum identifications (Liu et al, 2004). Protein elements may themselves contain elements for annotation and indistinguishable proteins, those that share with them all the identified peptides. They also contain peptide elements for each corresponding peptide assigned to an MS/MS spectrum, with information on the peptide sequence and its properties, including the optional weight attribute to reflect the confidence that the peptide is evidence for that particular protein.

The protXML format contains the results of subsequent protein‐level analyses applied to the set of protein identifications, such as XPRESS and ASAPRatio protein quantitation (Supplementary information). Each analysis stores an analysis_summary element in the root element with details about the analysis, such as name, date, version, and program settings. In addition, the analysis results for each protein are stored there as an analysis_result element. Unique identifiers are used to link each particular analysis_result with its corresponding analysis_summary. Wildcard elements in the analysis_summary and analysis_result elements are used for details specific to each analysis, and facilitate extensibility of the format to new analyses. For example, any new protein‐level analysis can supply a schema and namespace for its own analysis‐specific summary and result elements. A protXML document in which such elements are inserted in place of the wildcards will then be validated as long as it references the namespace of the analysis along with that of protXML.

**Comment by joncison** [comment]
To my mind, it was never policy that the <documentation> attribute had to point to "human readable" docs, i.e. an XSD is good enough.  Actually, I'd take an XSD any day over a bunch of text.  These formats are for hackers after all.

All we ask for in https://github.com/edamontology/edamontology/blob/master/HOW_TO_CONTRIBUTE.md is "link to format specification" and XSD is precisely that, no ?

**Comment by matuskalas** [comment]
I see this turned into a conceptual discussion.

**Formal specification** and **documentation** are 2 radically different things.

A **formal specification**, such as an XSD, is **useless for** finding out:
* what the format is for
* who maintains it
* who uses it
* how it compares with other formats
* how it's versioned
* where the formal specifications are
* shoudl I use it?
* _etc._
I assume you're getting my point.

A **scientific article** is yet another source of information about a format, including some of the points I wrote just above, but it's **dead**, _i.e._ not maintained over time.

**Comment by veitveit** [comment]
You obviously make a valid point when you say that neither an xsd file nor a publication are optimal for describing a data format. But I doubt that we find the information you request for all data formats. 

We could distinguish several levels of documentation:
a) no useful documentation available (probably also leading to removal of format from EDAM)
b) only technical information available (library, xsd, example file, ...)
c) full human-readable documentation available but no apparent maintenance
d) maintained full description of data format including detailed information about structure, maintainer, updates, purpose, ...

Would that solve this issue (at least partly)?
Such distinction would also help to identify data formats that become obsolete.

**Comment by joncison** [comment]
Ultimately this boils down to what attributes we have in EDAM, and how far we want to push EDAM into databank territory.  I think a little bit, as one of the core aims of EXCELERATE WP1 is "develop EDAM into a comprehensive catalogue of data formats".  So I think separate attributes could work for:

publication
xsd (or whatever formal machine specification)
docs

as for "maintained" - and some of those (extremely useful) attributes you enumerate Matus, that's beyond our scope I think but I imagine is in scope of BioSharing

**Comment by joncison** [comment]
I made some additions to _protXML_ (http://edamontology.org/format_3747) and copied the conceptual discussions across to https://github.com/edamontology/edamontology/issues/334.

Thus we can close this now.
