### ISSUE TITLE
Possibility to create new classes?

### ISSUE THREAD

**Issue by benjamin44** [edamontology/edamontology#168]
Hello, i need to standardize all of my files in BAM and VCF format. In order to do this, i need to create 3 classes that I couldn't find on the EDAM ontology. Those three classes are : Flowcell, Lane and Run.
- Flow Cell: it's the Flowcell where the analyse was realised
  I think, it could be a subclass of Microarrays.
- Lane: it's the Lane of the Flowcell where the analyse was realized.
- Run: it's the run of the Illumina machine.

Would it be possible to create them?

Thank you.

**Comment by joncison** [comment]
Thanks - and yes!  We'll add them to the next release

May I ask please that you expand the definitions a little bit?  A couple of sentences for each would be fine: the definition should be understandable for a non-expert.

**Comment by benjamin44** [comment]
Thanks for the answer. 
Yes, i can develop a little bit. 

Illumina is an American company that develops, 
manufactures and markets integrated systems for the analysis of genetic 
variation and biological function.


So, 

A "flow cell" is used to immobilise, amplify and sequence up to 1.5 billion molecules at once. This flowcell is composed to 8 "lanes" and in fact, 8 experiments can be allow in a single analyse.



A Lane is one of the 8 Lanes that compose a "flow cell". In this Lane, millions of sequences are immobilized, amplified and sequenced.



A Run should correspond to the number of the analysis. For exemple, if it's the 13th analysis, the run is 13.

I hope that my explanations are clear, if you need further details, you can contact me.

Date: Fri, 29 Apr 2016 01:46:21 -0700

**Comment by joncison** [comment]
Created in EDAM_1.15

"Flow cell"
http://edamontology.org/data_3733

"Lane"
http://edamontology.org/data_3734

"Run"
http://edamontology.org/data_3735

all under "Sequencing metadata name" (http://edamontology.org/data_3732)

I'm assuming these may be specified as inputs to some tool or other, and therefore are within EDAM scope (data including identifiers, data formats, operations, topic)
