### ISSUE TITLE
Implement checks for duplicate synynoms

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#170]
@hmenager  can you add checks that synonyms are unique, all types:
hasExactSynonym 
hasNarrowSynonym
hasBroadSynonym

this will ensure we catch errors, e.g. https://github.com/edamontology/edamontology/issues/131

**Comment by joncison** [comment]
This of course should be namespace aware.

**Comment by joncison** [comment]
@hmenager please move this to the right tracker (https://github.com/edamontology/edamxpathvalidator)

**Comment by hmenager** [comment]
Now moved

**Comment by matuskalas** [comment]
Added points to https://github.com/edamontology/edamxpathvalidator/issues/1, which are mostly about what should be done when duplicates are found. And whether duplicates are desired or not, and to what extent / in which cases. That calls for a separate issue, see #233.
