### ISSUE TITLE
Decide & correct HOW TO EDIT

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#174]
Correct claims about releases.

Refine info on how to edit and how to release.

Mention all info related to GitHub issues and Travis CI.

**Comment by matuskalas** [comment]
Rethink the token workflow.

Rethink merging. _NB._ that IDs have to be updated manually (**EXTREMELY ERROR-PRONE**) including throughout the relations!

Add: please commit and push often!

Add: write meaningful commit messages. Refer to tackled issues (but preferably without automatically closing them before the next release. If that stays the workflow)

Add best practices of dealing with GitHub issues: comments, labels, assignee, mentioning commits, merging, referencing other issues, etc...

**Comment by matuskalas** [comment]
Add: Double-check whether commits are pushed to the public repo.

**Comment by matuskalas** [comment]
And we **must** either:

- Forbid editting in Protégé(!!)

Or

- include an automated canonical reformatter, if possible, with every add/commit/push (See also #173. _NB._ that a manually launched reformatter before every add/commit would just again **keep being forgotten**)

OTHERWISE DIFF AND SUBSEQUENTLY ALL CHANGE TRACKING, MERGING, METRICS, _etc._ IS OUT OF ORDER!

**Comment by matuskalas** [comment]
Decide and document the workflow with **closing** issues and **labelling** them _done - staged for release_.

**Comment by matuskalas** [comment]
### Visual checking
Use http://webprotege.stanford.edu:
1. Have patience
2. Register
3. Log in
4. Upload your local EDAM_dev.owl
5. Click Share
6. Make Private
7. Have patience
8. Visually browse your EDAM
9. Don't edit, or at least don't download
10. Enjoy your EDAM!

**Comment by matuskalas** [comment]
## Please __ALWAYS__ add a label to an issue when closing it! Otherwise changelogging, reporting, and writing release notes are impossible! Please use the following:
* **_done - stages for release_**
* **_duplicate_** -- must first note which issue this a a duplicate of
* **_invalid_** -- write why, _e.g._ not true that a requested concept or term is missing
* **_won't fix_** -- write why, _e.g._ is a bug or a missing feature, but is out of scope or granularity
* **_wrong project_** -- **use https://github-issue-mover.appspot.com/ (needs to be tested!), while need to label with _wrong project_ manually. Preferably don't copy & paste issues manually, then contributors info and parts of discussion may get lost.**

## When closing automatically with commit messages, please add a label manually immediately after.

## After the release is done, __and all release notes and statistics are written__, change _done - staged for release_ to _fixed - released_.

**Comment by matuskalas** [comment]
### When (quick-)fixed an issue, but a discussion is open for eventual further improvements or refactoring, label with **_done - staged for release_** and with **_discussion_**, and **DO NOT CLOSE!**

**Comment by matuskalas** [comment]
Use British English spelling in the main (preferred) labels, and always add American English spelling as synonyms. (Has been reported separately in #184)

**Comment by veitveit** [comment]
Some of the comments above have been implemented into https://github.com/edamontology/edamontologyDocs/blob/master/editors_guide.rst. 
What about the rest (e.g. Visual checking and usage of Protege)?
This issue should be easy to close after getting to consensus of what will need to be documented.

**Comment by joncison** [comment]
@hmenager please move this to the right tracker (https://github.com/edamontology/edamontologyDocs)

**Comment by matuskalas** [comment]
With respect to the **token vs. merging** workflow, a suggestion:

What about if everyone editing `EDAM_dev.owl` (_i.e._ core devs and everyone who sends a pull request) has **their own sequence of IDs**, _e.g._ `edamontology.org/data_mk0001...etc.`, that will be **automatically** replaced with proper IDs either before the release (freeze time), or at some intermediate points, or at every `push` (How to implement? Similar issue to automated reformatting, but more complicated with additional concurrency).

Until the workflow is decided, and necessary automations implemented, this issue should stay here and open. I updated the title accordingly.

**Comment by matuskalas** [comment]
And until we have an automation for consolidating the temporary IDs, we could follow the following points:

- If not adding new concepts and not reformatting things around (_e.g._ with Protégé) and not doing drastic refactoring, you **don't need the token**.
- **Take token for exclusive QUICK changes**, including **manual consolidation of the temporary IDs**. Then first `commit` `EDAM_dev.owl` with `next_id` changed from `XXX` to `TOKEN_TAKEN_<NAME>_XXX`. Everybody will immediately see that **adding new concepts is blocked**.
- If adding concepts, start with changing **in your local file** the `next_id` from `XXX` to _e.g._`XXX__<NAME>012`, then give your next concept a **temporary ID** `http://edamontology.org/data_<NAME>012`, and then update `next_id` to `XXX<NAME>013`. `Commit` and `push origin` as is.
- Before a **consolidation of temporary IDs** occurs, the `next_id` in the common `EDAM_dev.owl` at GitHub will look something like _e.g._ `XXX__ji252__hm013__vs345__mk05`.
- The **"manual" consolidation of temporary IDs** will need a rather trivial script replacing the temporary IDs with proper ones. Thus "manual", meaning that **the consolidation is launched manually**, but done with help of a simple script.

What do you @joncison @hmenager @veitveit think? I'd suggest thinking about it now, and perhaps trying it after the coming release.

**Comment by joncison** [comment]
I think we'll need to revisit this when we get more contributors ... that may happen fairly soon given the ideas for thematic editors

**Comment by joncison** [comment]
This needs to be migrated across to https://github.com/edamontology/edamontologyDocs really.

**Comment by joncison** [comment]
This issue was moved to edamontology/edamontologyDocs#16
