### ISSUE TITLE
Add BAI (BAM index) and/or BAM+BAI format(s)

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#176]
BAM index (.bai) is a separate file, but only makes sense with a corresponding BAM file. Thus one format spread over 2 files is what makes sense. But how to model this scenario with _file extension_ and _media type_? They may need some refinement/extension to model this scenario nicely.
https://www.biostars.org/p/15847/

Ideas, suggestions, comments?

**Comment by matuskalas** [comment]
With respect to the parallel initiative of standardising bioinformatics media types, what do you think about multi-file formats @mr-c and others?

**Comment by mr-c** [comment]
Many systems model BAI as a different file format than BAM. Of course the relationship would be a useful thing to model, but that shouldn't delay its inclusion in EDAM :-)

**Comment by joncison** [comment]
Folks, we have _BAI_ (http://edamontology.org/format_3327) and _BAM_ (http://edamontology.org/format_2572).  So I think we could just add appropriate _file extension_ and _media type_ and on each concept, in due course.  Thus I close this.
