### ISSUE TITLE
Unsatisfiable classes in EDAM 

### ISSUE THREAD

**Issue by simonjupp** [edamontology/edamontology#178]
Hi, 
I noticed EDAM doing some strange stuff in OLS related to issue #175. There's two issues here, one is in EDAM and one is OLS not dealing with unsatisfiable classes properly. I'm fixing the latter now issue here EBISPOT/OLS#87

The problem in Edam is that 'community profiling' is a subclass of both Data and Operation that are asserted to be disjoint. Likewise the problem with 'sequence feature label' is both a subclass of Identifier and Parameter, again also disjoint. 

Cheers
Simon

**Comment by matuskalas** [comment]
Oh I see! Thanks a lot @simonjupp for pinpointing the EDAM side of the problem!

**Comment by hmenager** [comment]
Thank you indeed @simonjupp! @matuskalas, @simonjupp do you have any knowledge/recommendation for a tool that would perform such checks automatically?

**Comment by simonjupp** [comment]
Either Hermit or ELK, both have command line tools or you can use Protege (http://protege.stanford.edu) if you want a GUI for checking these things. 

https://www.cs.ox.ac.uk/isg/tools/ELK/

http://www.hermit-reasoner.com

**Comment by hmenager** [comment]
Thank you so much @simonjupp. No, I do not want a GUI, I want something we
can completely automate as part of a list of sanity checks launched by the
CI process ;)

**Comment by hmenager** [comment]
So, there are two issues here:

- community profiling is not a data concept
- sequence feature label is an identifier and probably also a parameter. that is IMHO ok, so the problem is we should not assume Parameter and Identifier to be disjoint. I'll correct EDAM to that end. @matuskalas, @joncison speak up if you disagree ;)

**Comment by matuskalas** [comment]
Epic @hmenager! :+1: 

However, I don't see a reason why _Sequence feature label_ should be a _Parameter_. But thanks for quick-fixing!

And super awesome with including HermiT into CI! :+1: :+1: :+1:

**Comment by joncison** [comment]
We need to find a way to deprecate "Parameter" ... which is after all a more a "role" of data not a type.

**Comment by matuskalas** [comment]
@joncison :+1: 

Except for _**penalties**_, none of the current (1.15) specialisations of [Parameter](http://edamontology.org/data_2527) are parameters in any way (and can even hardly be used as such, in a role of a parameter of an algorithm or operation)

- _Alignment score or penalty_
  -- scores should go somewhere else, together with other scores
  -- penalties are very different, these are algorithm/tool parameters

- _Sequence attribute_
  -- should go somewhere with other attributes (and seem to be partially mashed up with some kind of "genomic element"/"feature" attributes

- _Sequence features metadata_
  -- _ditto_ as above

- _Text_
  -- Text as part of an article? Or an arbitrary English text? Or another? Should perhaps be better specified

As this is separate from the original concern of this issue, I'm moving it to a new issue #182.
