### ISSUE TITLE
Topic "Immunology" has child Operation "Epitope Mapping"

### ISSUE THREAD

**Issue by smoe** [edamontology/edamontology#18]
Hi Jon,

I had understood that Topics and Operations are disjunct, please ignore this noise if I just happen to be wrong here.

Many thanks and greetings

Steffen

Update: I now see that I was falling into the EBI version 1.3 trap. The NCBO 1.11 does not have this any more.

**Comment by jongithub** [comment]
Apologies, in case you were looking at EDAM on OLS, OLS is out of date but will either be updated or removed from it soon. If removed, EDAM will be put back on OLS, once it's udpated to support OWL format (in Autumn ?)
