### ISSUE TITLE
Deprecate and clean up Parameter

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#182]
@joncison wrote in #178: "We need to find a way to deprecate "Parameter" ... which is after all a more a "role" of data not a type." :+1:

Except for _**penalties**_, none of the current (1.15) specialisations of [_Parameter_](http://edamontology.org/data_2527) are parameters in any way (and can even hardly be used as such, in a role of a parameter of an algorithm or operation)
- _Alignment score or penalty_
  -- scores should go somewhere else, together with other scores
  -- penalties are very different, these are algorithm/tool parameters
- _Sequence attribute_
  -- should go somewhere with other attributes (and seem to be partially mashed up with some kind of "genomic element"/"feature" attributes
- _Sequence features metadata_
  -- _ditto_ as above
- _Text_
  -- Text as part of an article? Or an arbitrary English text? Or another? Should perhaps be better specified

After deprecating _Parameter_, the _disjoint_-ness with _Identifier_, as discussed and acted upon in #178, should be reconsidered and subsequently reintroduced or not.

**Comment by hmenager** [comment]
@matuskalas if deprecating Parameter, why should we even consider re-disjointing it from Identifiers? BTW, Same goes for Parameter/Report disjunction, which is untrue in many cases, where report from softw. A is passed as a parameter of soft B which analyses and parses it.
but overall, +1 for deprecating this Parameter concept, for the same reasons Jon gave in #178

**Comment by joncison** [comment]
In EDAM_1.16:

_Parameter_ is deprecated

All of its kids are now kids of _Data_
