### ISSUE TITLE
Duplicates in numerical parts of EDAM IDs

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#185]
While adding next_id checks to edamxpathvalidator (see #173), I discovered that many numerical parts of EDAM ids have duplicates in other terms, meaning that the numeric part of the concept ID is used in more than one concept ID. No real collision, because there are never full ID collisions, but still... I'm not sure what we should do with such cases: ignore (because no full collision - but dirty), or rename concepts which is also bad if considering that IDs should be persistent?
Opinions requested!

**Comment by hmenager** [comment]
Here's the full error report from my modified edamxpathvalidator:
<pre>
Error: Element ID (numerical part) has already been used in another ID - 'Primers' (http://edamontology.org/topic_0922) -> 'Nucleic acid features report (primers)' (http://edamontology.org/data_0922)
Error: Element ID (numerical part) has already been used in another ID - 'PolyA signal or sites' (http://edamontology.org/topic_1302) -> 'Nucleic acid features report (PolyA signal or site)' (http://edamontology.org/data_1302)
Error: Element ID (numerical part) has already been used in another ID - 'CpG island and isochores' (http://edamontology.org/topic_1304) -> 'Nucleic acid features report (CpG island and isochore)' (http://edamontology.org/data_1304)
Error: Element ID (numerical part) has already been used in another ID - 'Restriction sites' (http://edamontology.org/topic_1305) -> 'Nucleic acid features report (restriction sites)' (http://edamontology.org/data_1305)
Error: Element ID (numerical part) has already been used in another ID - 'Splice sites' (http://edamontology.org/topic_1307) -> 'Nucleic acid features report (splice sites)' (http://edamontology.org/data_1307)
Error: Element ID (numerical part) has already been used in another ID - 'Matrix/scaffold attachment sites' (http://edamontology.org/topic_1308) -> 'Nucleic acid features report (matrix/scaffold attachment sites)' (http://edamontology.org/data_1308)
Error: Element ID (numerical part) has already been used in another ID - 'Operon' (http://edamontology.org/topic_1311) -> 'Gene features report (operon)' (http://edamontology.org/data_1311)
Error: Element ID (numerical part) has already been used in another ID - 'Promoters' (http://edamontology.org/topic_1312) -> 'Nucleic acid features report (promoters)' (http://edamontology.org/data_1312)
Error: Element ID (numerical part) has already been used in another ID - 'Protein membrane regions' (http://edamontology.org/topic_1456) -> 'Protein features report (membrane regions)' (http://edamontology.org/data_1456)
Error: Element ID (numerical part) has already been used in another ID - 'Exons' (http://edamontology.org/topic_2397) -> 'Gene features report (exon)' (http://edamontology.org/data_2397)
Error: Element ID (numerical part) has already been used in another ID - 'Gene transcription' (http://edamontology.org/topic_2399) -> 'Gene transcriptional features report' (http://edamontology.org/data_2399)
Error: Element ID (numerical part) has already been used in another ID - 'DNA mutation' (http://edamontology.org/topic_2533) -> 'Nucleic acid features report (mutation)' (http://edamontology.org/data_2533)
Error: Element ID (numerical part) has already been used in another ID - 'Introns' (http://edamontology.org/topic_2754) -> 'Gene features report (intron)' (http://edamontology.org/data_2754)
Error: Element ID (numerical part) has already been used in another ID - 'VNTR' (http://edamontology.org/topic_2867) -> 'Nucleic acid features report (VNTR)' (http://edamontology.org/data_2867)
Error: Element ID (numerical part) has already been used in another ID - 'Microsatellites' (http://edamontology.org/topic_2868) -> 'Nucleic acid features report (microsatellite)' (http://edamontology.org/data_2868)
Error: Element ID (numerical part) has already been used in another ID - 'RFLP' (http://edamontology.org/topic_2869) -> 'Nucleic acid features report (RFLP)' (http://edamontology.org/data_2869)
Error: Element ID (numerical part) has already been used in another ID - 'DNA polymorphism' (http://edamontology.org/topic_2885) -> 'Nucleic acid features report (polymorphism)' (http://edamontology.org/data_2885)
Error: Element ID (numerical part) has already been used in another ID - 'Protein topological domains' (http://edamontology.org/topic_3118) -> 'Protein features report (topological domains)' (http://edamontology.org/data_3118)
Error: Element ID (numerical part) has already been used in another ID - 'Expression signals' (http://edamontology.org/topic_3123) -> 'Nucleic acid features report (expression signal)' (http://edamontology.org/data_3123)
Error: Element ID (numerical part) has already been used in another ID - 'DNA binding sites' (http://edamontology.org/topic_3125) -> 'Nucleic acid features report (binding)' (http://edamontology.org/data_3125)
Error: Element ID (numerical part) has already been used in another ID - 'Nucleic acid repeats' (http://edamontology.org/topic_3126) -> 'Nucleic acid repeats (report)' (http://edamontology.org/data_3126)
Error: Element ID (numerical part) has already been used in another ID - 'DNA replication and recombination' (http://edamontology.org/topic_3127) -> 'Nucleic acid features report (replication and recombination)' (http://edamontology.org/data_3127)
Error: Element ID (numerical part) has already been used in another ID - 'Signal or transit peptide' (http://edamontology.org/topic_3135) -> 'Nucleic acid features report (signal or transit peptide)' (http://edamontology.org/data_3135)
Error: Element ID (numerical part) has already been used in another ID - 'Sequence tagged sites' (http://edamontology.org/topic_3139) -> 'Nucleic acid features report (STS)' (http://edamontology.org/data_3139)
Error: Element ID (numerical part) has already been used in another ID - 'Protein interaction experiment' (http://edamontology.org/topic_3557) -> 'Imputation' (http://edamontology.org/operation_3557)
</pre>

**Comment by matuskalas** [comment]
Oh, that's a major uncovering @hmenager! Except for the last pair, it looks like a result of a copy-&-paste mess-up.

As a first step, would you please perhaps add to the error report whether a concept is obsolete? Not necessary in the CI, but at least for right now? (if easy to do) By a random browse, I saw that many are deprecated, but not all. And the last pair is still "alive".

For the pairs where both are non-obsolete, we could perhaps deprecate one of them (the one supposedly less used), with a _replaced_by_ pointer to a new clean copy of it, with a new ID. Or some other hack to clean it up.

I'm also adding another, related point to #173, to check _created_in_ and _obsolete_since_.

**Comment by joncison** [comment]
This was a one-off (not a systematic or random) weirdness resulting from minting - the lazy way - the topics from the corresponding biological report concepts.

**Comment by joncison** [comment]
I *think* all those data concepts are deprecated - if so, I'd suggest we just ignore (or rather, raise a WARN message).  In future, check and raise ERROR in case of duplicate numerical ID to non-deprecated class.

**Comment by joncison** [comment]
Been through the list : all are deprecated except the last one (where both concepts are alive).  The least harmful thing to do is ignore this, but not repeat the error.  

Assigning to you Herve to please add the CI test raising WARN or ERROR as indicated above.

**Comment by hmenager** [comment]
@joncison I already did exactly what you're asking, so everything's fine as of https://github.com/edamontology/edamxpathvalidator/commit/46443f23145a3875aeff78c41255161e7d55c31f
;)

**Comment by matuskalas** [comment]
Even if not catastrophically critical, it should at some point be fixed in EDAM, too. _E.g._ by deprecating all such mutant concepts.

**Comment by joncison** [comment]
The only non-deprecated case is 

Error: Element ID (numerical part) has already been used in another ID - 'Protein interaction experiment' (http://edamontology.org/topic_3557) -> 'Imputation' (http://edamontology.org/operation_3557)

both terms are in use in bio.tools, so I propose we do nothing for now (least bad option)
