### ISSUE TITLE
New data "Enrichment report" and "GO term enrichment report"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#186]
**Enrichment report**
Substitute "Pathway and network report" (becomes child)
Parent: "Report"
Definition: An informative report containing a ranked list of ontology terms each associated with a statistical metric, concerning or derived from the analysis of a set of identifiers.

**GO term enrichment report**
Parent: "Enrichment report"
Definition: An informative report containing a ranked list of gene ontology terms each associated with a p-value, concerning or derived from the analysis of a set of gene or protein identifiers.
Synonym: Gene ontology enrichment report, GO term report

**Comment by joncison** [comment]
Done in EDAM_1.16

As requested above

_GO term enrichment report_ (http://edamontology.org/data_3754)
_Enrichment report_ (http://edamontology.org/data_3753)
