### ISSUE TITLE
Add Operation: "Relationship Inference" (Under "Text Mining")

### ISSUE THREAD

**Issue by jmcejuela** [edamontology/edamontology#19]
More info: https://en.wikipedia.org/wiki/Text_mining

**Comment by jongithub** [comment]
Will appear in EDAM_1.12

Relationship inference
http://edamontology.org/operation_3625
"Identify semantic relationships within a text or between two or more texts using text mining techniques."

Suggestion for improved definition welcome!

**Comment by joncison** [comment]
Closing this issue ... EDAM 1.12 out before Christmas !
