### ISSUE TITLE
Revise EDAM topics to support OLS requirements

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#190]
See https://github.com/EBISPOT/OLS/issues/43#issuecomment-224551785

**Comment by joncison** [comment]
The mapping is here
https://docs.google.com/spreadsheets/d/1XPo31DvhXvCdn93xNKzjb-15T83uwQyC9QQeLlH6AwQ/edit#gid=0

**Comment by veitveit** [comment]
All of the suggestions look good to me (also the questions)

**Comment by joncison** [comment]
All done in 1.21.

We may get answers to the questions, and thus a further round of edits.  But closing for now.
