### ISSUE TITLE
Requesting new Term "nmrML" in EDAM

### ISSUE THREAD

**Issue by DSchober** [edamontology/edamontology#193]
Dear Edam Curators.
Please consider the addition of the following new open source data standard for 1D NMR raw data for inclusion into EDAM:

http://nmrml.org/

The Nuclear Magnetic Resonance Markup Language (nmrML) is modeled along the same principles like mzML for Mass Spec (by PSI). We are nmrML for Nuclear Magnetic Resonance data (by MSI).

So, a potential new class would look like this:

                                                

<owl:Class    rdf:about="http://edamontology.org/format_ID">
  rdfs:labelnmrML/rdfs:label
  <rdfs:subClassOf rdf:resource="http://edamontology.org/format_2332"/>
  <rdfs:subClassOf rdf:resource="http://edamontology.org/format_ID for 'NMR data standard' "/>
  rdfs:commentnmrML is the open source xml standard developed by the EU Cosmos Program in compliance with the MSI. It consists of an XSD and an accompanying CV.
  /rdfs:comment
  <created_in>1.0</created_in>
  oboInOwl:hasDefinitionnmrML format for raw 1D NMR output data from Bruker and Varian/Agilent Instruments, standardised by the metabolomics standards initiative and financed through Cosmos and PheNoMeNal EU grants.
/oboInOwl:hasDefinition
  <documentation rdf:resource="http://nmrml.org"/>
  <oboInOwl:hasDbXref rdf:resource="http://nmrml.org"/>
  <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/edam#edam"/>
  <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/edam#formats"/>
/owl:Class

It requires an additional superclass labeled 'NMR data standard' or 'nuclear magnetic resonance spectroscopy data standard'.
You should link it with a 'nmr raw data' and your 'nmr spectrum' class....

 Best regards, 
  Daniel Schober (COSMOS).

**Comment by joncison** [comment]
duplicates https://github.com/edamontology/edamontology/issues/261
