### ISSUE TITLE
Requesting new term in EDAM

### ISSUE THREAD

**Issue by germa** [edamontology/edamontology#194]
Hello EDAM curators,

I would like to request a term for the
SEQUEST results file (.out) format 

Cheers,
Gerhard Mayer

**Comment by joncison** [comment]
Thanks Gerhard 

Can you please provide a link to where it's defined.

Also : in basic terms, what type of data is this format used for?

Thanks!

**Comment by germa** [comment]
The SEQUEST.out format is the results format of the widely used proteomics search engine SEQUEST.
Unfortunately there is no official description out there, since it's a proprietary format of Thermo.

**Comment by veitveit** [comment]
It would be "SEQUEST .out file"

Definition: "Raw" result file from SEQUEST database search.
Parent: Mass spectrometry data format

in a similar poorly annotated manner as "Mascot .dat format".

2016-07-13 12:19 GMT+02:00 Gerhard Mayer <notifications@github.com>:

> The SEQUEST.out format is the results format of the widely used proteomics
> search engine SEQUEST.
> Unfortunately there is no official description out there, since it's a
> proprietary format of Thermo.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/edamontology/edamontology/issues/194#issuecomment-232315750>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APEZhX_k03ERxlx96oWIrJfYz0C2ILGsks5qVLucgaJpZM4JKRdV>
> .
>



-- 
            \|||/
           (o o)
 ----ooO-(_)-Ooo----

Don't worry about life; you're not going to survive it anyway.

http://computproteomics.bmb.sdu.dk

**Comment by joncison** [comment]
OK - as a rule, "tool specific" formats are out of scope, with the exception (like this one) where the tool and hence format is very widely used.

**Comment by joncison** [comment]
In EDAM_1.16

_SEQUEST .out file" (http://edamontology.org/format_3758) is_a _Mass spectrometry data format" (http://edamontology.org/format_3245)
