### ISSUE TITLE
Requesting new terms: CSV, idXML, KNIME datatable

### ISSUE THREAD

**Issue by julianu** [edamontology/edamontology#196]
Hej, I don't know whether this is the correct place to ask for this, but we need some more file formats, which we can use for input and output at bio.tools:
- CSV: the simple comma separated values
- idXML: an XML format, used mainly by OpenMS to store all intermediate information (that is proteomics data like spectrum identification, protein identification, quantification of both). Maybe @timosachsenberg or @jpfeuffer can help to specify this more.
- KNIME datatable: for tools, which run inside KNIME (www.knime.org), it might be interesting whether those directly create KNIME tables or plain files

**Comment by veitveit** [comment]
**CSV** will probably be part of _TSV_ with synonym _CSV_ (we need a more general label for this format)

**idXML**
Definition: xml-file containing information about peptide identifications from mass spectrometry data analysis carried out with OpenMS.
Xsd schema found in http://open-ms.sourceforge.net/schemas/
subClassOf: Mass spectrometry data format, XML

**KNIME**
_Comment:_ @matuskalas Do we already have this type of data format (not a file)? It is covered by the description of _Format_ (specific type of data in memory).
see https://github.com/edamontology/edamontologyDocs/blob/master/technical_details.rst 

Definition: Data table that can be passed/streamed within the KNIME platform.
Description of format: probably best leaving it with knime.org
subClassOf: Workflow format?

**Comment by joncison** [comment]
Yes @julianu - GitHub is the preferred place for requests, thanks for the interest.

In EDAM_1.16

* _CSV_ (http://edamontology.org/format_3752) is_a _DSV_ (http://edamontology.org/format_3751)
* _idXML_ (http://edamontology.org/format_3764)
* _KNIME datatable format_ (http://edamontology.org/format_3765) is_a _Workflow format_ (http://edamontology.org/format_2032)

Not sure about KNIME though.  Strikes me that "KNIME datatable" is a type of data, which can be represented in KNIME native format == KNIME datatable format (is this binary, XML or plain text?)  and maybe other formats?  Please advise if what I've done is not right / enough

**Comment by julianu** [comment]
Thanks for adding these items.
Regarding the KNIME datatables: KNIME uses them internally and makes most of its operations on these tables. These can be written to CSV, TSV, XLS and so on, but may also contain data objects in some cells, which are not easy to export. So, I am not sure if it is really a _Workflow format_, as it does not describe the workflow but only the data passed along in it.
