### ISSUE TITLE
Request for new term

### ISSUE THREAD

**Issue by miantur** [edamontology/edamontology#197]
Dear edamontology-team,

I would like to request a new term for the GPR file format (http://mdc.custhelp.com/app/answers/detail/a_id/17120/related/1). This file format is often used for raw microarray data. There is a general term in EDAM which refers to GPR ("Raw microarray data", http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_3110&jump_to_nav=true) - but there seems to be no separate term.

Thanks in advance,
Michael

**Comment by joncison** [comment]
In EDAM 1.20 we have _Raw microarray data format_ (http://edamontology.org/format_3828) with child of _GPR_ (http://edamontology.org/format_3829).  Apologies @miantur for the huge delay.
