### ISSUE TITLE
Add Relaxed Phylip Interleaved format

### ISSUE THREAD

**Issue by DamCorreia** [edamontology/edamontology#198]
Name: Relaxed Phylip Interleaved
Parent: format_2924
Sibiling: format_1997

"Relaxed Phylip Interleaved" is a Phylip multiple alignment sequences. It differs from Phylip Format (format_1997) on length ID sequence. There no more length restriction to make ID, but whitespaces aren't allowed in the sequence ID/Name because one space separates the longest ID and the beginning of the sequence. Sequences IDs must be padded to the longest ID length.

doc : http://www.phylo.org/index.php/help/relaxed_phylip
doc : http://biopython.org/DIST/docs/api/Bio.AlignIO.PhylipIO-module.html

**Comment by joncison** [comment]
thanks !
