### ISSUE TITLE
Add Topic: "Text Mining" (under "Literature and Reference")

### ISSUE THREAD

**Issue by jmcejuela** [edamontology/edamontology#20]

**Comment by jongithub** [comment]
This exists, see:
http://edamontology.org/topic_0218

"Text mining" is a (narrow) synonym of "Data mining" topic.

**Comment by jmcejuela** [comment]
As a text miner researcher myself, if possible, somehow I would like to see a more clear about distinction between data vs text mining. If already marked as a synonym in the ontology, maybe the interface for tool addition could help on this by showing some tooltip with the list of synonyms? Or at least make able to search by synonyms.

Just my 2 cents.

**Comment by jongithub** [comment]
I appreciate that.  The thing is - the "Topic" branch, for practical reasons, must have only a few hundred concepts in total, and therefore the concepts must be very coarse grained.  

The fine-grained distinction is available within EDAM "Operation" branch, see:
http://edamontology.org/operation_0306

Support for search for synonyms in the registry is planned.   

I'll add synonyms to tool tips to the to-do list for future consideration

**Comment by jmcejuela** [comment]
Nice to hear that! As for me, just close the issue...

**Comment by joncison** [comment]
@jmcejuela, so now we have distinct topics for:

Text mining
http://edamontology.org/topic_0218

Data mining
http://edamontology.org/topic_3473

Hope you like this.

**Comment by jmcejuela** [comment]
You guys are working hard these days. Thanks!
