### ISSUE TITLE
Add BLAST XML v2?

### ISSUE THREAD

**Issue by peterjc** [edamontology/edamontology#200]
EDAM already has  http://edamontology.org/format_3331 _XML format as produced by the NCBI Blast package_

However, the NCBI have introduced a new BLAST XML v2, which I think ought to have a separate EDAM entry: 

https://www.ncbi.nlm.nih.gov/mailman/pipermail/blast-announce/2015q4/000118.html
https://www.ncbi.nlm.nih.gov/mailman/pipermail/blast-announce/2015q4/000118.html

Compared to the original blastxml, blastxml2 has many differences in how the data is tagged.

**Comment by matuskalas** [comment]
Thanks @peterjc for your reminder.

So far, we haven't modelled versions of formats in EDAM, other than GFF/2/3, but perhaps we should. At least to some extent.

Considerable are especially cases when there is a major change between format versions, that is neither forward- nor backward-compatible. In particular with schema-based formats.

**Comment by peterjc** [comment]
I would consider this a major change, neither forward nor backward compatible (despite holding essential same information).

**Comment by hmenager** [comment]
if there is no compatibility between the two versions, it probably means
that a new distinct format should be added in EDAM. @peterjc, do you know
have any knowledge of an official documentation for this format, besides
ftp://ftp.ncbi.nlm.nih.gov/blast/documents/NEWXML/xml2.pdf? Additionally,
the links you include mention a JSON-based version for these formats: do
you think they should be included?

**Comment by peterjc** [comment]
I've just spent several minutes on the NCBI website trying and failing to find anything else.

Also on the FTP site there is ftp://ftp.ncbi.nlm.nih.gov/blast/documents/NEWXML/ProposedBLASTXMLChanges.pdf

And yes, the JSON output would likely also deserve another EDAM entry.

**Comment by hmenager** [comment]
in addition, there is an XML schema (derived from ASN...) available on
http://www.ncbi.nlm.nih.gov/data_specs/schema/ files of interest are
http://www.ncbi.nlm.nih.gov/data_specs/schema/NCBI_BlastOutput2.mod.xsd and
http://www.ncbi.nlm.nih.gov/data_specs/schema/NCBI_BlastOutput.mod.xsd.
couldn't find any documentation on JSON format though.

**Comment by joncison** [comment]
In EDAM 1.20 we have _BLAST XML v2 results format_ (http://edamontology.org/format_3836)
