### ISSUE TITLE
Requesting new term for ProteomeXchange ID

### ISSUE THREAD

**Issue by germa** [edamontology/edamontology#201]
Hi all,

I want ro request a term for ProteomeXchange ID (http://www.proteomexchange.org). ProteomeXchange is a public repository for proteomics data.
The ID's have a format described by the regex    PXD[0-9]{6}

**Comment by veitveit** [comment]
Label: ProteomeXchange ID
Definition: Identifier for mass spectrometry proteomics data in the proteomexchange.org repository 
Parent:  Experiment annotation ID

**Comment by joncison** [comment]
In EDAM_1.16:

_ProteomeXchange ID_ (http://edamontology.org/data_3759) is_a _Experiment annotation ID_ (http://edamontology.org/data_1078)
