### ISSUE TITLE
Missing terms to register Structural Bioinformatics related services

### ISSUE THREAD

**Issue by scapella** [edamontology/edamontology#203]
When registering services at bio.tools, we (at ELIXIR-Spain) could not properly assigned terms to the different services related to molecular dynamics and simulation. We couldn't either register services related to structural bioinformatics e.g. protein structure predictions software.

It would be nice to have an easy way to provide these new terms. If there is already one, I haven't been able to find it.

**Comment by veitveit** [comment]
@scapella: 
Topic _Molecular Dynamics_ is covered by http://edamontology.org/topic_0176
Operation _Protein modelling_ is covered by  http://edamontology.org/operation_0477
and is child of _Protein structure analysis_ http://edamontology.org/operation_2406

Topic _Structure prediction_ is covered by  http://edamontology.org/topic_0082 and is parent of _Molecular dynamics_ 
Operation _Protein structure prediction_ by http://edamontology.org/operation_0474

Where you looking for these? There are quite a few additional related topics and operations.

**Comment by joncison** [comment]
@scapella - if you need new terms just request them using https://github.com/edamontology/edamontology/issues/new

Do the above links help?  Let us know what you need !

**Comment by scapella** [comment]
As I agreed in Rome during the F2F Technical Coordinators meeting,
ELIXIR-ES (BSC & IRB) will propose a new set of EDAM terms for the
Structural biology part based on a Community-driven effort.

Salva

**Comment by joncison** [comment]
Cool.  Please point your guys here:
http://edamontologydocs.readthedocs.io/en/latest/contributors_guide.html#requests

If there are very many requests, there may be a more efficient way (e.g. g-doc or some such).

thanks!

**Comment by joncison** [comment]
I think I can close this, @scapella just post specific requests directly in GitHub.  thanks!
