### ISSUE TITLE
Coverage of EBI-relevant XML formats

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#206]
Extensive list of XML formats listed on EBI website 
http://www.ebi.ac.uk/Tools/webservices/tutorials/aa_xml_formats

**Comment by veitveit** [comment]
In the following, formats in italic are already in EDAM or not supported. Format in bold are candidates for new formats.

_Architecture for Genomic Annotation, Visualization and Exchange (AGAVE)_ does not look supported anymore

 _BioXSD_ already in EDAM

_**BEAST**_ 
Definition: Input file for BEAST Software - Bayesian Evolutionary Analysis Sampling Trees
Parent: Raw sequence format
URL: http://beast.bio.ed.ac.uk/
Type: XML
Data: Sequence, Sequence set
Extension: N/A

_BIOpolymer Markup Language (BIOML)_ Links do not work. Does not look very supported

_Biological Pathways Exchange (BioPAX)_ already in EDAM

_Bioinformatic Sequence Markup Language (BSML)_ already in EDAM

**_Chado-XML_** 
Definition: Chado-XML is a direct mapping of the Chado relational schema into XML.
Parent: Raw sequence format
URL: http://gmod.org/wiki/Chado_XML
Type: XML
Data: Sequence set
Extension: N/A

_DAS XML_ already in EDAM

_EBI Application XML or an older version_ already in EDAM

_Genome Annotation Markup Elements (GAME)_ Links do not work. Does not look very supported

_Gene Expression Markup Language (GEML)_ Does not seem to be supported or popular

**_Helmholtz Open BioInformatics Technology network (HOBIT)_** 
Definition: Helmholtz Open BioInformatics Technology network (HOBIT) covers sequence, sequence alignment, RNA secondary structure and RNA secondary structure alignment formats
Parent: Raw sequence format
URL: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-7-490
Type: XML
Data: Sequence, Sequence set
Extension: N/A

**_HSAML_**
Definition: An alignment format generated by PRANK/PRANKSTER consisting of four elements: newick, nodes, selection and model
Parent: Alignment format (XML)
URL: http://www.ebi.ac.uk/goldman-srv/hsaml/
Type: XML
Data: Sequence alignment report
Extension: N/A

_DDBJ-XML_ Cannot find anything useful here

_EMBL-XML_ already in EDAM

_GenBank XML_ Did not find any documentation

_INSDSeq_already in EDAM

_InterPro XML_ not much documention, seems to be very simple xml-format

_InterPro Features XML_ found nothing

_InterPro Matches Complete XML_found nothing

**_InterProScan XML_**
Definition: Output xml file from the InterProScan sequence analysis application
Parent: Protein domain classification format
URL: https://github.com/ebi-pf-team/interproscan/wiki/OutputFormats
Type: XML
Data: Protein domain
Extension: N/A

_JalView 2 Project_ According to the web page: ... there is no stable schema yet ...

**_KEGG Markup Language (KGML)_**
Definition: The KEGG Markup Language (KGML) is an exchange format of the KEGG pathway maps, which is converted from internally used KGML+ (KGML+SVG) format.
Parent: Biological pathway or network format
URL: http://www.genome.jp/kegg/xml/
Type: XML
Data: Pathway or network
Extension: N/A

_Entrez Gene_ missing documentation

**_PubMed XML_**
Synomym: MEDLINE XML
Definition: Collected entries from biobliographic databases MEDLINE and PubMed
Parent: Bibliographic reference format
URL: https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html
Type: XML
Data: Bibliography
Extension: N/A

_NCBI BLAST XML_ already in EDAM

_MACSIM_ not much to be found

_MAGE-ML_ already in EDAM

_Metadata Object Description Schema (MODS)_ Used in life sciences?

**_MSAML_** 
Definition: A Set of XML Compliant Markup Components for Describing Multiple Sequence Alignments 
Parent: Alignment format (XML)
URL: http://xml.coverpages.org/msaml-desc-dec.html
Type: XML
Data: Sequence alignment report
Extension: N/A

_OBO XML_ already in EDAM

**_OrthoXML_**
Definition: OrthoXML is designed broadly to allow the storage and comparison of orthology data from any ortholog database. It establishes a structure for describing orthology relationships while still allowing flexibility for database-specific information to be encapsulated in the same format.
Parent: Gene annotation format
URL: http://orthoxml.org/xml/Documentation.html
Type: XML
Data: Sequence record
Extension: N/A

_PHYLIP_ already in EDAM

_phyloXML_ already in EDAM

**_Protein Sequence Database Markup Language (PSDML)_**
Definition: Tree structure of Protein Sequence Database Markup Language generated using Matra
Parent: Sequence feature annotation format
URL: http://matra.sourceforge.net/dtdtree/bio/psdml_dtdtree.php
Type: XML
Data: Protein sequence record
Extension: N/A

_HUPO Proteomics Standards Initiative (PSI)_ already in EDAM

_Readseq Bioseq-set_ Not clear. Readseq is a format converter

_RNAML_ already in EDAM

_Systems Biology Markup Language (SBML)_ already in EDAM

**_SeqXML_** 
Definition: SeqXML is an XML Schema to describe biological sequences. 
Parent: Raw sequence format
URL: http://orthoxml.org/xml/Documentation.html
Type: XML
Data: Sequence, Sequence set
Extension: N/A

**_UniParc XML_**
Definition: XML format for the UniParc database
Parent: Sequence feature annotation format
URL: http://www.uniprot.org/uniparc/
Type: XML
Data: Protein sequence record
Extension: N/A

_UniProtKB XML_ already in EDAM

**_UniRef XML_**
Definition: XML format for the UniRef reference clusters
Parent: Sequence feature annotation format
URL: http://www.uniprot.org/uniref
Type: XML
Data: Protein sequence record
Extension: N/A

_Extensible Feature Format (XFF)_ Not much to be found about the format

Summary: There are many xml formats in bioinformatics :-D

**Comment by joncison** [comment]
All now done except for HOBIT XML which I think is obsolete.
