### ISSUE TITLE
Html Widget to pull tools by query

### ISSUE THREAD

**Issue by jmcejuela** [edamontology/edamontology#21]
Use case: group wants to show case all its tools in its own webpage, with all the info kept in the elixir registry

---

This should be simple enough for any group to pull the JSON and create an interface list of it. However, this could be made easier and more standard for all users as a general widget. Furthermore, the widget could include something like "Powered by Elixir Registry" to make some kind of publicity of the registry itself.

**Comment by jmcejuela** [comment]
Matus commented that one group already has this specific to their needs. Cannot promise anything at this moment, but would like to standardize this and use the widget on the rostlab.org webpage.

**Comment by matuskalas** [comment]
Thank you @jmcejuela . Various institution would benefit from having something like this.

It is, however, a request for the Tools Registry, not EDAM. But let's leave it here until the Tools Registry has it's own GitHub repo ;-)

**Comment by jmcejuela** [comment]
True, I realized that later when I posted :-)

Thanks!

**Comment by joncison** [comment]
Wrong tracker, created here instead:
https://github.com/bio-tools/biotoolsregistry/issues/10
