### ISSUE TITLE
VisANT-supported formats

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#211]
Interaction/Pathway/Network data formats supported by VisANT
http://visant.bu.edu/import.htm

**Comment by veitveit** [comment]
**VisML**
Synonym: VisANT xml 
These are left to be added

URL: http://visant.bu.edu/misi/visML.htm
Type: xml
Definition: Default XML format of VisANT , containing all the network information
Parent: Biological pathway or network format
Data: Pathway or Network

**GML**
URL: https://gephi.org/users/supported-graph-formats/gml-format/
Type: Textual format
Definition: GML (Graph Modeling Language) is a text file format supporting network data with a very easy syntax. It is used by Graphlet, Pajek, yEd, LEDA and NetworkX.
Parent: Biological pathway or network format
Data: Pathway or Network
