### ISSUE TITLE
SeqXML formats

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#212]
http://seqxml.org/xml/Main.html

**Comment by veitveit** [comment]
__SeqXML__
Parent: XML, Sequence record format
Definition: XML Schema to describe biological sequences that is designed to be a simple and versatile format to store sequence data. 
Description: http://seqxml.org/xml/Main.html

__OrthoXML__
Parent: XML, (any ideas where it fits?)
Definition: XML schema designed to describe orthology relations. Orthologs are defined as genes in different species deriving from a single gene in the last common ancestor.
Description: http://seqxml.org/xml/Main.html

**Comment by veitveit** [comment]
Same and more info about these terms in issue #206
