### ISSUE TITLE
EMBOSS-supported formats

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#214]
A.1. Supported Sequence Formats
A.1.1. ABI Trace
A.1.2. ACEDB
A.1.3. ASN1
A.1.4. Asis
A.1.5. Clustal
A.1.6. CODATA
A.1.7. DAS
A.1.8. DAS DNA
A.1.9. Debug
A.1.10. EMBL
A.1.11. Experiment (Staden)
A.1.12. FASTA
A.1.13. FASTA (GCG)
A.1.14. FASTA (Pearson)
A.1.15. FASTA (with accession)
A.1.16. FASTA (database and identifier)
A.1.17. FASTA (GI style)
A.1.18. FASTA (NCBI style)
A.1.19. Fastq
A.1.20. Fastq (Illumina)
A.1.21. Fastq (Sanger)
A.1.22. Fastq (Solexa)
A.1.23. Fitch
A.1.24. GCG 8, GCG 9.x and 10.x
A.1.25. GenBank
A.1.26. GenPept
A.1.27. GFF3
A.1.28. GFF2
A.1.29. Hennig86
A.1.30. Intelligenetics
A.1.31. Jackknifer
A.1.32. Jackknifer (non-interleaved)
A.1.33. MASE
A.1.34. MEGA
A.1.35. MEGA (non-interleaved)
A.1.36. MSF
A.1.37. NBRF / PIR
A.1.38. NEXUS / PAUP (interleaved)
A.1.39. NEXUS / PAUP (non-interleaved)
A.1.40. PDB
A.1.41. PDB (nucleotide)
A.1.42. Pfam/Stockholm
A.1.43. PHYLIP (interleaved)
A.1.44. PHYLIP (non-interleaved)
A.1.45. Raw
A.1.46. RefseqP
A.1.47. SELEX
A.1.48. Staden (obsolete)
A.1.49. Strider
A.1.50. SwissProt
A.1.51. Text/Plain
A.1.52. Treecon
A.2. Supported Feature Formats
A.2.1. DASGFF
A.2.2. EMBL, GenBank, DDBJ
A.2.3. GFF3
A.2.4. GFF2
A.2.5. PIR/NBRF
A.2.6. SwissProt
A.3. Supported Alignment Formats
A.3.1. FASTA
A.3.2. Markx0
A.3.3. Markx1
A.3.4. Markx2
A.3.5. Markx3
A.3.6. Markx10
A.3.7. Match
A.3.8. MSF
A.3.9. Multiple
A.3.10. Pair
A.3.11. Score
A.3.12. Simple
A.3.13. SRS
A.3.14. SRS Pair
A.3.15. TCOFFEE
A.3.16. Trace (debugging only)
A.4. Supported Report Formats
A.4.1. DAS GFF Feature Table
A.4.2. Dbmotif
A.4.3. Debug report format
A.4.4. Diffseq
A.4.5. EMBL Feature Table
A.4.6. FeatTable
A.4.7. Genbank Feature Table
A.4.8. GFF Feature Table
A.4.9. Listfile
A.4.10. Motif
A.4.11. Nametable
A.4.12. PIR Feature Table
A.4.13. Regions
A.4.14. SeqTable
A.4.15. SRS
A.4.16. SRS Simple
A.4.17. SwissProt Feature Table
A.4.18. Tab-delimited Format
A.4.19. Table
A.4.20. TagSeq
A.4.21. Trace Feature Table (debugging only)

**Comment by joncison** [comment]
I think most of these are covered, and some of these are EMBOSS-specific and we might not want to pull in.

**Comment by veitveit** [comment]
Most of the should be in.
