### ISSUE TITLE
Should we remove the old EDAM_Topics subset from the NCBO BioPortal?

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#217]
Apparently, it confuses some users which EDAM at BioPortal they should use.

And even if they want only topics (what may not be clear to a new EDAM user), the ones there are probably an old version, aren't they?

[#BLAHmuc](https://twitter.com/hashtag/blahmuc)

**Comment by joncison** [comment]
Yes!  I asked ages ago for them to delete it, but this did not happen.  Will you take this up please?

**Comment by joncison** [comment]
This now gone.
