### ISSUE TITLE
Add synonyms for better text mining applications

### ISSUE THREAD

**Issue by nikolamilosevic86** [edamontology/edamontology#218]
It is useful to have dictionaries of synonyms, acronyms, and abbreviations for each concept in the ontology. Dictionary should include all forms of the certain concept people are using.
Example:
P-value
p\* value
p

Lower case/upper case forms are not necessary since it can be preprocessed, however, hyphens, asterisks, word inflections are necessary.

**Comment by matuskalas** [comment]
Text-mining experts, please give us also more concrete examples if you find some EDAM. You can also submit them as a concrete requirement, or even fork & submit pull-requests if you feel like.

Thanks a million!

[BLAHmuc](https://twitter.com/hashtag/blahmuc)

**Comment by matuskalas** [comment]
What about BrE vs. AmE spelling? Should we also include those?

And another question to both text-mining and other experts, should we mark by dedicated attributes special classes of exact synonyms? _E.g._: AmE (BrE is default. Ok?), inflection(?), alternative punctuation, jargon, ...., _etc._ Which other classes of exact synonyms?

**Comment by joncison** [comment]
Thanks.  For this to be actionable (i.e. appear in EDAM any time soon) we'd appreciate if you can provide details for the specific synonyms etc on specific concepts existing in EDAM, which you'd like to see in the next release.

**Comment by joncison** [comment]
just giving this a nudge; right now we're lacking bandwidth to systematically do this ourselves, but would much welcome specific suggestions.  thanks !!

**Comment by matuskalas** [comment]
Note/status: a **text-mining** expert group formation for EDAM is underway. Slowly but the right direction

**Comment by rioualen** [comment]
Closing this issue. Please open a new issue or pull request if specific synonyms need to be added.
