### ISSUE TITLE
Add systematically statistical concepts to the ontology 

### ISSUE THREAD

**Issue by nikolamilosevic86** [edamontology/edamontology#219]
Some of the statistical concepts are missing, including mean, median, range, standard deviation, percentage. Also, there can be some concepts how people describe statistical data in from the trials (for example sex (male/female) - 16/18). 

It would be useful if some of these concepts contain a list of regular expressions that describe them. An example of such list describing obtaining mean, SD and range can be found [here](https://github.com/nikolamilosevic86/WIET---Wizard-for-Information-Extraction-from-Tables/blob/master/DefaultSintacticRules/StatisticalValues).

Some of the statistical data can be used in combination, presenting combined concept (e.g. mean with standard deviation is usually presented as one data point in statistical tables, but it contains two numbers - one presenting mean, the other standard deviation). It would be useful if these concepts could be somehow linked together in the ontology.

**Comment by matuskalas** [comment]
This is also about adding concepts for concrete **scores/parameters/attributes** within bigger data. Useful for helping integration, parsing, visualisation, ...
Also applicable to _e.g._ [BioXSD](http://bioxsd.org). Maybe also to EMBOSS or Mobyle(?)

It would, of course, be nice to have a dedicated, non-bio-specific ontology of statistical parameters/scores/_etc._. If there is one, or appears one, great!

In addition, it may then be useful (certainly not harmful) to add relation _**is part of**_, in the few cases where it's valid on the **conceptual level** (_i.e._ always). Otherwise, _***is part of*_ of course applies to **concrete data formats** and to **concrete data instances**.

**Comment by joncison** [comment]
Thanks for the suggestions here, agree with your comments Matus although need to be very wary of modelling data per se. 

Still, this is on the margins of EDAM's scope, so we need to think if / how to do it.  @nikolamilosevic86 will you please enumerate a list of concepts you propose to add ?

**Comment by nikolamilosevic86** [comment]
My case study is about information extraction of numerical information from tables in biomedical literature. Some of the concepts I would like to use are:
* integer - just a single integer number (as EDAM is ontology of biomedical data types, this one comes first into the mind for presenting data)
* float
* percentage
* Roman number
* value with the unit (can be integer or float... some link to these values would be useful as well, maybe even some reference to Unit ontology)
* Statistical expression
** Mean & standard deviation (maybe there can be a better name, I am open to discussion)
** Range
* Alternative values
** Alternatives presenting same concept/value (e.g. 12 (40%), meaning there was 12 instances which is 40% of total population)
** Alternatives presenting values for different concepts (e.g. male/female - 12/13)
* Datetime

These are I believe the most common types of data found in literature and that could be useful for literature mining. In case I remember or find some more, I may add it here.

**Comment by veitveit** [comment]
Adding concepts like Integer, Float, ... could be a bit of an overkill. In consequence, one would have to add arrays and matrices of integer, ..., not to forget about data combining different data types. I would look more on describing the biological content instead of the primitive data types.

_Statistical expression_ is an interesting one and _Data_ for statistical terms like mean, s.d. and range are missing. One could add _Statistical report_ to cover all data types containing only statistical expressions. However, these expressions mostly are related to specific data such as for example microarray expression. 

And, not to forget, most data analysis calculate the mean at some point, making it an very generally used concept.

**Comment by matuskalas** [comment]
My gut feeling says that:
- _Integer_, _Float_, _etc._ are more a matter of programmatic and binary representation, not of semantics of a given attribute. And it's the semantics of the attribute that matters in EDAM _Data_, _e.g._ _Score_ or _Tool parameter_/_Metadata_/_Data parameter_ (should go to EDAM in some form? Despite of deprecating the dubious _Parameter_ in #182)
- _Range_ and _Datetime_ I think are relevant to model in EDAM, using some distinguished non-bioinformatics-specific `subset` (see https://github.com/edamontology/edamontology/issues/216#issuecomment-253173286)
- _Percentage_, _Roman number_, _M/F/X_, _etc._ are a matter of representation, too. These can be modelled by regular expression on the side of tool or format specification/schema/documentation

**Comment by joncison** [comment]
+1  

Certainly primitives e.g. xs:integer etc. are definitely out of scope.

**Comment by nikolamilosevic86** [comment]
Ok, if the primitives are out of scope. Just I had a thought that if there is ontology of data types, it should contain even primitive ones. 
However, percentage is not really just a matter of representation, it carries semantics. And it can be together with other statistical data types and formats (mean, median, range, standard deviation, mode, etc.). Datetime probably should probably be in some other subset which would aggregate time related concepts.

**Comment by matuskalas** [comment]
@nikolamilosevic86: Fair enough, percentage could perhaps be squeezed in.

**Comment by matuskalas** [comment]
The previously deprecated "parameter-like" concepts in EDAM were mostly too specific. But perhaps some more generalised ones would be useful.

Especially if we want to enable detailed tools descriptions allowing auto-generation of workbench wrappers and of workflows.

For curiosity and thought, I'm pasting in some obsolete "parameter-like" concepts (from a Travis CI report):

Error  : obsolete consider obsolete - 'Sequence mask character' (http://edamontology.org/data_0851) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Sequence alignment parameter' (http://edamontology.org/data_0864) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'EMBOSS sequence type' (http://edamontology.org/data_1110) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'BLAST sequence alignment type' (http://edamontology.org/data_1121) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Score end gaps control' (http://edamontology.org/data_1395) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Aligned sequence order' (http://edamontology.org/data_1396) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Vienna RNA parameters' (http://edamontology.org/data_1591) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Vienna RNA structure constraints' (http://edamontology.org/data_1592) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Vienna RNA concentration data' (http://edamontology.org/data_1593) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Number of iterations' (http://edamontology.org/data_1693) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Number of output entities' (http://edamontology.org/data_1694) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Hit sort order' (http://edamontology.org/data_1695) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Vienna RNA structural data' (http://edamontology.org/data_2022) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Sequence mask parameter' (http://edamontology.org/data_2023) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Search parameter' (http://edamontology.org/data_2079) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Mutation type' (http://edamontology.org/data_2132) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Results sort order' (http://edamontology.org/data_2134) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Toggle' (http://edamontology.org/data_2135) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Sequence offset' (http://edamontology.org/data_2145) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Threshold' (http://edamontology.org/data_2146) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Color' (http://edamontology.org/data_2151) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Rendering parameter' (http://edamontology.org/data_2152) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Date' (http://edamontology.org/data_2156) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Cardinality' (http://edamontology.org/data_2176) -> 'Parameter' (http://edamontology.org/data_2527)
Error  : obsolete consider obsolete - 'Geotemporal metadata' (http://edamontology.org/data_3105) -> 'Parameter' (http://edamontology.org/data_2527)

**Comment by veitveit** [comment]
In order to get to some conclusion here:
_simple data types_ are out of scope in EDAM

_parameter values_ are part of practically any tool. Using them for tool annotation looks very unpracticable. Imagine annotating a tool that has 100 input parameters. 

_data and format_ data terms usually correspond to items that can be represented by a format (mostly files), also to embrace the `is_format_of`relation. Then mean, percentage, range, ... should be part of e.g. a validation, statistical report, expression matrix, time series, ... and not a data type themselves

**Comment by joncison** [comment]
For now at least, I don't think we can action this one.  Closing for now.
