### ISSUE TITLE
Training material

### ISSUE THREAD

**Issue by peterjuv** [edamontology/edamontology#22]
Please add the following terms to EDAM Data Type in order to register ELIXIR eLearning Platform and similar platforms (e.g. Goblet):

    Training material 
        OER - Open Educational Resource
            MOOC - Massive open online course

**Comment by matuskalas** [comment]
Thank you @peterjuv , I'm sure that this may be in concern of multiple users.

I'd suggest adding 2 data concepts, as 1 is too few and 3 or 4 are too many ;-)

primary label: Training material
data concept
narrow(!) synonym: Open educational resource
narrow(!) synonym: OER

primary label: Online course
is_a Training material
narrow(!) synonym: MOOC
narrow(!) synonym: Massive open online course

**Comment by joncison** [comment]
@peterjuv, these will appear in EDAM_1.12 (this month):

Training material
http://edamontology.org/data_3669

Online course
http://edamontology.org/data_3670

(with synonyms as defined by @matuskalas)
