### ISSUE TITLE
New narrow synonyms

### ISSUE THREAD

**Issue by njall** [edamontology/edamontology#223]
From our work mapping [iAnn](http://iann.pro) fields to EDAM:

DNA methylation is a narrow synonym of Epigentics
Theoretical biology is a narrow synonym of Computational biology
Biotherapeutics is a narrow synonym Drug formulation and discovery
DNA Microarrays is a narrow synonym of Gene expression

**Comment by joncison** [comment]
Thanks, all this done in EDAM_1.16 or earlier
