### ISSUE TITLE
Remove old web pages folder from the distribution

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#224]
I would strongly advise to put the website in a separate repository of edamontology.org, and remove the web folder from the edamontology repo itself. Since @veitveit created a new version of these pages, and a separate readthedocs is available, we should just remove this, which will make the creation of web pages a whole lot lighter :)

**Comment by joncison** [comment]
+1  will you please do this?  also I shrunk down Veit's effort to 1 page because everything else is now on montologydocs.readthedocs.io/en/latest/
