### ISSUE TITLE
Add new term Expression profile clustering

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#225]
Until now, there is only _Gene expression profile clustering_ but this concept can be applied to many other data types.
Definition:     Perform cluster analysis of expression data to identify groups with similar expression profiles
Parent: Clustering

_Gene expression profile clustering_ will either become a child of this new term or we can skip it to have this concept applied more generally. Practically all omics data sets can have their profiles clustered, meaning that we either add many new terms of leave it with a general all-purpose one.

**Comment by joncison** [comment]
:+1:  done in EDAM_1.16

_Expression profile clustering_ (http://edamontology.org/operation_0313)  with appropriate narrowSynonyms

And given the same treatment to 
* _Gene expression profile comparison_ (http://edamontology.org/operation_0315)
* _Gene expression data analysis_ (http://edamontology.org/operation_2495)

We can I think close this issue, but would you pls. take a closer look at what other clean-ups / simplifications could be done along these lines ?  It might be there are some general concepts (that can be grouped together) and some other things that should be grouped under Gene, Protein, Metabolite ...  (please create a new issue with any actions)
