### ISSUE TITLE
Gene expression data formats can be generalized

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#226]
_Gene expression data_ is a subclass of _Data_. I would substitute it by _Expression data_ to include all the other data types that can be treated by similar operations for further processing such as statistical tests, clustering, functional analysis.

So either we keep it general or add similar terms _Protein expression data_, _Metabolite expression data_, ...

**Comment by joncison** [comment]
Yes - like this one

Done in EDAM_1.16, and with appropriate narrowSynonyms

More suggestions like this (which simplify EDAM) are warmly received :-)

**Comment by matuskalas** [comment]
Duplicate of slightly newer #237
