### ISSUE TITLE
New data types Clustered expression profiles

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#227]
Definition: Groupings of expression profiles according to a clustering algorithm.
Parent: _Gene expression data_

Preferably subclass of a parent _Expression data_
_Heatmap_ could be come subclass of this new term

**Comment by joncison** [comment]
In EDAM_1.16

_Clustered expression profiles_ (http://edamontology.org/data_3768) is_a  _Gene expression data_ (http://edamontology.org/data_2603)

(also with _Heat map_ as kid)

All good  ?

**Comment by veitveit** [comment]
I assume that the parent is _Expression data_ now. I would not put _Heat map_ as child as it does not necessarily include clustering.
