### ISSUE TITLE
Add Data: "Plain text"

### ISSUE THREAD

**Issue by ivanmicetic** [edamontology/edamontology#23]
"Plain text" exists as a format (http://edamontology.org/format_1964) but not as type of data. It is a common input data type on many forms.

**Comment by hmenager** [comment]
"plain text" itself is rather a format. maybe rather declare something for "query"?

**Comment by ivanmicetic** [comment]
I agree. Maybe "Plain text query" or "Free text search query"?

**Comment by joncison** [comment]
@ivanmicetic, this will be created in EDAM_1.12 (this month)

Text
http://edamontology.org/data_3671

(exact synonyms of "Free text" & "Plain text")
