### ISSUE TITLE
CorrelatedNetwork operations

### ISSUE THREAD

**Issue by llrs** [edamontology/edamontology#232]
I am currently using [WGCNA](https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/#cranInstall) which is a tool/package which I am unsure where it fits:
 - _Pathway or network analysis_: It creates a network, so it analyse and calculate some properties of the network
 - _Gene expression profile pathway mapping_: It doesn't map with current known pathways.
 - _Gene regulatory network analysis_: It is not about gene regulation
 - _Pathway or network prediction_: It doesn't predict, it just describe 
 - _Gene regulatory network prediction_: It is not about gene regulation prediction
 - _Protein interaction network prediction_: It doesn't predict protein interactions
 - _Gene expression correlation analysis_: It is based on gene expression correlation

Should such a tool be on both operations pathway or network analysis and gene expression correlation?

**Comment by joncison** [comment]
You could have just gone for _Pathway or network analysis_

BUT in EDAM_1.16 

_Weighted correlation network analysis_ (http://edamontology.org/operation_3766) is_a  _Pathway or network analysis_ (http://edamontology.org/operation_2497)

**Comment by llrs** [comment]
It was just to check if I understood correctly the way the ontologies work. 
But thanks for addressing this.
