### ISSUE TITLE
missing formats

### ISSUE THREAD

**Issue by germa** [edamontology/edamontology#234]
Hi,

there are still some formats left, which we still miss for ELIXIR-registration of all our de.NBI software and services:

ADF             Array Design Format                                                     http://www.ebi.ac.uk/arrayexpress/help/creating_an_adf.html#WhatIsADF

ARB             binary format used by the ARB software suite                            http://www.arb-home.de

EXP             Affymetrix EXP format                                                   http://media.affymetrix.com/support/developer/powertools/changelog/gcos-agcc/exp.html

consensusXML    OpenMS format for grouping features in one map or across several maps   http://ftp.mi.fu-berlin.de/pub/OpenMS/release1.9-documentation/html/classOpenMS_1_1ConsensusXMLFile.html

featureXML      OpenMS format for quantitation results (LC/MS features)                 http://ftp.mi.fu-berlin.de/pub/OpenMS/release1.9-documentation/html/classOpenMS_1_1FeatureXMLFile.html

idXML           OpenMS format for protein and peptide identification                    http://ftp.mi.fu-berlin.de/pub/OpenMS/release1.9-documentation/html/classOpenMS_1_1IdXMLFile.html

mzData          mass spectrometry data representation (still in use)                    http://www.psidev.info/mzdata-1_0_5-docs

TIDE TXT file   used by the tide proteomics search program                              http://cruxtoolkit.sourceforge.net/tide-search.html

Best regards,
Gerhard

**Comment by matuskalas** [comment]
Thanks for reporting @germa .

I'll try to fix as many of these this week as I'll manage. Thanks a lot for adding the links!

**Comment by joncison** [comment]
In EDAM 1.20 
* _ADF_ (http://edamontology.org/format_3830)
* _ARB_ (http://edamontology.org/format_3830) - setting this as a child of _Alignment format_ (http://edamontology.org/format_1921) - but not 100% sure this is right!
* for _EXP Affymetrix EXP format_ see _EXP_ (http://edamontology.org/format_1631) now with synonyms and link to docs
* _consensusXML_ (http://edamontology.org/format_3832) created under _Mass spectrometry data format_ (http://edamontology.org/format_3245) - but not 100% sure this is correct (pls. comment below if necessary)
* _featureXML_ (http://edamontology.org/format_3833) created under _Mass spectrometry data format_ (http://edamontology.org/format_3245) but not 100% sure this is correct
* for _idXML_ see http://edamontology.org/format_3764 now with additional link to docs
* _mzData_ created under _Mass spectrometry data format_ (http://edamontology.org/format_3245)  - also pointing the replacement _mzML_ (http://edamontology.org/format_3244) of this now deprecated format
* _TIDE TXT_ (http://edamontology.org/format_3834) created under _Mass spectrometry data format_ (http://edamontology.org/format_3245).  I assumed that this format is used by other tools than just TIDE and therefore warrants inclusion in EDAM.


apologies @germa for the big delays
