### ISSUE TITLE
Formats listed in SEQwiki

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#236]
Here follows a big list of formats that have been annotated on tools in SEQwiki

Many of these we have, but in many cases we need new synonyms.   Some are weird or refer to placeholder concepts e.g. "sequence".  Anyhow, this has to be a rich mine of formats for EDAM!

454
.ab1
.abd
.abi
abyss assemblies
aligned sequence files
aln
amos bank
arachne binary
artemis
.bam
bcl
bcl
.bin and .xml files from rundata directory
bioconductor
biojava
bioperl
bioprospector
bioscope
bismark
blast
blast output
bowtie
breakdancermax
bustard
bwa
(c)fast(a/q)
chado db
cif) and cluster coordinates (idx
cigar
cisgenome
clustalw
cmap
cn
cnv-seq
(compressed) fasta
compressed fasta
(compressed) fastq
compressed fastq
compressed/uncompressed
csfasta/csqual (abi solid)
csfasta/q
csqual
cufflinks
custom
customizable
custom motif format
delimited text
divet
eland
emboss
excel
experiment files
extended multi-fasta
fasta/fastq
fasta files for reference
fasta.gz
fasta/q
fasta+qual
fastqc
.fastq/.fq
fastq.gz
fcp
flat
fnaqual
fps
.fq.gz
galaxy
gatk
gbff
gct
gdc
gerald
goby
gzip
hmmcnv
hmmer
hsx
illumina bustard
illumina export files
integrative genomics viewer
intensity files (int.txt.gz
interleaved
int.txt.p.gz
jalview
jaspar
macs
mapreads
mapview
maq
megan
meme
metarep
mg-rast
mira3
most others
mothur
mrf
msa
multi-fasta
mummer
muscle
nexus
nib
output from blat
paired
paired interleaved
pas
phoenix 2
phylip
phymmbl
pos)
primer3
prosite
prq
qiime
qseq
rdp
sam/bam
samtools
scarf
seq
seqmap
sequence
sequence tag file (read count)
sga
shore consensus files
shortread
short read tag with count
sim4
single-end and paired end
single reads (.fasta .fasta.gz .fasta.bz2 .fastq .fastq.gz .fastq.bz2 .sff)
sms
snpeff
soap
solexa
solexa with probability
spch
special format for paired reads
specialized format
sqd
stamp
standard blast output
stockholm
tab-delimited
tablet
table with count data
tophat
trace archive
transfac
unaligned bam
velvet
xml traceinfo
xms

**Comment by veitveit** [comment]
Many of these format might be outdated or are already in.
