### ISSUE TITLE
Changing from gene expression terms to more general (omics data) expression

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#237]
The following terms could use a generalization/adaptation:

a) Operation _Gene expression data analysis_ would be better described by _Expression data analysis_. 
Synonyms: gene expression data analysis, protein expression data analysis, metabolite expression analysis, ... omics expression data analysis

All childs of _gene expression data analysis_ can be generalized.

b) _Simulated gene expression data generation_ can be generalized to _Simulated expression data generation_

c) _Functional genomics_ can be either substitute by _Functional omics_ or new terms _Functional proteomics_ become child of _Functional omics_ together with _Functional genomics_

d) _Microarray data rendering_ can be substituted by _Expression data rendering_. All its childs can be adapted then.

**Comment by matuskalas** [comment]
c) To me it seems that
- _Functional genomics_ is a slowly obsoleting synonym of _Gene expression_
- _Functional omics_ does not exist (according to Google search
- _Functional proteomics_ is some narrow, emerging topic with minimal publicity. I'd suggest either leaving out or including as a narrow synonym of _Proteomics_

**Comment by veitveit** [comment]
Point taken

**Comment by veitveit** [comment]
Some more details on moving to general _Expression_:

1. _Gene expression analysis_  to _Expression analysis_
Definition: Process (read and/or write)  expression data from experiments measuring molecules (e.g. omics data), including analysis of one or more expression profiles, typically to interpret them in functional terms.
Synonyms: Expression data analysis, Feature expression analysis
Narrow synonyms: RNA-seq analysis, Microarray data analysis, Gene expression data analysis, Protein expression analysis, Metabolite expression analysis

2. _Gene expression profile comparison_ to _Expression profile comparison_
Definition: Comparison of expression profiles.
Remove parent _Nucleic acid comparison_ (as this term compares different (!) nucleic acids e.g. for similarity)

3. _Gene expression correlation analysis_ to _Expression correlation analysis_
Synonyms: Co-expression analysis
Definition: Analyse the correlation patterns among features/molecules across across a variety of experiments, samples etc. 

4. _Gene expression profile clustering_ to _Expression profile clustering_
Definition: Perform cluster analysis of expression data to identify groups with similar expression profiles, for example by clustering.

5. _Gene expression profile pathway mapping_ to _Expression profile pathway mapping_
Definition: Map a expression profile to known biological pathways, for example, to identify or reconstruct a pathway.

6. This term seems to be very general and ambivalent and I suggest it to be removed: _Gene expression profiling_ 

7. Remove _Gene set testing_ and make it synonym of _Gene-set enrichment analysis_. The term might become more general but so far most of the enrichment analyses use genes as basis.

8. _Microarray data rendering_ to _Expression data rendering_
Definition: Visualise expression data.

9. All children of _Microarray data rendering_ can be adjusted by generalization of the definition.

10. _Gene expression data_ to _Expression data_
Definition: Image, hybridisation or some other data arising from a study of feature/molecule expression, typically profiling or quantification.
Add synonyms: Gene expression data, Protein expression data, Metabolite expression data

11. _Clustered gene expression profiles_ to _Clustered expression profiles_
Definition: Groupings of expression profiles according to a clustering algorithm.

12. _Heat map_
Definition: A graphical 2D tabular representation of expression data, typically derived from an omics experiment. A heat map is a table where rows and columns correspond to different features and contexts (for example, cells or samples) and the cell colour represents the level of expression of a gene that context.

13. Several other terms like _Gene expression profile_  and _Microarray metadata_ could be generalized.
Others not and should either be removed or moved into a "new" _Gene expression data_. Any opinions?

**Comment by joncison** [comment]
This is a fantastic contribution.

All done, but a couple of notes
* *RNA-Seq analysis* is a concept with kids, now under *Expression analysis*
* *Gene expression profiling* **replaced_by** *Expression analysis* (it's parent) but migrating the many synonyms etc.

As for 
_"13. Several other terms like Gene expression profile and Microarray metadata could be generalized. Others not and should either be removed or moved into a "new" Gene expression data. Any opinions?"_

I'd like very much to encourage you @veitveit to please take a second round of rigorous inspection, as you did, and create a new list of suggestions. 

For now I'll close this issue (but you can re-open when you paste a new list)
