### ISSUE TITLE
broken link at http://edamontology.org

### ISSUE THREAD

**Issue by hansioan** [edamontology/edamontology#238]
In the "Viewing" section when clicking the link with the name "EBI Ontology Look-up Service (OLS)" the link goes to:
http://edamontology.org/(http://www.ebi.ac.uk/ols/ontologies/edam

The intended url should be:
http://www.ebi.ac.uk/ols/ontologies/edam

There is an initial in the link address ("**http://edamontology.org/(**") that needs to be removed

**Comment by joncison** [comment]
thanks - fixed in GitHub

Matus pls update the web site ASAP

J:)
