### ISSUE TITLE
Validation errors / missing terms

### ISSUE THREAD

**Issue by lorenzr** [edamontology/edamontology#240]
Hi,
I was updating our entries and got some validating errors:

Invalid URI: http://edamontology.org/data_3723.
Invalid URI: http://edamontology.org/data_3722.
Invalid URI: http://edamontology.org/data_3721.
Invalid URI: http://edamontology.org/data_3720.
Invalid URI: http://edamontology.org/data_3719.
Invalid URI: http://edamontology.org/data_3718.

So, when I try to assign the data types, they are missing. Though when I look up the terms [here](http://webprotege.stanford.edu/#Edit:projectId=1c592f8c-b3ac-4797-adba-7a883c0e18aa), I can find them.
Where does this discrepancy come from? 
 
best regards,

Lorenz

**Comment by joncison** [comment]
sorry for very long delay in getting back Lorenz - anyhow, I think this issue is now solved (there was a lag between EDAM release and this being supported in bio.tools).  Please reopen the issue if there's still a problem
