### ISSUE TITLE
duplicate concept label "Differential gene expression analysis" in operation

### ISSUE THREAD

**Issue by bug1303** [edamontology/edamontology#241]
"Differential gene expression analysis" [http://edamontology.org/operation_3223] is subClassOf: "Differential gene expression analysis" [http://edamontology.org/operation_3742]

**Comment by joncison** [comment]
ooh, that's bad

"Differential gene expression analysis" [http://edamontology.org/operation_3223]  was erroneously added (duplicating 3742) and is now deprecated in edam_dev.owl

**Comment by matuskalas** [comment]
http://edamontology.org/operation_3742 is the deprecated copy. Added in 1.15, deprecated in 1.17.
