### ISSUE TITLE
|Differential gene expression analysis" name in parent and child

### ISSUE THREAD

**Issue by hansioan** [edamontology/edamontology#242]
The name "Differential gene expression analysis" is given to the term operation_3742 which has the child term operation_3223 with the same name of "Differential gene expression analysis". I think this is a bit confusing. 

Perhaps a solution is to replace the parent "Differential gene expression analysis" (operation_3742) with "Differential expression analysis" which can apply to other features apart from genes. The definition of this term can be similar to what it is now, but replace genes with features: 

"The analysis, using any of diverse techniques, to identify features that are differentially expressed under a given experimental setup."

**Comment by joncison** [comment]
this duplicates https://github.com/edamontology/edamontology/issues/241 (now fixed)
