### ISSUE TITLE
Some terms exist both as synonyms and independent concepts

### ISSUE THREAD

**Issue by bug1303** [edamontology/edamontology#244]
I was parsing EDAM_1.16.owl to compare existing concepts with our RNA ontology and found some terms occurring twice within the same sub-ontology (haven't checked across ontologies).
I was wondering which of these cases are intended / considered desirable, and which should be avoided.

"Nucleic acid sequence" (data_2977) hasNarrowSynonym "DNA sequence" and also subClass "DNA sequence" (data_3494).

"Isolation report" (data_3717) hasNarrowSynonym "Geographic location" and "Isolation source" and both also as subClass (data_3720 and data_3721)

"Gene expression analysis" (operation_2495) hasNarrowSynonym "RNA-seq analysis", which also exists as operation_3680

"Microarray experiment" (topic_3518) hasNarrowSynonym "ChIP-on-chip", which also exists as topic_3179

"Medical informatics" (topic_3063) hasBroadSynonym "Molecular medicine" and "Translational medicine", which also exists as topic_3388 and topic_3342 respectively.

GCG MSF (multiple sequence file) file format [format_1947] hasExactSynonym "MSF", which is also the Preferred Name of "Magellan storage file format" (format_3702)

**Comment by joncison** [comment]
most of these are bugs ... thanks!  ... will be squashed in next release  cc @hmenager for an addition to the CI to identify / report such cases

**Comment by matuskalas** [comment]
The reported cases will be fixed, and after https://github.com/edamontology/edamxpathvalidator/issues/3 is added, additional such cases need to be fixed, too.
