### ISSUE TITLE
Spectral library search

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#249]
Veit says  ... need to add a new EDAM term "spectral library search" at some point
as it is not exactly a synonym for "peptide identification"

**Comment by veitveit** [comment]
Parent: _Peptide identification_
Definition: Match experimentally measured mass spectrum to a spectrum in a spectral library or database.

**Comment by veitveit** [comment]
Also issue #118 which somehow did not make it into EDAM. Any of both definitions sounds fine

**Comment by joncison** [comment]
OK ... so in EDAM_dev.owl

"Spectral library search" (http://edamontology.org/operation_3801)
