### ISSUE TITLE
support HTTPS URL to EDAM concepts

### ISSUE THREAD

**Issue by mr-c** [edamontology/edamontology#257]
Expected behavior:

[http**s**://edamontology.org/format_2572](https://edamontology.org/format_2572) gives me the same content as http://edamontology.org/format_2572

Current behavior: 
(after accepting an invalid SSL certificate)
<h1>Not Found</h1>
<p>The requested URL /format_2572 was not found on this server.</p>
<hr>
<address>Apache/2.2.3 (CentOS) DAV/2 PHP/5.1.6 mod_ssl/2.2.3 OpenSSL/0.9.8e-fips-rhel5 Server at edamontology.org Port 443</address>

**Comment by joncison** [comment]
@matuskalas - this is one for you mate

**Comment by joncison** [comment]
@matuskalas - giving this a nudge !

**Comment by albangaignard** [comment]
The used certificate for SSL encryption seems to be very old. I attached a screenshot. 
![capture d ecran 2017-10-18 a 17 33 36](https://user-images.githubusercontent.com/10667536/31727739-a90e202e-b42a-11e7-8fac-e25d707ae08a.png)

**Comment by matuskalas** [comment]
Fixed, but needs some polishing.

**Comment by joncison** [comment]
@matuskalas - please close this (or say what's left to do).

**Comment by matuskalas** [comment]
Still needs a more stable setup, which is on the way

**Comment by joncison** [comment]
nudge-nudge @matuskalas

**Comment by joncison** [comment]
This fixed now, thanks @matuskalas

**Comment by mr-c** [comment]
Hurray!
