### ISSUE TITLE
Remove wrong newlines from definitions, synonyms, comments

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#266]

**Comment by matuskalas** [comment]
... and revise all newlines. The ones that are useful to keep should in addition have a **whitespace in the end** (to look better in apps that remove newlines w/o replacement, _e.g._ TSV export in Excel)

**Comment by joncison** [comment]
Nice if the CI can check for this (and all such validations) cc @hmenager

**Comment by matuskalas** [comment]
It'd be especially useful if CI checked that there are no tabs (\t) inside any XML elements and attributes. Is that difficult or easy with XPath? Should I create a dedicated issue there, @hmenager?

(I also reckon that trailing dots (.) in definitions and comments are checked by CI, or do I remember wrongly? In any case, not crucial but perhaps a nice-to-have)

**Comment by matuskalas** [comment]
Fixed by 68d565f

**Comment by matuskalas** [comment]
For info, leftover newlines are in: http://edamontology.org/data_0906, http://edamontology.org/format_3687, http://edamontology.org/operation_0338, and http://edamontology.org/operation_3192.
