### ISSUE TITLE
Fix wrong created_in & obsolete_since, remove duplicates

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#267]

**Comment by joncison** [comment]
@matuskalas : can you please define what we need to do to clean this up?  I assume some systematic fix is possible ...

**Comment by matuskalas** [comment]
This is easy to fix and I'll do it.

**Comment by matuskalas** [comment]
Fixed created_in errors in cca354d

**Comment by matuskalas** [comment]
Fixed error in deprecated concepts in 4d2ce76

**Comment by matuskalas** [comment]
Note also #317
