### ISSUE TITLE
Add disease category identifer

### ISSUE THREAD

**Issue by sduvaud** [edamontology/edamontology#27]

**Comment by jongithub** [comment]
We have "Disease ID" (http://edamontology.org/data_1150).  Is this not what you're after?

**Comment by joncison** [comment]
@sduvaud, in EDAM_1.12 (out this month), we'll have:

"Disease identifer" (http://edamontology.org/data_3667)

with children:
Disease name
http://edamontology.org/data_3668

Disease ID
http://edamontology.org/data_1150

pls. reopen the issue if you need more
