### ISSUE TITLE
Add .pptx format

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#271]
_Parent:_ XML, Image format (?)
_Definition:_ Microsoft Powerpoint format
_Description:_ https://msdn.microsoft.com/en-us/library/dd926741(v=office.12).aspx

**Comment by mr-c** [comment]
FYI: https://www.iana.org/assignments/media-types/application/vnd.ms-powerpoint

**Comment by mr-c** [comment]
For "pptx" the IANA Media type is (aka "mimetype") is [`vnd.openxmlformats-officedocument.presentationml.presentation`](https://www.iana.org/assignments/media-types/application/vnd.openxmlformats-officedocument.presentationml.presentation)

**Comment by matuskalas** [comment]
Thx @joncison for adding.

The media type will need fixing (https://www.iana.org/assignments/media-types/application/vnd.openxmlformats-officedocument.presentationml.presentation).

Another question is **whether we should model** formats like this
* Are there any bioinformatics tools that consume or produce data in such format?
* If yes, then add other related formats.

**Comment by joncison** [comment]
I fixed the media type. I'm not sure there are (m)any tools that use pptx directly, but it's so prevalent I think it's OK to use it (this an exception to the general scope rule). We have docx, probably others.  So closing for now (if there's more to add, please create a new issue for it).
