### ISSUE TITLE
Improve license info on GitHub

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#273]
From BOSC 2017 review by @peterjc: "From the GitHub repository alone, it is not obvious how EDAM is licensed. Please add this to the README and/or as a top level LICENSE file (using .md etc as you prefer)."

**Comment by peterjc** [comment]
Apologies, I tried to log GitHub issues directly for relevant points in my BOSC abstract reviews but missed this one.

**Comment by matuskalas** [comment]
Thanks a lot @peterjc for spotting this. I'll fix it as soon as I get to it

**Comment by matuskalas** [comment]
Now added in both a nicely readable [LICENSE.md](https://github.com/edamontology/edamontology/LICENSE.md) and in plain-text [LICENSE](https://github.com/edamontology/edamontology/LICENSE) to be recognised by GitHub.
