### ISSUE TITLE
Proposed operation refactorings

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#277]
Following the browsing of EDAM operations, I have a few suggestions I'd like to share. CC @joncison 
* Text annotation http://edamontology.org/operation_3778 is a child of both Analysis and Annotation, which seems weird because other annotations are not children of Analysis. I would have it as a child of Annotation only, and then consider Annotation to be a child of Analysis if deemed relevant
* The distinction between Assembly and Sequence Assembly seems a bit too theoritical to me. AFAIK when talking about assembly it's always sequence assembly, isn't it?
* Plotting should be a child of Visualisation, not directly of operation
* Query and retrieval (http://edamontology.org/operation_0224) should be in data handling IMO

**Comment by joncison** [comment]
all done in 1.18 *except* "Assembly" which stays for now (I'm not 100% convinced that it won't be needed, e.g. "Image assembly" or even "Protein structure assembly" (for some ab initio methods) and maybe others.

**Comment by matuskalas** [comment]
* Text annotation http://edamontology.org/operation_3778 was created as a child of both Analysis and Annotation intentionally, because Text annotation typically includes (semi-)automated analysis of the text (e.g. finding named entities)
 * Assembly other than Sequence assembly: Perhaps only theoretical. Personally, I haven't heard it being used in another context in bioinformatics.

**Comment by joncison** [comment]
@matuskalas : what do we need to do to close this issue ?

**Comment by joncison** [comment]
For "(semi-)automated analysis of the text (e.g. finding named entities)" we have _Text mining_ (http://edamontology.org/operation_0306) so I think _Text annotation_ (http://edamontology.org/operation_3778) can stay simply as a child of _Analysis_ (http://edamontology.org/operation_2945).

_Assembly_ is now deprecated (but made synonym of _Sequence assembly_)
