### ISSUE TITLE
problem with the management of deprecated terms

### ISSUE THREAD

**Issue by EricDeveaud** [edamontology/edamontology#28]
It looks like there is a problem in the ontology due to the deprecation of obsolete terms.

eg if we look at topic_0100

topic_0100 is deprecated and has us consider topic_0747

it turns that topic_0747 is deprecated to and has us consider topic_0160 and topic_0640

OK let's check for topic_0160 and topic_0640
topic_0160 appears to be also deprecated and have consider topic_0080
same apply for topic_0640 that is replacedBy topic_0080

Fortunately, topic_0080 appears to be valid

so we can represent the path from topic_0100 to topic_0080 this way:

topic_0100 -> consider topic_0747 -> consider topic_0640 -> replacedBy topic_0080

So, in short, topic_0100 should have consider or replacedBy set to topic_0080 instead of some also obsolete topic.

other examples:
topic_0748 -> consider topic_0639 -> replacedBy topic_0080
topic_0179 -> consider topic_0698 -> replacedBy topic_2814
operation_2448 -> consider operation_2446 -> consider operation_2403

furthermore the intermediate consider topic or operation appears as "father" of some terms.

for example, topic_3510 and topic_3511 appears to be a subClassOff topic_0160
nd as we saw above, topic_0160 is to consider topic_0080

I would suggest that when a term is marked as "deprecated" and have either a consider or a "replacedBy" that the whole ontology must be updated to avoid keeping deprecated "replacedBy" or "consider" terms. 

Best regards

Eric

**Comment by jongithub** [comment]
Thanks - we're aware of this issue and it needs fixing.  It's also a feature that the long-desired validator software should check for upon each release.

**Comment by joncison** [comment]
This all fixed in EDAM_1.13 (pending release)

Validation is in the pipeline !
