### ISSUE TITLE
More proposed Operation refactorings

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#280]
1. Deprecate *Protein sequence comparison* (http://edamontology.org/operation_2509) and *Nucleic acid sequence comparison* (http://edamontology.org/operation_2508) which are only distinct by the type of input sequence.  Their kids would still be findable via *Sequence comparison* (http://edamontology.org/operation_2451), *Nucleic acid comparison* (http://edamontology.org/operation_2998) and *Protein comparison* (http://edamontology.org/operation_2509)

2. Deprecate *Codon usage table processing* (http://edamontology.org/operation_2433); I don't think it's needed (two kids only)

3. Deprecate *Nucleic acid folding prediction (alignment-based)* (	
http://edamontology.org/operation_3471)  : it's distinct by type of input data yet it lacks the siblings that would make this distinction worthwhile

can I get some inputs @matuskalas  ?

**Comment by matuskalas** [comment]
👍
