### ISSUE TITLE
deprecated without consider nor replacedBy

### ISSUE THREAD

**Issue by EricDeveaud** [edamontology/edamontology#29]
operation_2238 and topic_3073 are tagged as deprecated by does not have "consider" nor "replacedBy" fields.

topic_3073 is  also tagged obsolete

either operation_2238 should hold a "consider" or "replacedBy" field or it should be tagged as "obsolete" 

best regards

Eric

**Comment by hmenager** [comment]
For future reference, the detection of such problems can easily be automated with xpath (or SPARQL I suspect). For instance, to detect deprecated terms annotated with a "consider" refering itself another deprecated term.

//owl:Class[owl:deprecated='true' and oboInOwl:consider[@rdf:resource=//owl:Class[owl:deprecated='true']/@rdf:about]]/@rdf:about

**Comment by joncison** [comment]
These bugs now fixed. 

All deprecated concepts now have "consider" or "replacedBy"

Hopefully we'll have validation soon (hint-hint @hmenager  ... :)
