### ISSUE TITLE
Format request SDF

### ISSUE THREAD

**Issue by bietzzbh** [edamontology/edamontology#291]
We would like to use SDF as input and output formats for several bio.tools services.

SDF (Structure-Data format) is a commonly applied chemical file format for the representation of molecular structures. 

For detailed information, please see:
http://infochim.u-strasbg.fr/recherche/Download/Fragmentor/MDL_SDF.pdf

**Comment by veitveit** [comment]
#164

**Comment by joncison** [comment]
*SDF* (http://edamontology.org/format_3814) was put in EDAM 1.20,
