### ISSUE TITLE
"hasAlternativeId" that points to non existing term

### ISSUE THREAD

**Issue by EricDeveaud** [edamontology/edamontology#30]
topic_0602 has field:
"hasAlternativeId" that point to topic_3076

but topic_3076 does not appears in ontology.

same for 
topic_0203 -> non existing topic_0197
topic_2814 -> non existing topic_3040

Eric

**Comment by jongithub** [comment]
The intention with hasAlternativeId is that it simply defines another ID by which the concept can be referred.  It's a legacy from past clean-ups.  Sadly the alternativeIds do not resolve :(  That should be fixed somehow ...

**Comment by joncison** [comment]
Closing this issue ... the hasAlternativeId remain.  And one day we resolve them (if that ever becomes necessary) ... but it's (very) legacy so I doubt it.
