### ISSUE TITLE
Changes to subterms of expression data rendering

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#300]
_dendrograph plotting_  and _Expression data-tree map rendering_ look very much the same as _Expression data tree or dendrogram rendering_ and should be deleted. Or is there a special meaning to dendrograph? 

New definition of _Expression data tree or dendrogram rendering_: Visualise clustered expression data using a tree diagram.

_Heat map generation_
New definition: The heat map usually uses a coloring scheme to represent expression values. They can show how quantitative measurements were influenced by experimental conditions. Generate a heat map of gene expression from e.g. microarray data.
Comment: The heat map usually uses a coloring scheme to represent expression values. They can show how quantitative measurements were influenced by experimental conditions.
hasDefinition: Generate a heat map of expression data from e.g. microarray data.

_Proximity map plotting_
Synonyms: Distance map rendering, proximity map rendering, distance matrix rendering, distance matrix plotting, correlation matrix plotting, correlation matrix rendering
Definition: Generate a plot of distances (distance or correlation matrix) between expression values.

**Comment by joncison** [comment]
All above done.  However _Dendrogram visualisation_ (http://edamontology.org/operation_2938, https://en.wikipedia.org/wiki/Dendrogram) and _Treemap visualisation_ (http://edamontology.org/operation_2942, https://en.wikipedia.org/wiki/Treemapping) not merged - they're different concepts I think.
