### ISSUE TITLE
Deprecation of terms under "Pathway or network analysis"

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#307]
Consider:

![image](https://user-images.githubusercontent.com/1506863/28536181-c6ee7d84-709e-11e7-8964-211c54054787.png)

shall we deprecate "Gene regulatory network prediction", "Protein interaction network prediction" and "Protein interaction network visualisation", all of which are conflations of their parents and siblings-of-parent concepts ?

cc @veitveit @matuskalas @hmenager

**Comment by joncison** [comment]
PS.  my vote is yes.  We need to be brutal if EDAM is to become simpler and thus more useful (at least, for the primary use case of "finding stuff"

**Comment by veitveit** [comment]
+1

**Comment by joncison** [comment]
OK, so I will deprecate in next release unless @hmenager or @matuskalas complain ... quickly guys :)
