### ISSUE TITLE
Deprecated EDAM terms with no replacements

### ISSUE THREAD

**Issue by hansioan** [edamontology/edamontology#317]
The following EDAM terms are deprecated, but do not have any values for properties such as "consider" or "replacedBy". The terms are:

Sequence mask character :: http://edamontology.org/data_0851
Sequence alignment parameter :: http://edamontology.org/data_0864
EMBOSS sequence type :: http://edamontology.org/data_1110
BLAST sequence alignment type :: http://edamontology.org/data_1121
Score end gaps control :: http://edamontology.org/data_1395
Aligned sequence order :: http://edamontology.org/data_1396
Vienna RNA parameters :: http://edamontology.org/data_1591
Vienna RNA structure constraints :: http://edamontology.org/data_1592
Vienna RNA concentration data :: http://edamontology.org/data_1593
Number of iterations :: http://edamontology.org/data_1693
Number of output entities :: http://edamontology.org/data_1694
Hit sort order :: http://edamontology.org/data_1695
Vienna RNA structural data :: http://edamontology.org/data_2022
Sequence mask parameter :: http://edamontology.org/data_2023
Search parameter :: http://edamontology.org/data_2079
Mutation type :: http://edamontology.org/data_2132
Results sort order :: http://edamontology.org/data_2134
Toggle :: http://edamontology.org/data_2135
Sequence offset :: http://edamontology.org/data_2145
Threshold :: http://edamontology.org/data_2146
Color :: http://edamontology.org/data_2151
Rendering parameter :: http://edamontology.org/data_2152
Date :: http://edamontology.org/data_2156
Cardinality :: http://edamontology.org/data_2176
Parameter :: http://edamontology.org/data_2527
Geotemporal metadata :: http://edamontology.org/data_3105
Strain data format :: http://edamontology.org/format_2210
Demonstration :: http://edamontology.org/operation_2246

**Comment by joncison** [comment]
All now have "consider" defined but in most cases this is pretty meaningless (i.e. top-level term, usually Data)
