### ISSUE TITLE
Tidy up concrete operations from the top level

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#318]
_E.g._ 'Anonymisation' and 'Deposition' belong to 'Data handling'.

'Rarefaction' needs proper synonyms and a proper placement in the hierarchy, too.

'Service management' needs a reasonable name, a reasonable meaning, and reasonable "sub-concepts". _E.g._ 'Tool handling'?  (_N.B._ that this is of course not bioinfo-specific. Do we really need such concepts anyway?)

**Comment by matuskalas** [comment]
In addition, 'Rarefaction' is completely wrong (see https://en.wikipedia.org/wiki/Rarefaction) and needs a corrected primary label.

**Comment by joncison** [comment]
Will take a look for the next release - are there any other specific fixes you have in mind?  Please paste them here ...

**Comment by joncison** [comment]
I've fixed this, so far as the above comments are actionable.  Please be more specific if you want other changes.
