### ISSUE TITLE
Metagenome annotation

### ISSUE THREAD

**Issue by iaraknes** [edamontology/edamontology#32]
Add metagenome annotation

**Comment by matuskalas** [comment]
I'm not sure Metagenome annotation should be modelled, but if Genome annotation is there then maybe. But which other "annotation"-s? Or just Sequence annotation??

**Comment by joncison** [comment]
@iaraknes, assuming that we're referring to the operation here, and not some metagenomics report, then I tend to agree with @matuskalas.  So I've added "metagenome annotation" as a "narrow synonym" on "Genome annotation" (http://edamontology.org/operation_0362).

But please do get back if you disagree.
