### ISSUE TITLE
BioPortal link doesn't work for topic

### ISSUE THREAD

**Issue by hansioan** [edamontology/edamontology#325]
The topic for which the BioPortal link doesn't work is:
http://edamontology.org/topic_0108

**Comment by matuskalas** [comment]
Weird enough.
Perhaps BioPortal automatically censors disputable terms like 'Protein expression' :-) [1]
[1] https://en.wikipedia.org/wiki/Protein_expression

**Comment by joncison** [comment]
I suspect a problem with BioPortal.  It's high time the URLs resolved to OLS (it isn't perfect yet, but is faster and more reliable).

**Comment by hansioan** [comment]
If I can put my 2 cents in, I agree that BioPortal is slow, on the other hand OLS is missing the entire deprecated tree, which for me is essential to curation; additionally it misses properties like different synonyms types. I do agree that it is faster and looks nicer.

**Comment by joncison** [comment]
The key issue is, which is best for the typical user?  I think OLS takes it.  Likely I'd still use OLS, BioPortal, emacs (!), Protege and lately RAINBio browser ...

**Comment by hansioan** [comment]
I think the best online one is:
http://people.binf.ku.dk/vzn529/eta/
but I might be a bit bias and subjective about this :)
It is very good at searching though :)

**Comment by joncison** [comment]
:) yes !

**Comment by albangaignard** [comment]
Very nice demo !!

Would it make sense to provide a JSON-LD version of the annotations ? so that they can be consumed by both nosql and RDF stores ?

**Comment by joncison** [comment]
sure, why not?  but I think we should take that in a separate thread (pls. create an issue)

**Comment by joncison** [comment]
Issue in OP has gone away (BioPortal was playing up)

**Comment by matuskalas** [comment]
Key performance indicator: http://bioportal.bioontology.org/visits

Anyhow, I will implement an option that will let users choose between different browsers, so that everyone's happy (separate issue).

**Comment by matuskalas** [comment]
Marked "invalid", as it got fixed at the NCBO side. (We need labels for closed issues for our own reporting & overview)
