### ISSUE TITLE
Links for PSI MI TAB (MITAB) format

### ISSUE THREAD

**Issue by uludag** [edamontology/edamontology#330]
Current MITAB format is linked to the following readme file

- http://ftp.ebi.ac.uk/pub/databases/intact/current/psimitab/README

This readme file describes the format only briefly and provides references for the full description.

After an internet search I found the following pages that describe the MITAB format with more details

- https://wiki.thebiogrid.org/doku.php/psi_mitab_file
- http://psicquic.github.io/MITAB27Format.html
- https://wiki.reactome.org/index.php/PSI-MITAB_interactions

--mahmut

**Comment by matuskalas** [comment]
Awesome, thanks @uludag
