### ISSUE TITLE
errors in some deprecation-related annotation

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#331]
reported initially by @hansioan and pj:
"PJ said that in the owl file of edam 1.19 at line 50533 there is an error. The issue is that there is a definition in that line instead of consider."
Testing further by adding new controls in https://github.com/edamontology/edamxpathvalidator, there are a few problems related to deprecated terms:

```
non-obsolete with consider - 'Drug report' (http://edamontology.org/data_1696)
non-obsolete with consider - 'Laboratory information management' (http://edamontology.org/topic_0607)
malformed consider - 'Structural biology' (http://edamontology.org/topic_1317)
```

**Comment by hansioan** [comment]
@hmenager please let me know when you fix these issues and update edam so I can integrate the updated version into bio.tools
