### ISSUE TITLE
Revise EDAM release process to ensure sync with bio.tools

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#338]
Suggestion from talking with @hansioan is to not formally release EDAM **until** it's updated in bio.tools, to avoid problems like https://github.com/bio-tools/biotoolsRegistry/issues/296

The task is to update the release docs (http://edamontologydocs.readthedocs.io/en/latest/editors_guide.html) and then stick to this.

cc @matuskalas @hmenager

**Comment by matuskalas** [comment]
@hansioan What do you mean by "formally release"?

@joncison Why would you want to update bio.tools **before** new EDAM version is release? I would understand if you want it **right after**

**Comment by joncison** [comment]
@matuskalas - that's essentially what I mean: @hansioan updates bio.tools **before** we "formally release" (_i.e._ announce) a new EDAM release - this way, people don't go to bio.tools with the wrong expectations.

the good news is that Hans has automated the process, although he still needs to run the scripts manually.

**Comment by matuskalas** [comment]
Ok @joncison , then let's from now on do all the releasing circus up to the point of the GitHub/Zenodo release, then notify @hansioan to run his scripts & give back the green light, and then announce.

**Comment by matuskalas** [comment]
@hansioan, could you please update bio.tools as soon as you're available with the new EDAM version 1.20? 1000000 thanks!

**Comment by hansioan** [comment]
Done.

**Comment by hansioan** [comment]
@matuskalas also done with deprecation fixes in bio.tools

**Comment by joncison** [comment]
I updated the release process (http://edamontologydocs.readthedocs.io/en/latest/editors_guide.html) with note to mail Hans and confirm bio.tools is happy *before* announcing.

**Comment by joncison** [comment]
This issue was moved to edamontology/edamontologyDocs#13
