### ISSUE TITLE
Add NLP generic format so other NLP formats can inherit from.

### ISSUE THREAD

**Issue by redmitry** [edamontology/edamontology#339]
<owl:Class rdf:about="http://edamontology.org/format_3840">
        <rdfs:label>NLP format</rdfs:label>
        <rdfs:subClassOf rdf:resource="http://edamontology.org/format_2350"/>
        <created_in>1.21</created_in>
        <rdfs:comment>Data format used in Natural Language Processing.</rdfs:comment>
    </owl:Class>

**Comment by joncison** [comment]
thanks!  done in EDAM_21 (out around end of this month)

**Comment by redmitry** [comment]
Proposed NLP nodes:
--------------------------------------------------
:format_3842 rdf:type owl:Class ;
    rdfs:subClassOf :format_3841 ;
    :created_in "1.21" ;
    rdfs:comment "Any NLP format used for annotated textual documents" ;
    rdfs:label "NLP Annotation format";

:format_3843 rdf:type owl:Class ;
    rdfs:subClassOf :format_3842 ;
    :created_in "1.21" ;
    rdfs:comment "NLP format used by a specific type of corpus (collection of texts)" ;
    rdfs:label "NLP Corpus format";

**Comment by joncison** [comment]
Added both of  the above, closing for now.

But note - these concepts are *types* of formats, what we really need are details for specific formats that are children of these classes.  I created a dedicated issue template for formats which might help.

**Comment by redmitry** [comment]
> what we really need are details for specific formats that are children of these classes.
Yeah! I understand this, but I prefer to eat the elephant in small pieces...
Now I think to adopt the formats from the [openminted ontology](https://github.com/openminted/omtd-share-ontology) providing "seeAlso" to the origin.

Thank you Jon,

D.
