### ISSUE TITLE
'file_extension' property with attributes of 'ontology_used' (?)

### ISSUE THREAD

**Issue by EvaIbarra** [edamontology/edamontology#341]
Hello,
I've seen in the latest version (1.20) that the property <http://edamontology.org/file_extension> has some attributes corresponding to <http://edamontology.org/ontology_used> (e.g. rdfs:label, definition), while this one (ontology_used) remains empty (e.g. no label). 
My feeling is that this two properties have been, somehow, mixed up.
Am I right?
Thanks!

**Comment by matuskalas** [comment]
Hi @EvaIbarra!
Thank you for your report.
Have you seen any concrete cases in EDAM where these properties seem to be mixed up? Are you able to find them again and let us know?
Many thanks again!

**Comment by EvaIbarra** [comment]
Hi, thanks for your reply!
What I've seen is this in 'file_extension':
```
    <!-- http://edamontology.org/file_extension -->

    <owl:AnnotationProperty rdf:about="http://edamontology.org/file_extension">
        <rdfs:label>Ontology used</rdfs:label>
        <rdfs:label>File extension</rdfs:label>
        <rdfs:comment>N.B.: File extensions that are not correspondigly defined at http://filext.com are recorded in EDAM only if not in conflict with http://filext.com, and/or unique and usual within life-science computing.</rdfs:comment>
        <oboInOwl:hasDefinition>&apos;File extension&apos; concept property (&apos;file_extension&apos; metadata tag) lists examples of usual file extensions of formats.</oboInOwl:hasDefinition>
        <rdfs:comment>Separated by bar (&apos;|&apos;), without a dot (&apos;.&apos;) prefix, preferrably not all capital characters.</rdfs:comment>
        <oboInOwl:hasDefinition>&apos;Ontology used&apos; concept property (&apos;ontology_used&apos; metadata tag) of format concepts links to a domain ontology that is used inside the given data format, or contains a note about ontology use within the format.</oboInOwl:hasDefinition>
        <oboInOwl:inSubset>concept_properties</oboInOwl:inSubset>
        <oboOther:is_metadata_tag>true</oboOther:is_metadata_tag>
    </owl:AnnotationProperty>
```
So, you see that you have **two labels and two definitions**. And then for 'ontology_used' you don't have any:
```    
    <!-- http://edamontology.org/ontology_used -->

    <owl:AnnotationProperty rdf:about="http://edamontology.org/ontology_used"/>
```
So I think that the 'file_extension' property got the attributes corresponding to 'ontology_used'.

**Comment by joncison** [comment]
Thanks @EvaIbarra! 

This fixed in EDAM_21 (out near end of this month or early next)
