### ISSUE TITLE
New operation: Multilocus Sequence Typing

### ISSUE THREAD

**Issue by dfornika** [edamontology/edamontology#342]
Would it be appropriate to add a new operation term for [multilocus sequence typing (MLST)](https://en.wikipedia.org/wiki/Multilocus_sequence_typing) to EDAM?

I'd suggest that it could be a subclass of [Genotyping (operation_3196)](https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Foperation_3196)

**Comment by dfornika** [comment]
Related term from TypOn:

http://purl.phyloviz.net/ontology/typon#MLST

**Comment by dfornika** [comment]
Related term from OBI:

http://purl.obolibrary.org/obo/OBI_0000435

**Comment by dfornika** [comment]
Is there any way that I (or other interested community members) can view the details of the term before it's released? I'm hoping that this term can be as consistent & compatible as possible with TypON and OBI.

**Comment by joncison** [comment]
sure ... you can download the dev version of EDAM (https://github.com/edamontology/edamontology/blob/master/EDAM_dev.owl) and look at it in e.g. Protege or a text editor.  

We'll also explore something more convenient, e.g. CI such that the dev. version gets uploaded to a public browser somewhere on each commit cc @hmenager @matuskalas
