### ISSUE TITLE
Proposed deprecations in Data branch

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#343]
- [ ] Secondary structure alignment (protein) http://edamontology.org/data_0878
- [ ] Secondary structure alignment (RNA) http://edamontology.org/data_0881
- [ ] Sequence alignment (pair) http://edamontology.org/data_1381
- [x] Atomic x coordinate http://edamontology.org/data_1744
- [x] Atomic y coordinate http://edamontology.org/data_1745
- [x] Atomic z coordinate http://edamontology.org/data_1746
- [x] Chemical structure sketch http://edamontology.org/data_3490

@matuskalas could you pls. tick any that you agree should go ?  Thanks !

**Comment by joncison** [comment]
@matuskalas  - so I self-ticked the ones I was sure about, and close this for now.

**Comment by matuskalas** [comment]
Not sure, I'd need some usage scenarios to be able to judge which should be in and which not. I just remember that we added the x, y, z coordinates for WHAT-IF and other 3D-structure resources. There the broad conceptual question would be, how much we should/can model detailed data attributes.

**Comment by jlgelpi** [comment]
Keeping separated entries for x, y , and z coordinates would make no sense. 
"XYZ Coordinates" or "Cartisian coordinates" as a combination is a better option. In fact XYZ as a FORMAT is accepted by most 3D-structure management software
