### ISSUE TITLE
[RainBio User] Change proposition for http://edamontology.org/data_2976 in EDAM 1.18

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#344]
[//]: # (You can add comment regarding your issue hereafter)
Change label to Amino acid sequence (like Nucleic acid sequence) and use Protein sequence as synonym

[//]: # (End of issue comments)
Hereafter are the initial version et proposed modification of attributes of the given term

| key | value |
| --- | --- |
| Attr  | **definition** |
| Old | One or more protein sequences, possibly with associated annotation. |
| New | One or more amino acid sequences, possibly with associated annotation. |
|  |  |
| Attr  | **label** |
| Old | Protein sequence |
| New | Amino acid sequence |
|  |  |
| Attr  | **exactSynonyms** |
| Old | Protein sequences| |
| New | Protein sequence|Protein sequences|Peptide sequence|Peptide sequences |
|  |  |

**Comment by joncison** [comment]
I added **exactSynonym** of *Amino acid sequence* and *Amino acid sequences* to relevant concepts, but didn't change the label.  Although obviously more biologically correct, I'm not sure the proposed change reflects the vernacular used by tool users.
