### ISSUE TITLE
Operation request: Spectrum calculation

### ISSUE THREAD

**Issue by vatsi16** [edamontology/edamontology#347]
For the annotation of https://www.ncbi.nlm.nih.gov/pubmed/15166022 .

I think it fits under "Spectral analysis" - http://edamontology.org/operation_3214 , under "Protein sequence analysis" - http://edamontology.org/operation_2479 and perhaps under "Calculation" - http://edamontology.org/operation_3438 .

**Comment by joncison** [comment]
Thanks.  I made it a child of *Protein property calculation* (http://edamontology.org/operation_0250) and *Spectral analysis* (http://edamontology.org/operation_3214).
