### ISSUE TITLE
Format request: Waters RAW 

### ISSUE THREAD

**Issue by vatsi16** [edamontology/edamontology#349]
I have found this format as input in more than 9 tools. There is already "Thermo RAW" term so i thought its good to add this one too.

**Parent:** "Mass spectrometry data format" - http://edamontology.org/format_3245 .
**Definition:**  Proprietary file format for mass spectrometry data from Waters. Proprietary format for which documentation is not available.

**Comment by joncison** [comment]
Thanks!  Will appear in next release.

**Comment by joncison** [comment]
PS.  I assumed it's a binary format - do you know if that's right?
