### ISSUE TITLE
Add new terms for BioExcel / structural bioinformatics

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#353]
The list of terms that should be added for BioExcel is here:
https://docs.google.com/spreadsheets/d/10BESl512gEHuPbWrTtIWPuVHKu6rmp5aNo2z-kRqglc/edit?usp=sharing
Thanks to @adamhospital and his team for preparing that.

**Comment by matuskalas** [comment]
Looks great, thanks for the work!

@adamhospital et al., could you please provide us (ideally) with links to definitions of those concepts (e.g. wikipedia), or at least supply some 1- or 2-sentence definitions yourselves?
Million thanks!

**Comment by joncison** [comment]
I think the defs. are all in the spreadsheet.

Let's get this in the next release (this month).

**Comment by matuskalas** [comment]
Sorry, I was too fast and didn't look at the next worksheet.

Many thanks @adamhospital et al., looks great!

This month is impossible as most of the EDAM team is in GCC/BOSC, but July will work very well.

**Comment by matuskalas** [comment]
@adamhospital, could you please provide us with a list of contributors who contributed to the spreadsheet (full names, including non-English characters where applicable) ? Thanks!

**Comment by hmenager** [comment]
@adamhospital I have a question regarding simulation data: does simulation data always _couple_ topology and trajectory data, as in a has_a relationship, or is simulation data a generalisation of the later two, like in a super/subclass relationship? (pls tell me if the ontology jargon I use needs more explanation).

**Comment by hmenager** [comment]
I added the first term for this: Molecular simulation data. If you want to pick up on this @matuskalas you are more than welcome

**Comment by jlgelpi** [comment]
Simulation data should have (has_a) the two components: the topology that is the description of the system, and eventually simulation settings and trajectory that contains the atom coordinates (and other components) that change over time. Some tools may consume or produce with just one of them (mostly the topology since it is generated by setup tools), but simulation and analysis tools always consume both.

**Comment by joncison** [comment]
ps. just re-open if you think more is needed
