### ISSUE TITLE
"Graph data", "Plot" and "Image"

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#359]
*Graph data* is required by DSEO (https://docs.google.com/spreadsheets/d/1ix1eKplAX9KHbBsA6uU7G95_7lD5Q9jGfEL_LV7dYAQ/edit#gid=1477753083) and we have *Graph format* (http://edamontology.org/format_3617) so I propose it's added: do you agree?

And what to do about *Plot* (http://edamontology.org/data_2884), this is just a type of *Image* (http://edamontology.org/data_2968) right?

**Comment by veitveit** [comment]
If considered as **Data**, then _Graph data_ could be handled by _Pathway or Network_ (at least broadly). 

_Image_ and _Plot_ are quite tricky. An _Image_ could also be a photograph (e.g. of a cell through the microscope). A _Plot_ is a mostly computer-generated figure. So being a child of _Image_ should be OK unless there are other abstract formats of _Plot_ that do not necessary display on the screen or paper. If we consider computational instructions to plot an image (e.g. in Latex) an _Image_, then this should be fine?

**Comment by joncison** [comment]
I think *Plot* is a thing that's been rendered (on screen, paper, papyrus scroll _etc._).

An *Image* I don't think can be *Computational instructions*.  

To be more practical / usable, I lean towards broadening the *Plot* definition to say it can cover plotting instructions - in which case it stays where it is.  The alternative would be to say that it is purely an image / figure (in which case it could be moved under *Image*.

**Comment by veitveit** [comment]
+1
