### ISSUE TITLE
Annotation of "end-of-line" issues

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#361]
We know some concepts are the "end of the line", *i.e.* can have kids, but those kids cannot have kids.

Very nice to formally annotate such terminal concepts and (where applicable) annotate other, more specialised well-maintained ontologies that could take over / are relevant.

It needs a bit of discussion first ...

**Comment by rioualen** [comment]
Created a [discussion](https://github.com/edamontology/edamontology/discussions/889), closing this issue for now.
