### ISSUE TITLE
miRNA GFF3 format

### ISSUE THREAD

**Issue by lpantano** [edamontology/edamontology#364]
name of the format: mirGFF3 

synonymous: miRNA GFF3

definition: GFF format that contains miRNA and isomiR information for high throughput assays.

link: https://github.com/miRTop/incubator/blob/master/format/definition.md

example: https://github.com/miRTop/mirtop/blob/master/data/examples/gff/correct_file.gff

extension: gff

ontology: so

**Comment by matuskalas** [comment]
miRTop channel: https://gitter.im/mirtop/devel
