### ISSUE TITLE
Missing a button for saving intermediate progress while annotating

### ISSUE THREAD

**Issue by TatyanaGoldberg** [edamontology/edamontology#37]
When annotating, it is intuitive for me to press the "save resource" button to save the progress of my annotation. However, having the first tab annotated only, it gives me an error that it cannot be saved because of "topic:null". So, I suggest to have an additional button for saving the annotation progress (at least: browser cookies).

**Comment by joncison** [comment]
Wrong tracker, created here instead:
https://github.com/bio-tools/biotoolsregistry/issues/9
