### ISSUE TITLE
Add trr datatype

### ISSUE THREAD

**Issue by bgruening** [edamontology/edamontology#371]
*Instructions:* When making a request, replace the text < between chevrons > after first reading the instructions.  Do not change any other text, and please try to complete as much information as you can (your request will get acted on sooner if you do).

**Format name:**  trr

**Short description:** trr files contain the trajectory of a simulation experiment used by GROMACS

**Parent URI(s):** < EDAM Format URI1 | EDAM Format URI2 |... >

*Instructions:* URI(s) of suggested EDAM Format parent(s) delimited by pipe ('|') *e.g.* "http://edamontology.org/format_3547|http://edamontology.org/format_2333". Format concepts normally have two parents: 1) indicating the basic type *e.g.* "Binary format", "Textual format" *etc.* (see http://edamontology.org/format_1915) and 2) indicating the type of data *e.g.* "Image format" (see http://edamontology.org/format_2350).

**exactSynonym(s):** < synonym1 | synonym2 |... >

*Instructions:* Exact synonym(s) delimited by pipe ('|') *e.g.* "png". Other commonly-used terms, acronyms *etc.* by which the concept is referred to.  This can also include capitalisation variations (as in above example) and use of "." prefix.

**Specification:** http://manual.gromacs.org/online/trr.html

The first 4 bytes of any trr file containing 1993. See https://github.com/galaxyproject/galaxy/pull/6597/files#diff-409951594551183dbf886e24de6cb129R760

**Documentation:** < URL1 | URL2 |... >

*Instructions:* URL(s) to format documentation delimited by pipe ('|') *e.g.* "http://www.w3.org/TR/PNG/". Provide link(s) to any general documentation of the format.

**Wikipedia:** < URL1 | URL2 |... >

*Instructions:* URL(s) to Wikipedia pages delimited by pipe ('|') *e.g.* "https://en.wikipedia.org/wiki/Portable_Network_Graphics". Provide link(s) to relevant Wikipedia pages, if any.

**Publication:** < DOI1 | DOI2 |... >

*Instructions:* Citation DOI *e.g.* "10.1038%2Fnbt1031" or URL *e.g.* "https://www.iso.org/standard/29581.html". Specify a DOI of an article (if available) that describes the format, and should be used to cite mentions or usage of the format.  Specify a A DOI (if available) otherwise a URL.

**Data represented:** < EDAM Data URI1 | EDAM Data URI2 |... >

*Instructions:* URI(s) of EDAM Data concept(s) the format represents delimited by pipe ('|') *e.g.* "http://edamontology.org/data_2968". Please specify the EDAM Data concept(s) for the type(s) of data represented by the format.  If you are not sure, or if you can't find the Data concept you need, you can use free text *e.g.* "Image data" instead of the URI.

**File extension(s):** < Extension1 | Extension2 |... >

*Instructions:* File extension(s) in common use delimited by pipe ('|') *e.g.* "png". Please specify all file name extensions that are commonly used.  Do not include period (`.`) character.

**Media type:** < media_type >

*Instructions:* Media type *e.g.* "image/png". Specify the formal media type (if available) as per https://www.iana.org/assignments/media-types/media-types.xhtml.

**Comment:** < comment >

*Instructions:* Comment to the EDAM developers. Add any comments you like for the EDAM developers to consider.

**Comment by hmenager** [comment]
I think they should @bgruening , but it's ok the way it is, as long as you provide as much information as you can it's alright. thank you! :+1:

**Comment by joncison** [comment]
this one for next release (Oct/Nov)

**Comment by joncison** [comment]
@bgruening and @jlgelpi - is this format ever used outside the context of GROMACS ?   As a rule, EDAM excludes formats which are specific to a single software only - although I'm open to compelling arguments why it should be included (there can be exceptions)

cc @matuskalas

**Comment by joncison** [comment]
trr (http://www.edamontology.org/format_3910) in EDAM_dev.owl (out v.soon) and for EDAM 1.22
