### ISSUE TITLE
Term request "NMReDATA"

### ISSUE THREAD

**Issue by DSchober** [edamontology/edamontology#374]
Dear Edam Curators.
Please consider the addition of the following new open source data standard for processed NMR data (incl spectral assignments) for inclusion into EDAM. The website is at http://nmredata.org/

The term to be requested is 'NMReData'.

I would suggest to put it in as

Format

    Textual format (http://edamontology.org/format_2330)   

        Processed NMR data   <- could call this 'NMR peak assignment data' ...

            NMReDATA

So, a potential new class would look like this:

                                                

<owl:Class    rdf:about="http://edamontology.org/format_ID">

  <rdfs:label>NMReDATA</rdfs:label>

  <rdfs:subClassOf rdf:resource="http://edamontology.org/format_2330"/>

  <rdfs:comment>NMReData is a text based data standard for processed NMR data. It is relying on SDF molecule data and allows to store assignments of NMR peaks to molecule features.
        The NMR-extracted data (or “NMReDATA”) includes: Chemical shift,scalar coupling, 2D correlation, assignment, etc. Find more in the paper at D. Jeannerat, Magn. Reson. in Chem., 2017, 55, 7-14." 

  </rdfs:comment>

  <created_in>1.0</created_in>

  <oboInOwl:hasDefinition>MReData is a text based data standard for processed NMR data. It is relying on SDF molecule data and allows to store assignments of NMR peaks to molecule features.

        The NMR-extracted data (or “NMReDATA”) includes: Chemical shift,scalar coupling, 2D correlation, assignment, etc.</oboInOwl:hasDefinition>

  <documentation rdf:resource="http://nmredata.org/"/>

  <oboInOwl:hasDbXref rdf:resource="http://nmredata.org/"/>

  <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/edam#edam"/>

  <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/edam#formats"/>

</owl:Class>

 

It should reside under 'Text Format', and as it is based on the SDF format, it could perhaps be made a subclass of the 'SDF' class.

Ideally it requires an additional superclass labeled 'Processed NMR data standard' or 'Processed nuclear magnetic resonance spectroscopy data standard' (under 

http://edamontology.org/format_2350

), e.g. to disambiguate it from the NMR raw data standard nmrML.

 
Best,

 Daniel Schober

**Comment by joncison** [comment]
great, thanks @DSchober - will look at this for next release

PS. you can also use our EDAM request templates (https://github.com/edamontology/edamontology/issues/new/choose) if that would be more convenient for you (either way is fine with us)

**Comment by joncison** [comment]
done in EDAM 1.22

note, I've just made it a child of http://edamontology.org/format_3824 - the preferred label of which is now _NMR data format_, _i.e._ it covers both raw and processed data formats (which I think makes sense, as some formats can handle both?)

Can always tweak this more, if we get more formats.
