### ISSUE TITLE
Difference between Protein accession and Sequence accession (protein)

### ISSUE THREAD

**Issue by JervenBolleman** [edamontology/edamontology#375]
Dear Edam developers,

I am quite confused between the differences between a "Sequence accession (protein)" and a "Protein accession" and specifically why the "UniProt accession" would be s subclass of the first but not the second. 

Also why is there an extended UniProt accession and how is this an different concept that the non extended one.

**Comment by joncison** [comment]
Thanks for your interest in EDAM

[Sequence accession (protein)](http://edamontology.org/data_1096) is the accession number of a _protein sequence database_ entry, *i.e.* of a metadata record describing a protein sequence.

[Protein accession](http://edamontology.org/data_2907) is the accession number of protein database,  _i.e._ of a metadata record describing a protein (more broad in scope than above).

[Sequence accession (protein)](http://edamontology.org/data_1096) could (arguably should) be defined as a subclass of [Protein accession](http://edamontology.org/data_2907) : thoughts @matuskalas @veitveit ?  

Which concept are you referring to by "extended UniProt accession" ? (please give the EDAM concept URI).

**Comment by JervenBolleman** [comment]
Never mind about the UniProt accession (extended) it's an deprecated concept (data_1099)

**Comment by JervenBolleman** [comment]
I have a similar question about [Protein report](http://edamontology.org/data_0896) and [Protein signature](http://edamontology.org/data_1355) which also don't share their hierarchy.

**Comment by joncison** [comment]
@matuskalas is action needed here?

**Comment by joncison** [comment]
closing this, but write back / reopen if you have issues / questions cc @JervenBolleman @matuskalas
