### ISSUE TITLE
Duplicated term labels

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#377]
These terms do have identical label (e.g. data + operation). This will lead to issues in future developments.

 Sequence alignment              Structure alignment             Sequence assembly              
 Alignment                       Taxonomic classification        Peptide identification         
 Sequence analysis               Structure analysis              Nucleic acid structure analysis
 Mapping                         Molecular dynamics              Sequence assembly              
 Taxonomy                        Protein structure analysis      Protein secondary structure

**Comment by joncison** [comment]
This has been discussed a lot in the past, and the status quo won out. 

Bear in mind concept URIs of each EDAM subontology are in discrete namespaces, so it should be possible to work around any issues.

cc @matuskalas @hmenager 

We can always re-open / revisit if a compelling reason comes ...
