### ISSUE TITLE
[Edam Browser User] New child proposition for undefined

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#380]
[//]: # (You can add comment regarding your issue hereafter)
### Comments
from veitveit

Any expression data is often visualized by showing the distribution. The label name looks quite general, so suggestions for better ones are welcome.

[//]: # (End of issue comments)
### Hereafter are the initial version et proposed modification of attributes of the given term

| key | value |
| --- | --- |
| Attr  | **label** |
| Old | undefined |
| New | Distribution plot |
|  |  |

| key | value |
| --- | --- |
| Attr  | **definition** |
| Old | undefined |
| New | Visualization of distribution of quantitative data, e.g. expression data, by histograms, violin plots and density plots |
|  |  |

| key | value |
| --- | --- |
| Attr  | **exactSynonyms** |
| Old | undefined |
| New | Histogram, Density plot |
|  |  |

| key | value |
| --- | --- |
| Attr  | **narrowSynonyms** |
| Old | undefined |
| New |  |
|  |  |

| key | value |
| --- | --- |
| Attr  | **parent-0** |
| Old | undefined |
| New | Plot |
|  |  |

**Comment by joncison** [comment]
Looks good. 

Added as child of [Plot](http://edamontology.org/data_2884)
