### ISSUE TITLE
Proposed Data deprecations (clean-up structural bioinformatics)

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#381]
When addressing https://github.com/edamontology/edamontology/issues/353:

A (bit drastic?) option is to deprecate *all* children of [Protein structure](http://edamontology.org/data_1460)

retaining these concepts as narrowSynonyms.

What do you think @jlgelpi ?  Would these child concepts ever be useful for practical purposes, esp. annotating tools in _bio.tools_ ?

cc @matuskalas @hmenager @veitveit

**Comment by jlgelpi** [comment]
Some of them (atom, residue. chain, trace), are components of the structure, and will seldom be used separately, they may have relevance for visualization tools or residues libraries (like the PDB hetatm library). Other (structural motif, complexes, domains) are the objects of several databases (CATH, PFAM, etc.), they should be kept in EDAM. However, I'm not sure if this is the right place as they are entities that have structure, more than just a part of the structure.

**Comment by joncison** [comment]
I'm closing this (for now), given how Protein structure (http://edamontology.org/data_1460) is defined, what we have is not wrong.  And some of the concepts are used (albeit very seldom).  

cc @jlgelpi @matuskalas
