### ISSUE TITLE
"AMBER off" & "AMBER frcmod" formats question 

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#385]
These are "FF parameter formats" but were also suggested (from https://github.com/edamontology/edamontology/issues/353) to be kids of  [Tertiary structure format](http://edamontology.org/format_2033) (in addition to ) - which I'm not sure is right.

jlgelpi : please advise.

**Comment by jlgelpi** [comment]
These formats are used only for forcefield parameters. They do not include structure data other than possibly standard geometries.

**Comment by joncison** [comment]
ok thanks
