### ISSUE TITLE
operation_2946 wrong deprecated format

### ISSUE THREAD

**Issue by EvaIbarra** [edamontology/edamontology#389]
The term <http://edamontology.org/operation_2946> does not have the proper datatype format for the <owl:deprecated> value. It should be a boolean and then <obsolete_since> 1.8, but the version is written instead.

**Comment by joncison** [comment]
thanks 

fixed in EDAM_dev.owl (out very soon) to go in EDAM 1.22

cc @hmenager - one for the linter (or more generally checking we have boolean values where these are mandated)
