### ISSUE TITLE
New format "msh" (Mash sketch)

### ISSUE THREAD

**Issue by dfornika** [edamontology/edamontology#390]
**Format name:**  "msh"

**Short description:** "To make a sketch, each k-mer in a sequence is hashed, which creates a pseudo-random identifier. By sorting these hashes, a small subset from the top of the sorted list can represent the entire sequence."

**Parent URI(s):** "http://edamontology.org/format_2333"

**exactSynonym(s):** "min-hash sketch | mash sketch"

**Specification:** "https://raw.githubusercontent.com/marbl/Mash/master/src/mash/capnp/MinHash.capnp"

**Documentation:** "https://mash.readthedocs.io/en/latest/sketches.html"

**Wikipedia:** "https://en.wikipedia.org/wiki/MinHash"

**Publication:** "https://doi.org/10.1186/s13059-016-0997-x"

**Data represented:** "http://edamontology.org/data_0850 | http://edamontology.org/data_2190"

**File extension(s):** "msh"

**Example(s):** "https://mash.readthedocs.io/en/latest/tutorials.html#querying-read-sets-against-an-existing-refseq-sketch"

**Information standard(s):** "https://capnproto.org/cxx.html"

**Ontologies used:** ""

**Governing organisation(s):** "http://bnbi.org/ | https://www.genome.gov/27562809/phillippy-group/"

**Media type:** "application/octet-stream"

**Comment:** ""

**Comment by joncison** [comment]
great, thanks for the rich details! 

it will appear as [msh](http://edamontology.org/format_3911) in EDAM_dev.owl (very soon) and EDAM 1.22
