### ISSUE TITLE
New EDAM Format concept for BpForms (representation for modified DNA, RNA, and proteins)

### ISSUE THREAD

**Issue by jonrkarr** [edamontology/edamontology#391]
*Instructions:* When making a request, replace the text < between chevrons > after first reading the instructions.  The instructions can be removed. Do not change any other text, and please try to complete as much information as you can (your request will get acted on sooner if you do).

**Format name:**  BpForms

**Short description:** BpForms is a string format for concretely representing the primary structures of biopolymers, including DNA, RNA, and proteins that include non-canonical nucleic and amino acids. See https://www.bpforms.org for more information.

**Parent URI(s):**  http://edamontology.org/format_2330|http://edamontology.org/format_2035

**exactSynonym(s):** 

**Specification:** https://raw.githubusercontent.com/KarrLab/bpforms/master/bpforms/grammar.lark

**Documentation:** https://www.bpforms.org|https://sandbox.karrlab.org/notebooks/bpforms/Tutorial.ipynb|https://docs.karrlab.org/bpforms

**Wikipedia:** 

**Publication:** https://arxiv.org/abs/1903.10042

**Data represented:** http://edamontology.org/data_2044|http://edamontology.org/data_1255

**File extension(s):** 

**Example(s):** 

**Information standard(s):** 

**Ontologies used:** http://edamontology.org/data_2301

**Governing organisation(s):** https://www.karrlab.org

**Media type:** plain

**Comment:**

**Comment by joncison** [comment]
This is great, thanks!  Will appear (with some minor tweaks) as http://edamontology.org/format_3909

Out very soon in EDAM_dev.owl and soon in EDAM 1.22

**Comment by jonrkarr** [comment]
Thanks, and thanks for maintaining this.

**Comment by jonrkarr** [comment]
For integration with SBOL and other projects, I realized we need to add separate entries for DNA, RNA, and proteins because they use different alphabets. This is similar to the different IUPAC alphabets for DNA/RNA and proteins.

Here's the same information for the DNA, RNA, and protein formats, which the differences bolded.

## DNA

Format name: **BpForms DNA**

Short description: **String format for concretely representing the primary structures of DNA that include non-canonical nucleic acids. See https://www.bpforms.org for more information.**

Parent URI(s): **http://edamontology.org/format_390**

exactSynonym(s):

Specification: https://raw.githubusercontent.com/KarrLab/bpforms/master/bpforms/grammar.lark | **https://raw.githubusercontent.com/KarrLab/bpforms/master/bpforms/alphabet/dna.yml**

Documentation: https://www.bpforms.org|https://sandbox.karrlab.org/notebooks/bpforms/Tutorial.ipynb|https://docs.karrlab.org/bpforms

Wikipedia:

Publication: https://arxiv.org/abs/1903.10042

Data represented: **http://edamontology.org/data_3494|http://edamontology.org/data_1276**

File extension(s):

Example(s):

Information standard(s):

Ontologies used: http://edamontology.org/data_2301

Governing organisation(s): https://www.karrlab.org

Media type: plain

Comment:

## RNA

Format name: **BpForms RNA**

Short description: **String format for concretely representing the primary structures of RNA that include non-canonical nucleic acids. See https://www.bpforms.org for more information.**

Parent URI(s): **http://edamontology.org/format_390**

exactSynonym(s):

Specification: https://raw.githubusercontent.com/KarrLab/bpforms/master/bpforms/grammar.lark | **https://raw.githubusercontent.com/KarrLab/bpforms/master/bpforms/alphabet/rna.yml**

Documentation: https://www.bpforms.org|https://sandbox.karrlab.org/notebooks/bpforms/Tutorial.ipynb|https://docs.karrlab.org/bpforms

Wikipedia:

Publication: https://arxiv.org/abs/1903.10042

Data represented: **http://edamontology.org/data_3495|http://edamontology.org/data_1276**

File extension(s):

Example(s):

Information standard(s):

Ontologies used: http://edamontology.org/data_2301

Governing organisation(s): https://www.karrlab.org

Media type: plain

Comment:

## Protein

Format name: **BpForms protein**

Short description: **String format for concretely representing the primary structures of protein that include non-canonical nucleic acids. See https://www.bpforms.org for more information.**

Parent URI(s): **http://edamontology.org/format_390**

exactSynonym(s):

Specification: https://raw.githubusercontent.com/KarrLab/bpforms/master/bpforms/grammar.lark | **https://raw.githubusercontent.com/KarrLab/bpforms/master/bpforms/alphabet/protein.yml**

Documentation: https://www.bpforms.org|https://sandbox.karrlab.org/notebooks/bpforms/Tutorial.ipynb|https://docs.karrlab.org/bpforms

Wikipedia:

Publication: https://arxiv.org/abs/1903.10042

Data represented: **http://edamontology.org/data_2976|http://edamontology.org/data_1277**

File extension(s):

Example(s):

Information standard(s):

Ontologies used: http://edamontology.org/data_2301

Governing organisation(s): https://www.karrlab.org

Media type: plain

Comment:
