### ISSUE TITLE
New Data concept: Count matrix

### ISSUE THREAD

**Issue by daniwelter** [edamontology/edamontology#400]
**Data name:**  Count Matrix

**Short description:** A table of unnormalized values representing summarised read counts per genomic region (e.g. gene, transcript, peak).

**Parent URI(s):** [Matrix](http://edamontology.org/data_2082)

**exactSynonym(s):** Read count matrix

**Wikipedia:** n/a

**Comment:** Definition modified from [here](https://www.ebi.ac.uk/training/online/glossary/normalised-read-count-matrix). Needed for Human Cell Atlas project

**Comment by joncison** [comment]
will appear as http://edamontology.org/data_3917
