### ISSUE TITLE
New Data concept: Alignment reference

### ISSUE THREAD

**Issue by daniwelter** [edamontology/edamontology#401]
**Data name:**  Alignment reference

**Short description:** One or a set of reference molecular sequences, structures, or profiles used for alignment of genomic, transcriptomic, or proteomic experimental data.

**Parent URI(s):** [Data](http://edamontology.org/data_0006)

**exactSynonym(s):** n/a

**Wikipedia:** n/a

**Comment:** Term requested for the Human Cell Atlas project.

**Comment by joncison** [comment]
hey @daniwelter - I think we can use [Sequence set](http://edamontology.org/data_0850) for this, adding "Alignment reference" as a **narrowSynonym** (and with a tweaked definition of the concept, capturing "one or multiple"
