### ISSUE TITLE
New Data concept: Protocol

### ISSUE THREAD

**Issue by daniwelter** [edamontology/edamontology#402]
**Data name:** Protocol

**Short description:** Information about how a scientific experiment or analysis was carried out that results in a specific set of data or results used for further analysis or to test a specific hypothesis.

**Parent URI(s):** [dData](http://edamontology.org/data_0006)

**exactSynonym(s):** n/a

**Wikipedia:** n/a

**Comment:**  Term requested for the Human Cell Atlas project.

**Comment by joncison** [comment]
hey @daniwelter we actually have [Experiment report](http://edamontology.org/data_2531) which fits, but your "Protocol" (and your definition) is much better.  Will refactor now ("Protocol" will become the primary label).

**Comment by daniwelter** [comment]
@joncison We considered whether experiment report would be good enough for what we need but we felt it wasn't specific enough to our criteria for a protocol. Happy with your suggested solution.

**Comment by joncison** [comment]
OK - great!  And thanks a million for the brilliant work with the concept suggestions - made my life MUCH easier.  All done now!  cc @matuskalas @hmenager @veitveit  - the release 1.23 is good to go.

**Comment by daniwelter** [comment]
Great to hear! Thanks for getting through the terms so quickly. Once the release is out, I can pull the new version into the HCA OLS instance and that'll make my curators very happy :)
