### ISSUE TITLE
New Data concept: Quality control report

### ISSUE THREAD

**Issue by daniwelter** [edamontology/edamontology#403]
**Data name:** Quality control report

**Short description:** A collection of results of testing an output or a sample of an output against the desired specification or standard.

**Parent URI(s):** [Report](http://edamontology.org/data_2048)

**exactSynonym(s):** QC report | QC metrics | Quality control metrics

**Wikipedia:** n/a

**Comment:** Term requested for the Human Cell Atlas project.

**Comment by joncison** [comment]
Will appear as http://edamontology.org/data_3914
