### ISSUE TITLE
New Format concept: Zarr

### ISSUE THREAD

**Issue by daniwelter** [edamontology/edamontology#404]
**Format name:**  Zarr

**Short description:** The Zarr format is an implementation of chunked, compressed, N-dimensional arrays for storing data. 

**Parent URI(s):** http://edamontology.org/format_2333|http://edamontology.org/format_3033

**exactSynonym(s):** n/a

**Specification:** https://zarr.readthedocs.io/en/stable/spec.html

*Instructions:* URL to formal specification of the format *e.g.* "http://www.w3.org/TR/PNG/". Provide a link to the official specification of the format (if available), either an XML schema (XSD), or other rigorous & comprehensive syntax specification.

**Documentation:** https://zarr.readthedocs.io/en/stable/spec.html|https://pangeo.io/data.html

**Wikipedia:** n/a

**Publication:** n/a

**Data represented:**  http://edamontology.org/data_3112|http://edamontology.org/data_2535

**File extension(s):** zarray|zgroup

**Example(s):** https://zarr.readthedocs.io/en/stable/spec/v2.html#examples

**Information standard(s):** n/a

**Ontologies used:** n/a

**Governing organisation(s):** n/a

**Media type:** n/a

**Comment:** Required by the Human Cell Atlas project.

**Comment by joncison** [comment]
will appear as http://edamontology.org/format_3915
