### ISSUE TITLE
New Format concept: MTX

### ISSUE THREAD

**Issue by daniwelter** [edamontology/edamontology#405]
**Format name:**  MTX

**Short description:**The Matrix Market matrix (MTX) format stores numerical or pattern matrices in a dense (array format) or sparse (coordinate format) representation. 

**Parent URI(s):** http://edamontology.org/format_2330|http://edamontology.org/format_3033

**exactSynonym(s):** n/a

**Specification:** https://reference.wolfram.com/language/ref/format/MTX.html

**Documentation:** https://reference.wolfram.com/language/ref/format/MTX.html

**Wikipedia:** n/a

**Publication:** n/a

**Data represented:** http://edamontology.org/data_3112%7Chttp://edamontology.org/data_2535

**File extension(s):** mtx

**Example(s):** https://reference.wolfram.com/language/ref/format/MTX.html

**Information standard(s):** n/a

**Ontologies used:** n/a

**Governing organisation(s):** https://www.nist.gov/

**Media type:** n/a

**Comment:** Required by the Human Cell Atlas project

**Comment by joncison** [comment]
will appear as http://edamontology.org/format_3916
