### ISSUE TITLE
New Format concept: Loom

### ISSUE THREAD

**Issue by daniwelter** [edamontology/edamontology#406]
**Format name:**  Loom

**Short description:** The Loom file format is based on HDF5, a standard for storing large numerical datasets. The Loom format is designed to efficiently hold large omics datasets. Typically, such data takes the form of a large matrix of numbers, along with metadata for the rows and columns. 

**Parent URI(s):** http://edamontology.org/format_2333|http://edamontology.org/format_3590

**exactSynonym(s):** n/a

**Specification:** https://linnarssonlab.org/loompy/format/index.html

**Documentation:** https://linnarssonlab.org/loompy/format/index.html|https://linnarssonlab.org/loompy/semantics/index.html

**Wikipedia:** n/a

**Publication:** n/a

**Data represented:** http://edamontology.org/data_3112%7Chttp://edamontology.org/data_2535

**File extension(s):** loom

**Example(s):** https://linnarssonlab.org/loompy/semantics/index.html

**Information standard(s):** n/a

**Ontologies used:** n/a

**Governing organisation(s):** n/a

**Media type:** n/a

**Comment:** Required for the Human Cell Atlas project

**Comment by joncison** [comment]
will appear as http://edamontology.org/data_3913
