### ISSUE TITLE
Query: Synthetic Chemistry

### ISSUE THREAD

**Issue by allysonlister** [edamontology/edamontology#407]
Good afternoon! Quick question please.

EDAM term http://edamontology.org/topic_3371 (Synthetic Chemistry) has a synonym of Synthetic organic chemistry. I'm just wondering if this is a truly synonymous topic? In the same way as Chemistry and Organic Chemistry are two different research areas, does the same hold true of Synthetic (Organic) Chemistry? I'm not an expert here, but am unsure about its use as a synonym.

Thanks very much!

**Comment by joncison** [comment]
thanks @allysonlister I'm not an expert either but I strongly suspect it would be better to say
**Synthetic chemistry** _hasNarrowSynonym_ **Synthetic organic chemistry**

will change the synonym type now ...
