### ISSUE TITLE
Biotherapeutics: typo in definition

### ISSUE THREAD

**Issue by allysonlister** [edamontology/edamontology#408]
Good afternoon! Just wanted to drop you a line about Biotherapeutics - looks like it should read "and" in the definition? Thanks!

http://edamontology.org/topic_3374 | Biotherapeutics | The process of formulating abd administering a pharmaceutical compound to achieve a therapeutic effect.

**Comment by joncison** [comment]
Thanks Ally ... looking to make a new release in July, so please send any other suggestions, cheers!
