### ISSUE TITLE
CAS Number listed twice

### ISSUE THREAD

**Issue by neilotte** [edamontology/edamontology#416]
It appears there are two IRIs for the class representing CAS Numbers in the present release:

•	http://edamontology.org/data_1002 
•	http://edamontology.org/data_3102

Does this look correct to you, or is there really a difference here?

Best,
 Neil

**Comment by joncison** [comment]
Ooh, that's not so good.  Looks like a redundancy crept in (a long time ago!)

Will fix by deprecating http://edamontology.org/data_3102 (whilst preserving all relevant annotations)

Thanks for spotting!
