### ISSUE TITLE
Problem with definition of evidence

### ISSUE THREAD

**Issue by Mttbnchtt** [edamontology/edamontology#417]
The definition of [evidence](http://edamontology.org/data_2042) is, I would argue, not correct. The current definition is the following: "Typically a statement about some data or results, including evidence or the source of a statement, which may include computational prediction, laboratory experiment, literature reference etc."

There are two issues:
1. It is circular because the term 'evidence' appears in the definition.
2. Properly speaking, evidence (or a piece of evidence) is not a statement but, rather, the information that the statement conveys or the event or fact that it describes. For example, evidence for General Relativity is not Eddington's statement that a specific astronomical observation turned out the way it did. Evidence is rather that the observation was so-and-so or, perhaps even more properly, that the facts observed were so-and-so.

**Comment by joncison** [comment]
Thanks!

Now redefined:
_"Typically a human-readable summary of body of facts or information indicating why a statement is true or valid. This may include a computational prediction, laboratory experiment, literature reference etc."_

**Comment by joncison** [comment]
@Mttbnchtt ping me here if the above is not OK
