### ISSUE TITLE
Annotation of visualisation tools: How to do? How should EDAM model the related concepts?

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#42]
Examples:
https://bio.tools/tool/BioJS/msa/0.4.8
https://bio.tools/tool/RostLab/Aquaria/1

## Scenario:
A visualisation tool consumes a concrete type of data (D), and visualises it.

### Notes:
 - The output of this visualisation operation (VO) is the visualisation (V) itself.
 - This visualisation (V) is ontologically neither an operation nor a type of data.
 - The visualisation (V) is usually on a screen, but can also be e.g. just sent to a printer, or a file, or only generated into a computer memory representation.

### Implication for EDAM:
 - So what is the output type of data?
 - And format?
 - Is there any output data at all?
 - Is the output data the same as input (V=D), just in a different, "graphical" format?
 - What is the format then? Especially if it's not directly a graphical image file format (e.g. PNG, SVG) or a full valid HTML record?
 - Is it just a binary blob?
 - But isn't then EVERYTHING digital a binary blob?

## Bonus scenario:
The same tool as above can in addition to the visualisation "save"/"export" some data from the visualisation.

### Notes and questions:
 - The input and its format would then be the same as the output of the visualisation (V) discussed above, I suppose.
 - But what are the operations here?
 - Perhaps some _Data extraction_, which is highly useful elsewhere, too (And is perhaps better than abusing _Data retrieval_ which states for retrieving records from a database and not from other data).

## Bonus bonus:
 - _Data editting_ (especially "manual") can be another natural operation with a visualisation!
 - _Visual analysis_ would be another (especially "manual") operation with a visualisation!

__How to annotate these?!?__

**Comment by joncison** [comment]
So I'd suggest visualisation (V) is simply "Image" (http://edamontology.org/data_2968).  The format would only be specified if it's actually rendered to a file, and then it is PDF or whatever.

As for "Data editing" see "Editing" (http://edamontology.org/operation_3096)
As for "Visual analysis" (which is very vague) see "Analysis" (http://edamontology.org/operation_2945)

I believe this answers your questions, but feel free to re-open otherwise.
