### ISSUE TITLE
file extension field for file formats

### ISSUE THREAD

**Issue by mr-c** [edamontology/edamontology#44]
Thanks!

**Comment by matuskalas** [comment]
018754f:

Added a *file_extension* attribute for '|'-separated lists of file extensions.

Populated examples:
`<file_extension>xml</file_extension>`
`<file_extension>oxlicg</file_extension>`
`<file_extension>imzML|ibd</file_extension>`

**Comment by mr-c** [comment]
Thanks!

Mar, 9 feb. 2016, 04:48, Matúš Kalaš <notifications@github.com> a scris:

> Closed #44 <https://github.com/edamontology/edamontology/issues/44>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edamontology/edamontology/issues/44#event-543856954>.
>
-- 
Michael R. Crusoe     CWL Community Engineer     crusoe@ucdavis.edu
<mcrusoe@msu.edu>
Common Workflow Language project    University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe
