### ISSUE TITLE
Add "Multivariate analysis" as narrowSynonym or concept under "Statistical calculation"

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#467]

**Comment by veitveit** [comment]
Multivariate analysis not necessarily is statistical (e.g. clustering).

**Comment by joncison** [comment]
I added _Multivariate analysis_ as **narrowSynonym** of [Mathematics](http://edamontology.org/topic_3315) and _Multivariate statistics_ as **narrowSynonym** of [Statistics and probability](http://edamontology.org/topic_2269).  

Don't want to open the can of worms (just yet) to add these concepts as operations ...
