### ISSUE TITLE
Add "Quantitative proteomics" as narrowSynonym under "Proteomics" (if not its own concept - see "Quantitative genetics")

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#502]

**Comment by joncison** [comment]
Added as **narrowSynonym** but please @veitveit advise on what (if any) new concepts should be added under [Proteomics](http://edamontology.org/topic_0121) as new concepts (see the [Proteomics](http://edamontology.org/topic_0121) concept definition for what synonyms are currently defined - some of these to become sub-concepts?)

**Comment by veitveit** [comment]
Given that the next level in Genomics is quite broad and has many terms, I would add this as subterm to proteomics for consistency. There are other ways of doing proteomics, which are not quantitative

**Comment by joncison** [comment]
Will do ... but pls. take a look at [Proteomics](http://edamontology.org/topic_0121) and advise what other (if any of the) synonyms should be converted to sub-concepts.  We'd need a nice but not huge set of sub-concepts - with similar-ish granularity as the kids of _Genomics_
