### ISSUE TITLE
Revision of preferred labels under Data "Alignment"

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#511]
We have terms like [Sequence alignment (protein)](http://edamontology.org/data_1384) which might look nice in the tree, but certainly in no way reflects the vernacular. The change will be to make the preferred labels e.g.  _Protein sequence alignment_.  

cc @matuskalas @veitveit @hmenager - I think this is a no-brainer ?

**Comment by joncison** [comment]
So I assumed this is OK, I also added [DNA structure alignment](http://edamontology.org/data_3924) to fill in an obvious gap.

**Comment by jlgelpi** [comment]
Although Protein structure alignment is a common practice, this is not the case for DNA. It can make sense for RNA as RNAs have not obvious 3D structures. I would say rather Nucleic Acids Structure alignment.

**Comment by joncison** [comment]
Thanks @jlgelpi   and sorry because the title should have said **Data** branch not Operation (will fix)

In **Data** we have:

Structure alignment
    Nucleic acid structure alignment 
            DNA structure alignment
            RNA structure alignment
    Protein structure alignment 

Is this OK, or do you think the "DNA structure alignment" can be dropped (or what?)  I appreciate the nucleic acid alignments are a bit of a rare thing.

**Comment by jlgelpi** [comment]
I would keep it, just for completness, but I doubt that it has much use.
