### ISSUE TITLE
Consider deprecating "Global alignment" and "Local alignment"

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#516]
Notions of [Global alignment](http://edamontology.org/operation_0496) and [Local alignment](http://edamontology.org/operation_0495) are examples of _how_ something is done, not _what_ is done.   

They create a secondary axis of annotation for alignment tools - with respect to the primary axis _e.g._ terms like _Protein sequence alignment_.  This creates problems arising from the choice (which one, or both axes) that people use to annotate. 

So I'm consider deprecating those two terms, making them _narrowSynonym_ of _Sequence alignment_

Like to hear an opinion @matuskalas @veitveit @hmenager as this is a decision that could apply all across EDAM (hence potentially a big refactor leading to a simpler / more usable? EDAM)

**Comment by matuskalas** [comment]
IMHO, global vs local aln are _what_ not _how_.

_How_ can be the same thing, e.g. the algorithm of needle & water is pretty much the same.

_What_ is different, i.e. finding a matching subsequence & position, vs aligning the whole sequences.

Sure, these days it's much more rare to do a global (pairwise) aln as opposed to local, but it's still useful in some cases. And almost always in MSA, phylogeny, etc. ;-)

**Comment by joncison** [comment]
thanks @matuskalas, fair points.  Will leave as-is.
