### ISSUE TITLE
Consolidate Sequence-profile alignment etc.

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#517]
These are all somewhat overlapping concepts:

-  [Sequence-profile alignment](http://edamontology.org/data_0869) 
-  [Sequence signature matches](http://edamontology.org/data_0858)
-  [Sequence signature report](http://edamontology.org/data_2762)

*i.e.* reports on the alignment of a sequence to a sequence profile (or - more generally - motif or other sequence signature).

These types don't really have formats as-such, therefore I'm proposing to see if we just do with once concept, probably _Sequence signature report_ with appropriate synonyms.

What do you think @matuskalas @veitveit @hmenager ?

NB. prob. also holds for [Profile-profile alignment](http://edamontology.org/data_0868)

**Comment by joncison** [comment]
Taking a closer look:
-  [Sequence-profile alignment](http://edamontology.org/data_0869) is for the alignment, but in practice (I think) is synonymous with [Sequence signature matches](http://edamontology.org/data_0858).  Same goes, I think, for  [Profile-profile alignment](http://edamontology.org/data_0868)
 
-  [Sequence signature report](http://edamontology.org/data_2762) is distinct in that it holds / describes the pattern, motif, profile etc. itself (not matches to sequences)

So I'd propose to merge the first lot and keep the second as discrete.

What do you think @matuskalas ?

**Comment by veitveit** [comment]
+1

**Comment by joncison** [comment]
thanks @veitveit, done.
