### ISSUE TITLE
Structure clustering operation wrong ID

### ISSUE THREAD

**Issue by hansioan** [edamontology/edamontology#518]
The operation concept "Structure clustering" which has the path the operation tree:
Operation -> Clustering -> Structure clustering
seems to have the ID of 
http://edamontology.org/topic_2844
which is an id for topics. 

One can check BioPortal by following the link:
http://edamontology.org/topic_2844
or in the IFB EDAM Browser:
https://ifb-elixirfr.github.io/edam-browser/#topic_2844&operation

**Comment by matuskalas** [comment]
Thanks for spotting @hansioan !
Is it used anywhere in bio.tools @hansioan ? Thanks!

**Comment by hansioan** [comment]
@matuskalas It is actually not used at all in bio.tools because it doesn't validate. I found it from another source.

**Comment by joncison** [comment]
thanks!  will fix later today ...
