### ISSUE TITLE
Add "Copy number variation detection" Operation

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#528]
Add "Copy number variation detection" Operation as child of *Structural variation detection*

Add subconcepts:
* Deletion detection
* Duplication detection
* Complex CNV detection
* Amplification detection
* Copy number estimation (which exists already)

**Comment by d-salgado** [comment]
Can you please tell me when you have an edam test version for me to check that the terms are aligned with our discussions ?
Thanks

**Comment by joncison** [comment]
Hi @d-salgado 

All the changes are now available in https://github.com/edamontology/edamontology/blob/master/EDAM_dev.owl and will be pushed into production (and thus made available in the BioPortal, OLS, and edamBrowser browsers) soon.

It'd be great if you can take a look at the changes, e.g. using [Protege](https://protege.stanford.edu/).

Thanks!
