### ISSUE TITLE
Should minimum information documents be added to EDAM?

### ISSUE THREAD

**Issue by mayerg97** [edamontology/edamontology#53]
http://www.psidev.info/node/91

**Comment by joncison** [comment]
@mayerg97, if I understand the question right, then I think the short answer is "no".  Reporting guidelines (such as "Minimum information for ...") are more in scope of BioSharing.

BUT data formats corresponding to those min. info. standards certainly are in scope (please let us know if we're missing any)

So I'm closing this .. but pls. reopen if I got the wrong end of the stick
