### ISSUE TITLE
Protein Inference 

### ISSUE THREAD

**Issue by PratikDJagtap** [edamontology/edamontology#532]
*Instructions:* When making a request, replace the text < between chevrons > after first reading the instructions.  The instructions can be removed. Do not change any other text, and please try to complete as much information as you can (your request will get acted on sooner if you do).

**Operation name:**  < operation_name >

*Instructions:*  Name of operation, *e.g.* "Sequence aignment".  This is the most commonly used term.  

**Short description:** < short_description >

*Instructions:* Short description, *e.g.* "Align (identify equivalent sites within) molecular sequences." A sentence or two describing the operation, specifically stating *what* is done but not *how*. Keep it concise, lucid and avoid jargon and acronyms. See http://edamontology.org/operation_0004 for examples.

**Parent URI(s):** < EDAM Operation URI1 | EDAM Operation URI2 |... >

*Instructions:* URI(s) of suggested EDAM Operation parent(s) delimited by pipe ('|') *e.g.* "http://edamontology.org/operation_2928".  Pick the single, most relevant operation. In some (exceptional) cases, a broad operation type (top-level operation) *e.g.* "Comparison", "Calculation" *etc.* (see http://edamontology.org/operation_0004) may also be specified.

**exactSynonym(s):** < synonym1 | synonym2 |... >

*Instructions:* Exact synonym(s) delimited by pipe ('|') *e.g.* "Sequence alignment generation". Other commonly-used terms, acronyms *etc.* by which the concept is referred to.  

**Wikipedia:** < URL1 | URL2 |... >

*Instructions:* URL(s) to Wikipedia pages delimited by pipe ('|') *e.g.* "https://en.wikipedia.org/wiki/Sequence_alignment". Provide link(s) to relevant Wikipedia pages, if any.

**Comment:** < comment >

*Instructions:* Comment to the EDAM developers. Add any comments you like for the EDAM developers to consider.

**Comment by joncison** [comment]
Hi @PratikDJagtap 

The term you need is [Protein identification](http://edamontology.org/operation_3767) which has narrowSynonym "Protein inference".
