### ISSUE TITLE
Phosphosite localization

### ISSUE THREAD

**Issue by PratikDJagtap** [edamontology/edamontology#534]
*Instructions:* When making a request, replace the text < between chevrons > after first reading the instructions.  The instructions can be removed. Do not change any other text, and please try to complete as much information as you can (your request will get acted on sooner if you do).

**Data name:**  < data_name >

*Instructions:*  Name of the type of data, *e.g.* "Protein sequence".  This is the most commonly used term.  

**Short description:** < short_description >

*Instructions:* Short description, *e.g.* "One or more protein sequences, possibly with associated annotation." A sentence or two describing the type of data. Keep it concise, lucid and avoid jargon and acronyms. See http://edamontology.org/data_0006 for examples.

**Parent URI(s):** < EDAM Data URI1 >

*Instructions:* URI(s) of suggested EDAM Data parent *e.g.* "http://edamontology.org/data_2044". Data concepts have a single parent only.

**exactSynonym(s):** < synonym1 | synonym2 |... >

*Instructions:* Exact synonym(s) delimited by pipe ('|') *e.g.* "Protein sequences". Other commonly-used terms, acronyms *etc.* by which the concept is referred to.

**Wikipedia:** < URL1 | URL2 |... >

*Instructions:* URL(s) to Wikipedia pages delimited by pipe ('|') *e.g.* "https://en.wikipedia.org/wiki/Protein_primary_structure". Provide link(s) to relevant Wikipedia pages, if any.

**Comment:** < comment >

*Instructions:* Comment to the EDAM developers. Add any comments you like for the EDAM developers to consider.

**Comment by matuskalas** [comment]
Done, added as a narrow synonym of Post-translational modification analysis / prediction.
