### ISSUE TITLE
Format for Vega

### ISSUE THREAD

**Issue by jonrkarr** [edamontology/edamontology#552]
**Format name:**  Vega

**Short description:** Vega is a visualization grammar, a declarative language for creating, saving, and sharing interactive visualization designs. With Vega, you can describe the visual appearance and interactive behavior of a visualization in a JSON format, and generate web-based views using Canvas or SVG.

**Parent URI(s):** "http://edamontology.org/format_3464|http://edamontology.org/format_3547

**exactSynonym(s):** 

**Specification:** https://vega.github.io/vega/docs/#specification

**Documentation:** https://vega.github.io/vega/docs/

**Wikipedia:** 

**Publication:** 10.1145/2642918.2647360

**Data represented:** http://edamontology.org/data_2968

**File extension(s):** json

**Example(s):** https://vega.github.io/vega/examples/

**Information standard(s):** 

**Ontologies used:** 

**Governing organisation(s):** http://idl.cs.washington.edu/

**Media type:** application/json

**Comment:**

**Comment by joncison** [comment]
Thanks for this and the other suggestions @	jonrkarr, if you have any others please keep posting your issues - will try to incorporate them into the next release which we're planning to put out soon.
