### ISSUE TITLE
Format for Vega lite

### ISSUE THREAD

**Issue by jonrkarr** [edamontology/edamontology#553]
**Format name:**  Vega-lite

**Short description:** Vega-Lite is a high-level grammar of interactive graphics. It provides a concise JSON syntax for rapidly generating visualizations to support analysis. Vega-Lite specifications can be compiled to Vega specifications.

**Parent URI(s):** "http://edamontology.org/format_3464|http://edamontology.org/format_3547

**exactSynonym(s):** 

**Specification:** https://vega.github.io/vega-lite/docs/#spec

**Documentation:** https://vega.github.io/vega-lite/docs/

**Wikipedia:** 

**Publication:** 10.1109/TVCG.2016.2599030

**Data represented:** http://edamontology.org/data_2968

**File extension(s):** json

**Example(s):** https://vega.github.io/vega-lite/examples/

**Information standard(s):** 

**Ontologies used:** 

**Governing organisation(s):** http://idl.cs.washington.edu/

**Media type:** application/json

**Comment:**

**Comment by joncison** [comment]
thanks a million for the detailed info .. will appear in EDAM 1.25 ... out soon
