### ISSUE TITLE
Format for GFA

### ISSUE THREAD

**Issue by mr-c** [edamontology/edamontology#558]
**Format name:**  GFA

**Short description:**  Graphical Format Assembly captures sequence graphs as the product of an assembly, a representation of variation in genomes, splice graphs in genes, or even overlap between reads from long-read sequencing technology

**Parent URI(s):** http://edamontology.org/format_2330 | http://edamontology.org/format_2561

**exactSynonym(s):** gfa | .gfa

**Specification:** http://gfa-spec.github.io/GFA-spec/

**Documentation:** http://gfa-spec.github.io/GFA-spec/

**Wikipedia:**

**Publication:**

**Data represented:** http://edamontology.org/data_3494 ?

**File extension(s):** gfa

**Example(s):** https://github.com/sjackman/assembly-graph/blob/master/sample.gfa | https://github.com/sjackman/assembly-graph/blob/master/loop.gfa

**Information standard(s):**

**Ontologies used:** 

**Governing organisation(s):** https://github.com/GFA-spec

**Media type:** 

**Comment:** Similar to FASTG

**Comment by sjackman** [comment]
Should this description differentiate between the incompatible versions GFA1 and GFA2?

I suggest using these two examples at https://github.com/sjackman/gfalint/tree/master/examples
GFA1: https://raw.githubusercontent.com/sjackman/gfalint/master/examples/big1.gfa
GFA2: https://raw.githubusercontent.com/sjackman/gfalint/master/examples/big2.gfa

**Comment by sjackman** [comment]
I'd remove the comment `Comment: Similar to FASTG`. It's not really more similar to FASTG than to any other `Sequence assembly format (text)`.

**Comment by mr-c** [comment]
> I'd remove the comment Comment: Similar to FASTG. It's not really more similar to FASTG than to any other Sequence assembly format (text).

Ah, I was speaking ontologically; that they are both sequence assembly formats.

**Comment by mr-c** [comment]
> Should this description differentiate between the incompatible versions GFA1 and GFA2?

Sure, I'd support splitting this into two concepts, GFA1 and GFA2 (no need for a parent concept since they are incompatible)

**Comment by joncison** [comment]
Thanks both! Will go in as two concepts / different URIs.
