### ISSUE TITLE
potential data types

### ISSUE THREAD

**Issue by only1chunts** [edamontology/edamontology#561]
Hi, 
Sorry for not following the data concepts template you kindly provided!
At GigaDB we use a set of file types in a controlled vocabulary, I've been reconciling those to the EDAM_1.23 release and found a number of them missing from EDAM. Attached is a simple TSV table of those file types with the extension suffix expected and a short description. Sorry no URL links to references or any other details you ask for.
My intention was to link out to EDAM as the reference for each of our file type descriptions, so if you add any of these I can update GigaDB to include the EDAM links.
Hope it can be useful to you.
[new-edam-suggestions.txt](https://github.com/edamontology/edamontology/files/4661959/new-edam-suggestions.txt)

**Comment by joncison** [comment]
Thanks a million for this, and for the GigaDB::EDAM tie-in. 

I'm taking a look now - aiming to get the new concepts in the next release out soon.  We can always flesh out the details (more concept metadata) in due course. 

cc @veitveit  @matuskalas @hmenager

**Comment by joncison** [comment]
@only1chunts  ... me and @matuskalas are working on a [g-sheet](https://docs.google.com/spreadsheets/d/1w80Ky5Q-bPTqlNcZ6MjzNsOP24YuAOBbCH1cg0ba4D0/edit#gid=0) with your terms right now.

**Comment by joncison** [comment]
All done @only1chunts ... will be out in the next release (coming soon)
