### ISSUE TITLE
Comment regarding the EDAM Term "Design"

### ISSUE THREAD

**Issue by sduvaud** [edamontology/edamontology#562]
Hi,

As you know, we are moving from in-house keywords to EDAM in ExPASy. One of our resource providers, Vincent Zoete, who develops resources such as SwissDock, and who is in the molecular modelling/design/docking domain, has chosen "Design" as one of the operations to describe some of his resources. However, looking at the page [https://www.ebi.ac.uk/ols/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Foperation_2430]() it is not clear for him whether the term applies to small molecules (like the ones he usually deals with), since the term seems to be referring to proteins/nucleic acid sequences. Is he correct?

If yes, is there a way to either create a new term like "Small molecule design" or update the definition? Thank you very much.

**Comment by joncison** [comment]
Hi

[Design](http://edamontology.org/operation_2430) would do, but it's is a very high-level concept - it would be better to use something more specific.   I'll add _Small molecule design_.  

PS.  we'll have a few new design concepts going into the next release, see e.g. https://github.com/edamontology/edamontology/issues/542, https://github.com/edamontology/edamontology/issues/540 and https://github.com/edamontology/edamontology/issues/537

PPS.  also applicable is the EDAM Topic [Medicinal chemistry](http://edamontology.org/topic_0209) with exactSynonym _Drug design_ 

Cheers!

**Comment by sduvaud** [comment]
Hi Jon!

Thanks a million! I'll let Vincent know.

Best, Severine

**Comment by matuskalas** [comment]
"Small molecule design" sounds reasonable to me, unless there is a better term for it. But it definitely should be a Topic, not an Operation. Reminder: Topics should, whenever possible, have a corresponding Wikipedia article.

**Comment by matuskalas** [comment]
sorry, closed by mistake, reopening

**Comment by joncison** [comment]
Hi @sduvaud 

A bit of clean-up was needed, but in EDAM 1.25 (out this week) there will _Protein design_ and _Small molecule design_ sitting under _Design_, alongside _Nucleic acid design_.  These are obviously all very high-level operations, but useful for categorising the function of tools at a high level. 

The existing concept _Virtual screening_ is now a child of _Small molecule design_ ... with clean-ups of synonyms etc.

Hope this helps!

J:)
