### ISSUE TITLE
Docker Image format_3973 should not be subClassOf Raw Sequence Format

### ISSUE THREAD

**Issue by mr-c** [edamontology/edamontology#563]
http://edamontology.org/format_3973

Raw Sequence Format has a biological meaning, docker images are not biological data

This wasn't part of the original request: https://github.com/edamontology/edamontology/issues/556

**Comment by joncison** [comment]
Oops.  Will fix in next release or quietly patch the released files ...

**Comment by matuskalas** [comment]
+ rename to Docker image
+ remove file extension
+ make Wikipedia link rdfs:seeAlso instead

**Comment by matuskalas** [comment]
Million thanks @mr-c for spotting this and @melibleq @hmenager for fixing the whole concept.

Note: A separate 'Docker file' concept (the recipe text file) is awaiting merge.
