### ISSUE TITLE
FAIR Topic concept

### ISSUE THREAD

**Issue by vdda** [edamontology/edamontology#581]
*Instructions:* When making a request, replace the text < between chevrons > after first reading the instructions.  The instructions can be removed. Do not change any other text, and please try to complete as much information as you can (your request will get acted on sooner if you do).

**Topic name:**  < FAIR>

**Short description:** < Topic related with FAIR Principales, [first published in 2016](https://www.nature.com/articles/sdata201618), contain guidelines for good data management practice that aim at making data FAIR: findable, accessible, interoperable, and reusable >

**Parent URI(s):** < EDAM Topic: Ontology and terminology, "http://edamontology.org/topic_0089">

**exactSynonym(s):** < FAIRification | FAIRness >

**narrowSynonym(s):** < synonym1 | synonym2 |... >

**Wikipedia:** < URL1 | URL2 |... >

**Comment by vdda** [comment]
Wikipedia: < "https://en.wikipedia.org/wiki/FAIR_data" >

**Comment by matuskalas** [comment]
Summary (#584)

Added 3 generic topics to start with:
  - Open science (http://edamontology.org/topic_4010)
  - Data management (http://edamontology.org/topic_4011)
  - FAIR data (http://edamontology.org/topic_4012, under both of the above 2)

This should now enable the "first-pass" annotations of tools and training materials in generic registries. Please feel free to start using the above IDs/URIs immediately, even if the URIs don't de-reference yet. They will be kept persistent.

For everyone "new" to this effort reading this:
A bigger collaborative work on extending EDAM with data management and open science concepts has started. Please let us now if you want to join the effort (GitHub or twitter @edamontology is great)
