### ISSUE TITLE
New format for low Entropy Model Specification language

### ISSUE THREAD

**Issue by jonrkarr** [edamontology/edamontology#588]
**Format name:**  LEMS

**Short description:** XML-based language for specifying generic models of hybrid dynamical systems.

**Parent URI(s):** format_2013|format_2332

**exactSynonym(s):** Low Entropy Model Specification language

**Specification:** https://github.com/LEMS/LEMS/tree/master/Schemas/LEMS

**Documentation:** http://lems.github.io/LEMS/

**Wikipedia:** 

**Publication:** 10.3389/fninf.2014.00079

**Data represented:** data_3241|data_3869

**File extension(s):** xml

**Example(s):** http://lems.github.io/LEMS/|https://github.com/LEMS/LEMS/tree/master/examples

**Information standard(s):** 

**Ontologies used:** 

**Governing organisation(s):** https://neuroml.org/

**Media type:** application/xml

**Comment by matuskalas** [comment]
🙏🏽 Giant thanks for all your formats additions @jonrkarr !

Please keep them coming if you have more 👍🏽

**Comment by jonrkarr** [comment]
Closing because this is a duplicate of #710
