### ISSUE TITLE
Add media types to format concepts

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#6]
Add annotation property on "format" terms for mime-type, then add annotations to all relevant classes.   Concentrate on formal IANA/IETF types first.  

application/xml
text/csv
text/html
text/plain
text/xml

Convenient place I can pull the bioinformatics media types from, e.g.:
application/cellml+xml  ??

Camille says ...
As you may remember, we (MIRIAM Registry) are keen on using the EDAM ontology.

> I noticed the "Format" branch and I am wondering whether it would be possible to also record the media type [1] of each format (those small strings such as "text/turtle" or "application/cellml+xml")?

[1] http://en.wikipedia.org/wiki/Internet_media_type

You can use the official source
(http://www.iana.org/assignments/media-types), but not all formats are actually registered there. Also http://www.fileformat.info/info/mimetype/index.htm (which combines info from multiple sources) and finally you can refer to the individual format's specification and website.

ps. If you want an assertion to be inherited by all subclasses then you need to use an object or datatype property. Annotation properties aren’t inherited in any logical sense. Prob I’d create a little collection of mime types and then axiomatise your fomats as such:       (parent class) has_mime_type some mime_type_x       (sub class of parent class) has_mime_type some mime_type_y   --- <note it would also inherent has_mime_type some mime_type_x from parent class so has both x and y here>

**Comment by hmenager** [comment]
This is also requested in the context of CWL descriptions:
https://groups.google.com/d/msg/common-workflow-language/X9_vv-rNep4/nUXUctm1AgAJ

**Comment by joncison** [comment]
Ready to add these as soon as someone tells us what they are - right now, almost no media types are defined for bioinformatics.

**Comment by matuskalas** [comment]
018754f:

Added a *media_type* URI attribute.
 `<media_type rdf:resource="..."/>`

Populated example media types: application/xml, application/cellml+xml
 `<media_type rdf:resource="http://www.iana.org/assignments/media-types/application/xml"/>`
 `<media_type rdf:resource="http://www.iana.org/assignments/media-types/application/cellml+xml"/>`

**Comment by joncison** [comment]
@matuskalas @hmenager - do you know if there's any movement here?  I rather suspect we're still lacking media types ...

**Comment by matuskalas** [comment]
@joncison As you know, we've been supporting media types in EDAM since long ago. As long as there is a specific media type existing for a given format, it can (and should) be noted in EDAM. A code review & polishing could be done to ensure maximum coverage in EDAM.

The other way round, _i.e._ creating & standardising media types, is a very different kind of project altogether. Some work in that direction has been done by @mr-c & al

**Comment by rioualen** [comment]
Closing this issue, as it's been inactive for a long time, and it seems that it's at least partially fixed. 

Please open a new issue if more formats need to be added/updated.
