### ISSUE TITLE
Electrocardiography

### ISSUE THREAD

**Issue by Kigaard** [edamontology/edamontology#608]
**Topic name:**  < Electrocardiography  >

**Short description:** < The monitoring method for measuring electrical activity in the heart.  >

**Parent URI(s):** < http://edamontology.org/topic_3300 >

**exactSynonym(s):** < EKG | ECG >

**narrowSynonym(s):** <>

**Wikipedia:** < https://en.wikipedia.org/wiki/Electrocardiography >

**Comment:** < Primarly intented for use in @bio-tools as a tool topic >

**Comment by drashti171299** [comment]
@matuskalas have you added this term? or is it pending?

**Comment by matuskalas** [comment]
Oops, I totally overlooked this, sorry everyone.

**Comment by matuskalas** [comment]
(A good small task for a newcomer, including Outreachy applicants!)

For a guide how to proceed, please read https://github.com/edamontology/edamontology/blob/main/CONTRIBUTING.md#how-to-add-a-new-concept. Please make sure to:
- Please put a second "Parent class" http://edamontology.org/topic_3382 (Imaging), in addition to topic_3300 (Physiology).
- Please make sure to add `Co-authored-by: Mads Kierkegaard <mads.k@live.dk>` after an empty line(!) to the bottom of the commit message when you **commit** these changes locally (not in the pull request(!)). **Important:** To make it possible, either commit without the `-m` option, or insert a second `-m "NEWLINE_WITHOUT_CLOSING_DOUBLE-QUOTES` and fill in the co-author there.

Million thanks! 🙏🏽

I have one question @Kigaard and everyone who might know, mostly for curiousity: Is ECG used also in scientific or pre-clinical research, or mostly just for clinical diagnostics? (To rephrase the question, are there tools in @bio-tools that deal with research data from ECG?)

**Comment by drashti171299** [comment]
Yes @matuskalas I would like to fix it :)

**Comment by drashti171299** [comment]
@matuskalas I have done this and already made a PR for this. Have look at that 😊.

**Comment by melibleq** [comment]
This issue was closed by https://github.com/edamontology/edamontology/pull/692.
