### ISSUE TITLE
Antimicrobial resistance

### ISSUE THREAD

**Issue by Kigaard** [edamontology/edamontology#610]
**Topic name:**  < Antimicrobial resistance >

**Short description:** < Microbial mechanisms for protecting microorganisms against antimicrobial agents>

**Parent URI(s):** < http://edamontology.org/topic_3301 >

**exactSynonym(s):** < AMR | AR >

**narrowSynonym(s):** < Antibiotic resistance | ABR >

**Wikipedia:** < https://en.wikipedia.org/wiki/Antimicrobial_resistance >

**Comment:** < Primarly intented for use in @bio-tools as a tool topic. Alternativly, a suggestion would be to add the topic name as a synonym to the parent >

**Comment by Anushka-shukla** [comment]
Hey, @matuskalas what has to be done in this issue. Is it like writing the content in the format specified above? Can you please assign this to me? What are exactSynonym and narrowSynonym can you please specify from where I can learn about these?
Thanks in advance! :)

**Comment by matuskalas** [comment]
(A good small task for a newcomer, including Outreachy applicants!)

For a guide how to proceed, please read https://github.com/edamontology/edamontology/blob/main/CONTRIBUTING.md#how-to-add-a-new-concept. Please make sure to:
- Not add the **comment**, that's just an information important in this issue.
- Please make sure to add `Co-authored-by: Mads Kierkegaard <40895049+Kigaard@users.noreply.github.com>` after an empty line(!) to the bottom of the commit message when you **commit** these changes locally (not in the pull request(!)). **Important:** To make it possible, either commit without the `-m` option, or insert a second `-m "NEWLINE_WITHOUT_CLOSING_DOUBLE-QUOTES` and fill in the co-author there.

Million thanks! 🙏🏽

**Comment by Kigaard** [comment]
I have made my "real" e-mail address public `mads.k@live.dk` which can be used instead of the Github-issued one.

Thanks :smiley:, and sorry for the inconvenience :sweat_smile:

**Comment by matuskalas** [comment]
Thank you @Kigaard🙏🏽 I replaced your no-reply GitHub email `40895049+Kigaard@users.noreply.github.com` with this one `mads.k@live.dk` in the [comment above](https://github.com/edamontology/edamontology/issues/610#issuecomment-827218734).

**Comment by AnkitaxPriya** [comment]
Hello @matuskalas, I'd like to work on this issue.

**Comment by matuskalas** [comment]
Awesome, thank you @AnkitaxPriya 🙏🏽

**Comment by AnkitaxPriya** [comment]
@matuskalas do I need to edit `<oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/edam#edam"/>` and  `<oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/edam#topics"/>`  as well? There are no information given as to what values/links must be added here. I have added the screenshot for your reference. 

Kindly also clear where must I add the co-author's details. 

![image](https://user-images.githubusercontent.com/44089458/117038296-1739ef00-ad25-11eb-95ed-2cd05be6acab.png)

**Comment by matuskalas** [comment]
> @matuskalas do I need to edit `<oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/edam#edam"/>` and `<oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/edam#topics"/>` as well? There are no information given as to what values/links must be added here. I have added the screenshot for your reference.

Just please leave it as in the template, both #edam and #topics. This is some historical obsolete stuff, but we keep it for now.

> Also, I didn't understand what value must I insert here `<created_in>(Please insert the 'doap:Version' value from the header of the file here, without "_dev". For example: 1.26)</created_in>`

1.26

> Should I leave `<oboInOwl:hasBroadSynonym>...</oboInOwl:hasBroadSynonym>` and `<oboInOwl:hasRelatedSynonym>...</oboInOwl:hasRelatedSynonym>` as it is or delete them since no values exist for them as of now?

Delete please if no values.

> Kindly also clear where must I add the co-author's details.

> - Please make sure to add `Co-authored-by: Mads Kierkegaard <mads.k@live.dk>` after an empty line(!) to the bottom of the commit message when you **commit** these changes locally (not in the pull request(!)). **Important:** To make it possible, either commit without the `-m` option, or insert a second `-m "NEWLINE_WITHOUT_CLOSING_DOUBLE-QUOTES` and fill in the co-author there.

> ![image](https://user-images.githubusercontent.com/44089458/117038296-1739ef00-ad25-11eb-95ed-2cd05be6acab.png)

Looks great! 👍🏽

- Please just remove the second topic_... and the whole rdfs:comment
- And the start and end spaces in the label & synonyms
- Instead of the `|` in synonyms, please make separate lines with corresponding XML elements for each of them

Many thanks! 🙏🏽
