### ISSUE TITLE
New format concept for PETab

### ISSUE THREAD

**Issue by jonrkarr** [edamontology/edamontology#611]
**Format name:**  PETab

**Short description:** A data format for specifying parameter estimation problems in systems biology

**Parent URI(s):** format_3475

**exactSynonym(s):** 

**Specification:** https://petab.readthedocs.io/en/stable/documentation_data_format.html

**Documentation:** https://petab.readthedocs.io/en/stable/

**Wikipedia:**

**Publication:** 10.1371/journal.pcbi.1008646

**Data represented:** data_3869

**File extension(s):** tsv

**Example(s):** https://petab.readthedocs.io/en/stable/example.html

**Information standard(s):** 

**Ontologies used:** 

**Governing organisation(s):** PETab editors

**Media type:** text/tab-separated-values

**Comment by matuskalas** [comment]
(A good small task for a newcomer, including Outreachy applicants!)

For a guide how to proceed, please read https://github.com/edamontology/edamontology/blob/main/CONTRIBUTING.md#how-to-add-a-new-concept. Please make sure to:
- Not add the file extension and media type, these are "inherited" from the "parent" super-concept.
- `documentation` should rather be the more specific link (**Specification**)
- `repository` should be https://github.com/PEtab-dev/PEtab
- I think we can skip the `organisation`, this one is not so formal, and the repository is more useful.
- Please make sure to add `Co-authored-by: Jonathan Karr <jonrkarr@gmail.com>` after an empty line(!) to the bottom of the commit message when you **commit** these changes locally (not in the pull request(!)). **Important:** To make it possible, either commit without the `-m` option, or insert a second `-m "NEWLINE_WITHOUT_CLOSING_DOUBLE-QUOTES` and fill in the co-author there.

Million thanks! 🙏🏽

**Comment by jonrkarr** [comment]
The group that manages it is the PE Tab editors -- the original developers plus a couple of others. The website for the "organization" and format are the same.

**Comment by matuskalas** [comment]
> The group that manages it is the PE Tab editors -- the original developers plus a couple of others. The website for the "organization" and format are the same.

Thanks for the clarification! I think in this case we don't need to record it additionally as `organisation` in EDAM. That attribute is mostly for the special cases of institutionalized standards organizations|consortia that govern a set of formats (like _e.g._ HUPO PSI).

**Comment by AnkitaxPriya** [comment]
Hi @matuskalas, I'd like to work on this issue.

**Comment by AnkitaxPriya** [comment]
I have already worked on issue #610, would you assign this task to me?
