### ISSUE TITLE
plain TEXT format missing

### ISSUE THREAD

**Issue by only1chunts** [edamontology/edamontology#63]
EDAM -> FORMAT -> DOCUMENT_FORMAT -> {PDF, DOCX, XLS, XLSX} 
but no TEXT/TXT option there?
Is it somewhere else, or was it not included for a reason? my use-case example would be readme.txt files, no specific format but everyone know the sort of information that should be in there.

**Comment by hmenager** [comment]
text format is here: http://edamontology.org/format_2330
