### ISSUE TITLE
<Genetic variation> topic should also have <Genomics> as parent class 

### ISSUE THREAD

**Issue by albangaignard** [edamontology/edamontology#632]
**Topic name:**  < Genetic Variation >

**Parent URI(s):** < Molecular Genetics >

This topic should also have as parent class < Genomics > 

(discussed with @abihouee)

**Comment by Lukong123** [comment]
Hello @matuskalas please I'll like to know more on this issue i hope to work on it

**Comment by Lukong123** [comment]
Hello @matuskalas I have sent a pull request but it seems to have some problems and i can't figure it out please can you help me?

**Comment by matuskalas** [comment]
Thanks for finding this missing link @albangaignard & @abihouee! And thanks @Lukong123 for adding it to EDAM! 🙏🏽
