### ISSUE TITLE
AGP format missing

### ISSUE THREAD

**Issue by only1chunts** [edamontology/edamontology#64]
I cannot find AGP format. its described here:
http://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/
Not sure where it would fit, but my first attempt to locate it was looking under the
SEQUENCE_ASSEMBLY_FORMAT section, but it might also belong in TEXTUAL_FORMAT section.

**Comment by matuskalas** [comment]
Thanks for the details!
