### ISSUE TITLE
Add post-commit hook (good as "my first Bash shell script" and/or "my first Git hook")

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#644]
Please add a `post-commit` file to the `.githooks` directory, which will (using a simple Bash shell script) inform the user with a nice 1-line message that the commit to EDAM was successful 😊

[A good small task for newcomers, e.g. Outreachy applicants. A good issue to do first before this: #616(setup)]

----

**Basic info about Git hooks:**
 - [Quick overview](https://coderefinery.github.io/git-collaborative/05-hooks/)
 - [Slightly more info](https://git-scm.com/book/it/v2/Customizing-Git-Git-Hooks)

**Learning Bash shell:**
- [Command line essentials for Bioinformaticians](https://bcc2020cle.bioinformatics.guide/) ([Slides here](https://rpubs.com/iracooke/bcc2020cle), [Video here](https://bcc2020.sched.com/event/c7Sz/command-line-essentials-for-bioinformaticians) or on [Vimeo](https://vimeo.com/441683367), Hands-on exercises linked from the first site)
- [Software Carpentry shell tutorial](http://swcarpentry.github.io/shell-novice/)

> **About Git and Git hooks:**
>  - Quick introduction|refresh of [Git and GitHub](https://coderefinery.github.io/git-refresher/02-refresher/) (101)
>  - Install Git: see [here](https://coderefinery.github.io/git-refresher/01-setup) and [here](https://carpentries.github.io/workshop-template/#git)
>  - Install a convenient [text editor](https://coderefinery.github.io/installation/editors/) ([see also](https://carpentries.github.io/workshop-template/#editor))
>  - [Learn Git](https://coderefinery.github.io/git-intro/) (great for both beginners and advanced)
>  - [Forking](https://coderefinery.github.io/git-collaborative/03-distributed/) a GitHub repository and creating a pull request

**Comment by AnkitaxPriya** [comment]
I would like to take up this @matuskalas

**Comment by AnkitaxPriya** [comment]
@matuskalas I am unable to see `post-commit.sample` here. How must I proceed? 

![image](https://user-images.githubusercontent.com/44089458/114494020-3ae3ab00-9c39-11eb-87f5-9801641415f4.png)

**Comment by Uttam-Singhh** [comment]
Hii @matuskalas I have also started working on this.

**Comment by AnkitaxPriya** [comment]
@matuskalas I have made a PR #652. Kindly review and let me know if any improvements are needed. Thank you.

**Comment by gloriaumutesi** [comment]
@matuskalas Hi! I am an Outreachy applicant and have passed the initial application. I would like to contribute to this project but Permission to edamontology/edamontology.git is denied. Would u grant me permission?

**Comment by AnkitaxPriya** [comment]
@matuskalas kindly check #658, I have made the necessary changes for my PR.
