### ISSUE TITLE
incorrect synonym for "Document format"

### ISSUE THREAD

**Issue by only1chunts** [edamontology/edamontology#65]
Item "edamontology.org/format_3507" is listed as "Document format" and has the synonyms "Microsoft Word Format" and "doc", which would be fine, but this item has 4 sub-classes of: docx, PDF, xls and xlsx, which cannot all be Word documents as well. I think removing mention of "Microsoft Word Format" and "doc" from the format_3507 item, and creating a new item as a subclass for it, or expanding the docx to also include doc format? (but they are very different formats so probably should be separate like xls and xlsx are).

**Comment by hmenager** [comment]
Yes it is. Thank you for reporting this.

**Comment by joncison** [comment]
"Document format" still  had "doc" synyonym - now removed
