### ISSUE TITLE
Proposing redesign of logo for EDAM Ontology

### ISSUE THREAD

**Issue by pooja2299** [edamontology/edamontology#651]
I would like to suggest an improved version of edam logo for edam-browser. I have tried to make one given below.

![image](https://user-images.githubusercontent.com/44069818/113519705-91067d80-95ab-11eb-8383-c90c09446963.png)

Need your feedback @matuskalas 
PS: this is the initial version of it. Changes and suggestions are welcomed.

**Comment by bryan-brancotte** [comment]
Hi @pooja2299,

Sorry for the delay, I think EDAM logo rework should be proposed within edamontology, not just for the edam-browser (afterall the browser is not EDAM, it is only using it).

**Comment by bryan-brancotte** [comment]
Proposition for reusing the logo have been made in https://github.com/edamontology/edam-browser/pull/106.

**Comment by pooja2299** [comment]
Thanks @bryan-brancotte for replying! I have changed the issue to proposing redesign of logo for edam ontology . So, can I work on designing the logo?

**Comment by pooja2299** [comment]
> Proposition for reusing the logo have been made in [edamontology/edam-browser#106](https://github.com/edamontology/edam-browser/pull/106).

Here, the existing logo has been used and linked to the edamontology.org website. 
But I would like to propose of a new design of logo which will look captivating and then linking it to edamontology.org.

**Comment by pooja2299** [comment]
Here's the sample of the logo and its link. 
![image](https://user-images.githubusercontent.com/44069818/114614273-f3553180-9cc1-11eb-8aa5-88a122d84b18.png)

PS : More improvements need to be done on logo . Posting just for sample.

**Comment by pooja2299** [comment]
Another design improvement for logo

![image](https://user-images.githubusercontent.com/44069818/115155719-c24c7680-a09e-11eb-9a32-21904f67384e.png)

**Comment by matuskalas** [comment]
Nice proposals, highly appreciated! 🙌🏽

I created a new repo for collecting all the proposals of a logo _etc._. Please fork https://github.com/edamontology/logoi, add file(s) with your suggestion(s), and create PR(s). Million thanks!! 🙏🏽

**Comment by rioualen** [comment]
Seeing as there is a dedicated repository, I will close this issue for now. Thank you all for contributing!
