### ISSUE TITLE
Update NCBO BioPortal links to include ?p=classes

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#665]
I think it'll be great to update most of the links to browsing EDAM in the NCBO BioPortal from https://bioportal.bioontology.org/ontologies/EDAM to https://bioportal.bioontology.org/ontologies/EDAM?p=classes. In most of the places, it makes sense to point to **browsing** (_i.e._ the "Classes" tab, `?p=classes`), instead of the default "Summary" tab.

Way forward: Search for all links to https://bioportal.bioontology.org, and update everywhere where it'll be better with the "Classes" tab.

(A good short mini-task for newcomers! 😉 incl. Outreachy applicants)

**Comment by AnkitaxPriya** [comment]
Hello @matuskalas is this issue still open? I'd like to work on this.

**Comment by drashti171299** [comment]
@matuskalas  I would like to contribute on this issue.

**Comment by matuskalas** [comment]
Awesome, please check it out👍🏽

**Comment by drashti171299** [comment]
Hey @matuskalas  I want to know that from where I can get the source code to edit or I can directly use this repository code.
Also specify which file do I need to edit

**Comment by drashti171299** [comment]
I have searched in this repository but it is showing in READ.md file only

**Comment by matuskalas** [comment]
@drashti171299 please search for _e.g._ `bioportal.bioontology.org` in the GitHub search box up left (the default option 'In this repository'). I can see that there are 2 hits in README which could be fixed.

**Comment by drashti171299** [comment]
I have fixed it @matuskalas
