### ISSUE TITLE
Identifiers used as input to QuickGO

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#67]
There are canonical and taxon-specific forms of RNAcentral ID.
Canonical form e.g. urs_9or10digits identifies an RNA sequence (within the RNA central database) which may appear in multiple sequences

Taxon-specific form identifies a sequence in the specific taxon (e.g. urs_9or10digits_taxonID)

QuicKGO uses the taxon-specific one

**Comment by joncison** [comment]
We may need a parent term "RNA sequence identifier" or some such for thisone

**Comment by veitveit** [comment]
There might be only very few children of this term
Either broaden definition "RNA family identifier" or use "Sequence identifier" as parent?

**Comment by joncison** [comment]
Agree ... just put _RNAcentral id_ as childOf (more broadly defined) _RNA family identifier_

@matuskalas : do you agree?

**Comment by joncison** [comment]
It's now just a child of *Sequence accession (nucleic acid)* because they're identify individual sequences not really families per se, so far as I can tell.
