### ISSUE TITLE
Cryogenic electron microscopy

### ISSUE THREAD

**Issue by Kigaard** [edamontology/edamontology#687]
**Topic name:**  < Cryogenic electron microscopy >

**Short description:** < A method for studying biomolecules and other structures at very low (cryogenic) temperature using electron microscopy. >

**Parent URI(s):** < http://edamontology.org/topic_0611 >

**exactSynonym(s):** < cryo-EM >

**narrowSynonym(s):** < >

**Wikipedia:** < https://en.wikipedia.org/wiki/Cryogenic_electron_microscopy >

**Comment:** <  Primarly intented for use in @bio-tools as a tool topic. It might make sence to add term and synonyms as a narrow synonyms to the parent  (Electron microscopy)>

**Comment by matuskalas** [comment]
Thank you @Kigaard for this addition! This is indeed better than what we have so far in EDAM-bioimaging, so let's add it to mainstream EDAM first (then it's also soon usable in @bio-tools). And let's improve this & related concepts in EDAM-bioimaging later.

(A good small task for a newcomer, including Outreachy applicants!)

For a guide how to proceed, please read https://github.com/edamontology/edamontology/blob/main/CONTRIBUTING.md#how-to-add-a-new-concept. Please make sure to:
- Not add the **comment**, that's just an information important in this issue.
- Please make sure to add `Co-authored-by: Mads Kierkegaard <mads.k@live.dk>` after an empty line(!) to the bottom of the commit message when you **commit** these changes locally (not in the pull request(!)). **Important:** To make it possible, either commit without the `-m` option, or insert a second `-m "NEWLINE_WITHOUT_CLOSING_DOUBLE-QUOTES` and fill in the co-author there.

Million thanks! 🙏🏽

**Comment by drashti171299** [comment]
I would like to take initiative and add this to the content.

**Comment by matuskalas** [comment]
Awesome, thank you @drashti171299! 😊
