### ISSUE TITLE
Valuable data about identifiers for inclusion in EDAM

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#69]
here is metadata for databases and identifiers known to GO:
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

It was generated from an old file called GO.xrf_abbs, and has subsequently revised manually.

To use it, better to periodically update from it (rather than treat it as a fossil) - discuss this with @tonysawfordebi (Tony Sawford at EBI) more

**Comment by joncison** [comment]
This is a critical production file so we can reliably use it as a source of uptodate information (need script to make the handhshake)

**Comment by tonysawfordebi** [comment]
Also available in JSON format from:
https://s3.amazonaws.com/go-public/metadata/db-xrefs.json

**Comment by joncison** [comment]
Excellent ... @tonysawfordebi, will you please remind me: is the file auto-generated, or is it (at least partially) hand-edited?

**Comment by tonysawfordebi** [comment]
The YAML file is maintained by hand - the original version was created automatically from the file that it supersedes, but ongoing maintenance is manual.

The JSON version of the file is created automatically from the YAML.

**Comment by joncison** [comment]
@tonysawfordebi - so at this stage, two obvious things to look at:

1. "type" the example_id by annotating with EDAM Data->Identifier concepts, e.g. "Ensembl gene ID" (http://edamontology.org/data_1033).  that could be useful for users, and would also help ...
2. Automatically pulling into EDAM values from id_syntax and example_id

What do you think?

What is type_name ?
What is type_id?

There could also be scope for exposing in bio.tools information from here (for the database, and data access URLs, see separate thread:
https://github.com/bio-tools/biotoolsregistry/issues/17

**Comment by tonysawfordebi** [comment]
type_name and type_id go together and are used to specify what kind of a thing an identifier from a database represents (gene, protein, sequence feature, etc) - so they're like the EDAM concepts Data->Identifier concepts, but not tied to a specific database.

The set of types that is currently used in db-xrefs.yaml (and a number of other files, for example https://github.com/geneontology/go-site/blob/master/metadata/eco-usage-constraints.yaml) is defined in http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/experimental/upper/go-upper.obo.

One thing to bear in mind is that db-xrefs.yaml does not claim to be an exhaustive list of all databases & the identifier types that they mint; it merely lists those that are somehow relevant to GO.

**Comment by joncison** [comment]
So if I understand right these define the biological entity / phenomena.  We could contemplate annotating type with EDAM Data concepts e.g. "Protein report" (http://edamontology.org/data_0896).  One can argue that is a report about some protein that is identified, rather than the protein per se.  But then we could still have the Data->Identifier annotation on the identifiers e.g. "Ensembl gene ID" (http://edamontology.org/data_1033) and "NCBI gene ID" (http://edamontology.org/data_1027) both identify some "Gene report" (http://edamontology.org/data_0916).

Out of interest, @tonysawfordebi, do you have plans (or would you be amenable to others) to extend to db-xrefs.yaml, possibly with more databases and identifiers, and possibly with EDAM annotations?

I fully understand it's a mission-critical file and all the implications of that!

**Comment by tonysawfordebi** [comment]
There are currently no plans to extend the set of attributes / annotations in db-xrefs.yaml (at least, none that I'm aware of), but there are no reasons why it couldn't be, and, personally, I wouldn't have any problem with it including EDAM annotations.

Adding new databases to the file is something that will inevitably happen on an ad-hoc basis.

**Comment by joncison** [comment]
OK, excellent.  Then I'll discuss this more other folk working in this area and get back on this thread - thanks!

**Comment by jmcmurry** [comment]
Given that:
* Most of the records in the GO xref file are annotated to Entity (BET:0000000). 
* Remaining records are annotated either to protein (PR:000000001) or to gene (SO:0000704). 

Jon, are you proposing:
* Manual curation of those that remain Entity (BET:0000000) to more specific EDAM terms?
* Changing protein (PR:000000001) and gene (SO:0000704) to their EDAM equivalents?
* Something else?

As a side note, I think SO and PR terms are sensible as these are authoritative sources in their respective domains. Could Edam not simply import such pre-existing terms rather than minting new ones? Perhaps this is already happening? Pardon being out of the loop and thanks for explaining.

cc: @cmungall

**Comment by joncison** [comment]
I'm not (yet) proposing anything - depends on what folk agree is most useful / practical.  

I can see value in annotating types of identifier e.g. "Ensembl gene ID" (http://edamontology.org/data_1033).  As for data itself, the (annotation of) the entity/phenomena (PR:*, SO:*), the report on such (EDAM:data_*), or both, could be useful in different scenarios. 

EDAM no longer includes much biology at all under the Report concept (http://edamontology.org/data_2048) - just the prevalent, common types of reports out there (at least that's the idea).   e.g. we have "Gene transcript report" (http://edamontology.org/data_3134) but one would need SO for finer-grained annotation of features.

**Comment by veitveit** [comment]
This discussion is quite old and looks more like an issue for enhancement in https://github.com/geneontology/go-site/ (if there is interest). 

@joncison @hansioan The yaml file provides details about databases suitable to add/update them to bio.tools. You might want to check how well they are covered in bio.tools

Issue closed for now
