### ISSUE TITLE
File handling is not an "Analysis" operation

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#71]

**Comment by hmenager** [comment]
Currently operation 2409 (File handling) is a subclass of analysis: obviously a mistake, since even its definition says "Basic (non-analytical) operations of some data, either a file or equivalent entity in memory.". Should it be a direct subclass of "Operation", or something more fine-grained?

**Comment by joncison** [comment]
Now child of Operation (http://edamontology.org/operation_0004)
