### ISSUE TITLE
Wrong release version in EDAM_1.24.owl ?

### ISSUE THREAD

**Issue by bryan-brancotte** [edamontology/edamontology#723]
Hi, when opening the https://raw.githubusercontent.com/edamontology/edamontology/main/releases/EDAM_1.24.owl I found out that
```
        <doap:Version rdf:datatype="http://www.w3.org/2001/XMLSchema#decimal">1.25</doap:Version>
```

Should the version number be changed in EDAM_1.24 ? Or is the problem more important

**Comment by matuskalas** [comment]
Fixed.
TODO: Update on website.
TODO: Check the whole 1.24, it looks being plagued with all sorts of problems 🤔
