### ISSUE TITLE
Problem with Genome resequencing (operation_3923)

### ISSUE THREAD

**Issue by Kigaard** [edamontology/edamontology#726]
Operation Genome sequencing (http://edamontology.org/operation_3923) is subclass of topic Sequencing (http://edamontology.org/topic_3168).

**Comment by Kigaard** [comment]
Hi @matuskalas 😄 Just small reminder about a bug, so it may be part of release 1.26 😃 I don't know the exact release schedule

**Comment by Kigaard** [comment]
Work continued in #775.

**Comment by matuskalas** [comment]
This was fixed in 1028c944. Genome resequencing is since a topic (http://edamontology.org/topic_3923). This change wasn't yet part of the major release 1.25, but released in the following minor releases.

Sorry for the messy issues, this was closed without explanation.
