### ISSUE TITLE
Microfluidics

### ISSUE THREAD

**Issue by Kigaard** [edamontology/edamontology#743]
**Topic name:**  < Microfluidics >

**Short description:** < Interdisplinary study of behavior, precise control, and manipulation of low (microlitre) volume fluids in constrained space.  >

**Parent URI(s):** <http://edamontology.org/topic_3318 >

**exactSynonym(s):** < >

**narrowSynonym(s):** < Fluidics >

**Wikipedia:** < https://en.wikipedia.org/wiki/Microfluidics >

**Comment:** < The topic is a intradisiplinary topic with many possible parents: Physics (Only one chosen), Chemistry (http://edamontology.org/topic_3314), Biochemistry (http://edamontology.org/topic_3292), and Biotechnology (http://edamontology.org/topic_3297) >

**Comment by matuskalas** [comment]
Sounds great👍🏽

Do you know about some concrete cases of usage within life sciences? Or even among tools? I'm just curious 😊

**Comment by Kigaard** [comment]
It is used in the single-cell sequencing, where the cells are immersed in droplets prior to further analysis. There is also a whole research field involving lab/organs-on-a-chip. But I am not an expert in microfluidics 😅
