### ISSUE TITLE
Weird behavior in BioPortal for parsing of comment and Definition

### ISSUE THREAD

**Issue by hmenager** [edamontology/edamontology#75]
When parsing http://edamontology.org/format_3244 in BioPortal, the comment is concatenated to the definition. See source below, and compare with BioPortal "definition" field. I think this is not an EDAM problem, but this is a reminder to ask BioPortal people.

    <owl:Class rdf:about="http://edamontology.org/format_3244">
        <rdfs:label>mzML</rdfs:label>
        <rdfs:subClassOf rdf:resource="http://edamontology.org/format_2332"/>
        <rdfs:subClassOf rdf:resource="http://edamontology.org/format_3245"/>
        <rdfs:comment>mzML is the successor and unifier of the mzData format developed by PSI and mzXML developed at the Seattle Proteome Center.</rdfs:comment>
        <created_in>1.2</created_in>
        <oboInOwl:hasDefinition>mzML format for raw spectrometer output data, standardised by HUPO PSI MSS.</oboInOwl:hasDefinition>
        <documentation rdf:resource="http://psidev.info/mzml"/>
        <oboInOwl:hasDbXref rdf:resource="http://psidev.info/mzml"/>
        <oboInOwl:inSubset rdf:resource="&oboOther;edam#edam"/>
        <oboInOwl:inSubset rdf:resource="&oboOther;edam#formats"/>
    </owl:Class>

**Comment by joncison** [comment]
@hmenager : please take it up with them by mailing support@bioontology.org

**Comment by hmenager** [comment]
support has been mailed. EDAM-core is CCed.

**Comment by joncison** [comment]
If this ever was a bug, it's fixed now.  NB:  BioPortal uses "Definitions" which includes comment: and definition: (a bit confusing).
