### ISSUE TITLE
rdfs:comment with non-literal value

### ISSUE THREAD

**Issue by cmungall** [edamontology/edamontology#751]
EDAM.owl has:

```xml
 <!-- http://edamontology.org/operation_2519 -->

    <owl:Class rdf:about="http://edamontology.org/operation_2519">
        <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/owl#DeprecatedClass"/>
        <created_in>beta12orEarlier</created_in>
        <obsolete_since>1.6</obsolete_since>
        <oboInOwl:hasDefinition>Process (read and / or write) nucleic acid tertiary structure data.</oboInOwl:hasDefinition>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/edam#obsolete"/>
        <oboInOwl:replacedBy rdf:resource="http://edamontology.org/operation_2480"/>
        <rdfs:comment rdf:resource="http://edamontology.org/operation_2481"/>
        <rdfs:label>Structure processing (nucleic acid)</rdfs:label>
        <owl:deprecated>true</owl:deprecated>
    </owl:Class>
    
```

While this is valid OWL, it is convention in both OBO and most other ontologies to only have literal values from comments, I assume this is a mistake. You already have the replacedBy triple.

This is how it looks in OLS:

![image](https://user-images.githubusercontent.com/50745/131583824-d2ecb044-90c0-4f8b-8bbe-35d21fad3593.png)

**Comment by matuskalas** [comment]
This is obviously a bug, thank you very much for reporting @cmungall 🙏🏽

**Comment by matuskalas** [comment]
This is now fixed, many thanks again for finding it @hrshdhgd @cmungall

Is this such a showstopper for your workflow that you'd prefer us patching it in the (otherwise) stable release at https://edamontology.org/EDAM.owl?

Possibly related to this, there are some `oboInOwl:...Synonym`-s with a non-literal value in EDAM. Do those work fine in your tooling?
