### ISSUE TITLE
[Edam Browser User] Change proposition for http://edamontology.org/topic_3974

### ISSUE THREAD

**Issue by vbaillet** [edamontology/edamontology#769]
[//]: # (You can add comment regarding your issue hereafter)
### Comments
- definition was incorrect (definition of epigenomics), substituted by current comment entry which is a more correct def of epistasis
- suppr parent term Genomics (not an Omics concept), sub parent term Epigenetics by Genetics (higher order parent term, epistatis not a subfield of epigenetics)

[//]: # (End of issue comments)
### Hereafter are the initial version and proposed modification of attributes of the given term

| key | value |
| --- | --- |
| Attr  | **definition** |
| Old | The study of the epigenetic modifications of a whole cell, tissue, organism etc. |
| New | The study of the phenomena whereby the effects of one locus mask the allelic effects of another, such as how dominant alleles mask the effects of the recessive alleles at the same locus. |
|  |  |

| key | value |
| --- | --- |
| Attr  | **parent-0** |
| Old | http://edamontology.org/topic_3295 |
| New | http://edamontology.org/topic_3053 |
|  |  |

**Comment by matuskalas** [comment]
Many thanks indeed @vbaillet! 🙏🏽

This was a copy&paste bug 🐛

We have now suggested a simpler and more generic definition with @LucieLamothe, inspired by the definition in MASH: http://purl.bioontology.org/ontology/MSH/D004843
Please review whether you think it's acceptable, or whether it needs to be made more specific.
We had a feeling that the both the definition based on the article mentioned in #557 by @sduvaud and the one in the [Wikipedia page](https://en.wikipedia.org/wiki/Epistasis) look specific only to the genetic variation case, whereas the one in MASH is generic and covering any interference, for example masking, and for example allelic.
What is right? 🤔
Please see the changes to be reviewed here: https://github.com/edamontology/edamontology/pull/771/files (It should be possible to click on the green button on the right 'Review changes').
