### ISSUE TITLE
Standardize use of "notRecommendedForAnnotation"-property

### ISSUE THREAD

**Issue by Kigaard** [edamontology/edamontology#778]
The use of `notRecommendedForAnnotation` property does not seem to be used consistently throughout the ontology.
The property is missing for terms, which could be used (The property should be added, mostly for easing automation of reading). However, a more pressing issue is the terms, where it clearly should have `notRecommendedForAnnotation`set to `false` - For example [Text data](http://edamontology.org/data_2526) (See Definitions).

**Comment by rioualen** [comment]
I'm moving this to a discussion #892 and closing the issue.
