### ISSUE TITLE
New operation "Mass spectrum visualization"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#78]
Description: "Graphical visualization of a mass spectrum"
Parent: http://edamontology.org/operation_0004

Resulting from mapping tools from ms-utils.org

**Comment by joncison** [comment]
Created in EDAM_1.13 (pending release):

Mass spectrum visualisation
http://edamontology.org/operation_3694

child of Visualisation (http://edamontology.org/operation_0337)
