### ISSUE TITLE
[Edam Browser User] Change proposition for http://edamontology.org/operation_0256

### ISSUE THREAD

**Issue by vedran-kasalica** [edamontology/edamontology#780]
[//]: # (You can add comment regarding your issue hereafter)
### Comments
The operation has 2 different terms as expected inputs. Should be looked into.

[//]: # (End of issue comments)
### Hereafter are the initial version and proposed modification of attributes of the given term

| key | value |
| --- | --- |
| Attr  | **has_input-0** |
| Old | http://edamontology.org/data_0849 |
| New | http://edamontology.org/data_1255 |
|  |  |

**Comment by matuskalas** [comment]
Thanks again @vedran-kasalica for spotting this🙏🏽 Indeed, it should only be `data_1255`. Do you want to fix it in the OWL file yourself & issue a pull request?

**Comment by vedran-kasalica** [comment]
Hi @matuskalas, thanks for he clarification! Sure I will make a pull request as soon as I have some free time!

**Comment by matuskalas** [comment]
Awesome, thanks so much @vedran-kasalica!

**Comment by vedran-kasalica** [comment]
Hi @matuskalas, I have updated the ontology. In addition, I had a bit of time and I looked into the ontology and noticed 4 similar cases, namely:

|  Operation |  has_input  |
| :------------: | :------------: |
|   http://edamontology.org/operation_0297 | http://edamontology.org/data_0886,	http://edamontology.org/data_0883 |
|   http://edamontology.org/operation_0286 | http://edamontology.org/data_2977,	http://edamontology.org/data_1597 |

|  Operation |  has_output  |
| :------------: | :------------: |
| http://edamontology.org/operation_0478 | http://edamontology.org/data_1461,	http://edamontology.org/data_2877 |
| http://edamontology.org/operation_0286 | http://edamontology.org/data_0914,	http://edamontology.org/data_1597 |

Should I create another issue to address that?
