### ISSUE TITLE
Duplicate definition

### ISSUE THREAD

**Issue by LucieLamothe** [edamontology/edamontology#782]
35 concepts (see bellow) seems to have the diplicated definitions. The were identified by the robot report duplicate definition query (slightly altered).
They need to be specified.

http://edamontology.org/format_2183 | XML format for EMBL entries.
http://edamontology.org/format_2184 | XML format for EMBL entries.
http://edamontology.org/format_2185 | XML format for EMBL entries.
http://edamontology.org/topic_3173 | The study of the epigenetic modifications of a whole cell, tissue, organism etc.
http://edamontology.org/topic_3974 | The study of the epigenetic modifications of a whole cell, tissue, organism etc.
http://edamontology.org/data_2316 | The name of a cell line.
http://edamontology.org/data_2317 | The name of a cell line.
http://edamontology.org/data_2318 | The name of a cell line.
http://edamontology.org/data_2319 | The name of a cell line.
http://edamontology.org/data_2320 | The name of a cell line.
http://edamontology.org/format_3281 | The A2M format is used as the primary format for multiple alignments of protein or nucleic-acid sequences in the SAM suite of tools. It is a small modification of FASTA format for sequences and is compatible with most tools that read FASTA.
http://edamontology.org/format_3811 | The A2M format is used as the primary format for multiple alignments of protein or nucleic-acid sequences in the SAM suite of tools. It is a small modification of FASTA format for sequences and is compatible with most tools that read FASTA.
http://edamontology.org/data_2752 | Identifier of an entry from the GlycosciencesDB database.
http://edamontology.org/data_2796 | Identifier of an entry from the GlycosciencesDB database.
http://edamontology.org/data_2379 | Identifier of a strain of an organism variant, typically a plant, virus or bacterium.
http://edamontology.org/data_2912 | Identifier of a strain of an organism variant, typically a plant, virus or bacterium.
http://edamontology.org/format_3975 | Graphical Fragment Assembly captures sequence graphs as the product of an assembly, a representation of variation in genomes, splice graphs in genes, or even overlap between reads from long-read sequencing technology.
http://edamontology.org/format_3976 | Graphical Fragment Assembly captures sequence graphs as the product of an assembly, a representation of variation in genomes, splice graphs in genes, or even overlap between reads from long-read sequencing technology.
http://edamontology.org/format_1996 | EMBOSS simple sequence pair alignment format.
http://edamontology.org/format_3330 | EMBOSS simple sequence pair alignment format.
http://edamontology.org/operation_0450 | Detects chimeric sequences (chimeras) from a sequence alignment.
http://edamontology.org/operation_3918 | Detects chimeric sequences (chimeras) from a sequence alignment.
http://edamontology.org/format_1919 | Data format for a molecular sequence record.
http://edamontology.org/format_2551 | Data format for a molecular sequence record.
http://edamontology.org/format_2552 | Data format for a molecular sequence record.
http://edamontology.org/data_2101 | An identifier of a software end-user (typically a person).
http://edamontology.org/data_2118 | An identifier of a software end-user (typically a person).
http://edamontology.org/data_2749 | An identifier of a particular genome.
http://edamontology.org/data_2751 | An identifier of a particular genome.
http://edamontology.org/data_2785 | An accession of annotation on a (group of) viruses (catalogued in a database).
http://edamontology.org/data_2913 | An accession of annotation on a (group of) viruses (catalogued in a database).
http://edamontology.org/data_1141 | Accession number of an entry (family) from the TIGRFam database.
http://edamontology.org/data_2731 | Accession number of an entry (family) from the TIGRFam database.
http://edamontology.org/data_2531 | A human-readable collection of information about about how a scientific experiment or analysis was carried out that results in a specific set of data or results used for further analysis or to test a specific hypothesis.
http://edamontology.org/data_3914 | A human-readable collection of information about about how a scientific experiment or analysis was carried out that results in a specific set of data or results used for further analysis or to test a specific hypothesis.

**Comment by matuskalas** [comment]
Oh wow! 😱🐛 This is a major finding 🙀
