### ISSUE TITLE
Topics in EDAM

### ISSUE THREAD

**Issue by jamesmalone** [edamontology/edamontology#8]
The list of topics in EDAM has grown and continues to do so. It's out of scope (prob) for SWO which imports EDAM - I don't know how much this even in scope for EDAM really. Can I suggest for these reasons, and to facilitate the import of software relevant parts into SWO, topics becomes it's own entity with a separate file which can then import EDAM if you want to see the full thing? This would also mean topics can be reused outside of EDAM for people not interested in software of course.

**Comment by joncison** [comment]
Closing this for now - may resurrect if requested again
