### ISSUE TITLE
Request for msutils.org (3 operations)

### ISSUE THREAD

**Issue by joncison** [edamontology/edamontology#80]
Chromatogram visualisation
http://edamontology.org/operation_3203	
child of http://edamontology.org/operation_0004	
Relate more to mass spectrometry, retention time? There are several types of chromatograms (children). These include XIC/EIC/SIC (eXtracted, Extracted or Selected Ion Chromatograms, all synonymous) and TIC (Total Ion Chromatogram), but also fluoresence, UV/Vis absorbtion and electrochemical detection, and FID for GC. The units and linear ranges are very different, so they should be separate concepts. Do we use US or UK spelling (visualization or visualisation)?

Protein fragment weight comparison	
Change to: Calculate the molecular weight of a protein (or fragments) and compare it another protein or reference data. Generally used for protein identification in mass spectra	http://edamontology.org/operation_2929		
Comment: Change definition and add synonym

Spectral library search	Determination of best matches between a (tandem) mass spectrum and a database of spectra		
child of http://edamontology.org/operation_3646	
Difficult to find the right parent. Mayb too general name?	
Synonym: Spectral library search of peptides

**Comment by krdav** [comment]
Also add "Mascot Generic Format":
http://www.matrixscience.com/help/data_file_help.html#GEN

**Comment by joncison** [comment]
@veitveit : ditto this one, closing because I think it duplicates your individual issues.  Please create new issues as necessary, if something will be lost
