### ISSUE TITLE
Exact synonym duplicate

### ISSUE THREAD

**Issue by LucieLamothe** [edamontology/edamontology#815]
Robot test duplicate_exact_synonym raised some error (not run before, mistake on my behalf, I skipped it) raised 4 duplicates:

WARN    duplicate_exact_synonym http://edamontology.org/data_2044       oboInOwl:hasExactSynonym        Sequences
WARN    duplicate_exact_synonym http://edamontology.org/topic_0080      oboInOwl:hasExactSynonym        Sequences
WARN    duplicate_exact_synonym http://edamontology.org/data_0881       oboInOwl:hasExactSynonym        Secondary structure alignment (RNA)
WARN    duplicate_exact_synonym http://edamontology.org/operation_0502  oboInOwl:hasExactSynonym        Secondary structure alignment (RNA)
WARN    duplicate_exact_synonym http://edamontology.org/data_3134       oboInOwl:hasExactSynonym        mRNA features
WARN    duplicate_exact_synonym http://edamontology.org/topic_3512      oboInOwl:hasExactSynonym        mRNA features
WARN    duplicate_exact_synonym http://edamontology.org/data_0857       oboInOwl:hasExactSynonym
WARN    duplicate_exact_synonym http://edamontology.org/operation_3904  oboInOwl:hasExactSynonym

**Comment by LucieLamothe** [comment]
The last error is making me think that we should check for empty property in concept annotation.

**Comment by LucieLamothe** [comment]
For the  Secondary structure alignment (RNA), after all does it make sense to check for duplicate exact synonym when we are voluntarily not checking duplicate labels (because of similar concept just in different subset)

**Comment by matuskalas** [comment]
Fixed to the level applicable now. PR #816 

The problems stays there in cases of label duplication between different sub-ontologies.
