### ISSUE TITLE
missing terms

### ISSUE THREAD

**Issue by lorenzr** [edamontology/edamontology#83]
I attached some terms that I am missing to describe our data output.
[EDAM_BacDive_extension.xlsx](https://github.com/edamontology/edamontology/files/113662/EDAM_BacDive_extension.xlsx)

Mostly experimental data.

**Comment by joncison** [comment]
These concepts added in EDAM_1.14:
"Biosafety report"
http://edamontology.org/data_3716

"Biosafety classification"
http://edamontology.org/data_3719

Done in EDAM_1.14:

"Pathogenicity report"
http://edamontology.org/data_3718

"Isolation source"
http://edamontology.org/data_3721

"Geographic location"
http://edamontology.org/data_3720

"GC-content" added as "narrow synonym" of "Nucleic acid property" (http://edamontology.org/data_0912)

"Cultivation parameter"
http://edamontology.org/data_3724

"Morphology parameter"
http://edamontology.org/data_3723

"Physiology parameter"
http://edamontology.org/data_3722
