### ISSUE TITLE
incorrect position of the term 'OWL format' (format_2197) in the hierarchy 

### ISSUE THREAD

**Issue by annazhukova** [edamontology/edamontology#84]
Currently 'OWL format' is a subClass of 'XML' which is only true for some (but not all) of its child terms. For instance, 'OWL/XML' is an 'XML' format, while 'Manchester OWL Syntax' is not.

**Comment by hmenager** [comment]
Thank you so much for reporting this. I corrected the ontology, this correction will be part of the next release (tomorrow hopefully).

**Comment by annazhukova** [comment]
Thank you.
