### ISSUE TITLE
Operation "Read Pre-Processing" vs the rest

### ISSUE THREAD

**Issue by smoe** [edamontology/edamontology#86]
Hello,

the term pre-processing is used a lot, especially by those who do not really understand what is going on underneath. The SeqWiki folks use it to gather a range of activities in the interface from receiving raw data and the start of the analysis: https://en.wikibooks.org/wiki/Next_Generation_Sequencing_%28NGS%29/Pre-processing

The ontology in 1.22 has it like

    Read quality control
      ->  Pre-processing
      ->  Variant filtering

which kind of mixes it all up. Please investigate.

Cheers,

Steffen

**Comment by smoe** [comment]
Sorry for this spam, please involve
   http://www.ebi.ac.uk/ols/beta/ontologies/edam/terms?iri=http%3A%2F%2Fedamontology.org%2Foperation_3192
which is sequence trimming that is a child of sequence editing (nice!) but also somehow commonly understood of this pre-processing thingy. It is not part of sequence analysis, though, a link I would prefer to see cut.

**Comment by matuskalas** [comment]
Thanks @smoe 
Did you mean EDAM 1.12?

I'd suggest:

- renaming "Editing" to "Processing" or "Data processing", or maybe "Data handling" (with synonyms). This would be the operation that consumes data and outputs the SAME DATA, just somewhat processed/filtered/improved/cleaned/converted...
- note: whether such an operation is used as pre-processing, post-processing, or core-processing, is specific to a concrete workflow and shouldn't be a concern of EDAM
- removing synonym "Processing" from "Analysis"
- clean up the definitions of both to clarify the distinction
- move under "Processing" whatever fits there, from wherever

**Comment by smoe** [comment]
Hm. I like the term "Editing", though. It has a human touch to it that "processing" loses. I tend to agree that pre/post is not necessarily useful in all kinds of workflows, but once you give it all a topic, it is rather interesting to know if that close to the machine output (pre-procesing) or close to the rewarding end of it all (post-processing), and after all it helps to identify the tools to select for some workflow.

**Comment by joncison** [comment]
A step in the right direction in EDAM_1.14:
"Data handling"
http://edamontology.org/operation_2409

"Editing" is simply moved under "Data handling"

See also comment on "Analysis" (http://edamontology.org/operation_2945)

@matuskalas @smoe  : we could go further by making the "Sequence *" concepts under "Sequence editing" generic, e.g. "Sequence masking" -> "Masking", "Sequence conversion" -> "Conversion" etc.  I'm not sure if this gives us more conciseness / generality - or creates confusion :)  Open a new ticket please if you think we should do this.
