### ISSUE TITLE
New format: MSP

### ISSUE THREAD

**Issue by xtrojak** [edamontology/edamontology#864]
**Format name:** MSP

**Short description:** NIST Text file format for storing MS/MS spectra (m/z and intensity of mass peaks) along with additional annotations for each spectrum. A single MSP file can thus contain single or multiple spectra. This format is frequently used to share spectra libraries.

**Parent URI(s):** http://edamontology.org/format_3245|http://edamontology.org/format_2330

**Is Format Of:** 

**exactSynonym(s):** NIST Spectra format

**Specification:** https://chemdata.nist.gov/mass-spc/ms-search/docs/Ver20Man_11.pdf

**Documentation:** https://bioconductor.org/packages/release/bioc/vignettes/MsBackendMsp/inst/doc/MsBackendMsp.html

**Wikipedia:** 

**Publication:** 

**Data represented:** http://edamontology.org/data_0943

**File extension(s):** msp

**Example(s):** https://zenodo.org/record/4471217/files/RECETOX_GC-EI_MS_20201028.msp

**Information standard(s):** 

**Ontologies used:**

**Governing organisation(s):** https://chemdata.nist.gov/

**Media type:**

**Comment:** The specification is in the PDF in section "NIST Text Format of Individual Spectra" on page 47. I don't know whether there is a way how to specify this.

**Comment by hechth** [comment]
thanks @matuskalas
