### ISSUE TITLE
owl:versionIRI for .owl files

### ISSUE THREAD

**Issue by vtoure** [edamontology/edamontology#870]
Hi, 

Currently EDAM has in the .owl file provided the version included as a `doap:Version`. 

Are you considering (and) would it be possible for upcoming releases of the RDF versions of EDAM to provide an `owl:versionIRI`?

This is usually a common predicate (and [header information in Protege](http://protegeproject.github.io/protege/views/ontology-header/#:~:text=The%20version%20IRI%20should%20describe,published%20at%20its%20Ontology%20IRI)) for indicating the version of an ontology. Also recommended (requested even) by the OBO Foundry for example.

In our case, this would facilitate the integration of EDAM into our project.

Thanks!

**Comment by matuskalas** [comment]
Hi hi, million thanks for the heads up, and a big sorry for the delayed reaction! 🙏🏽🙇🏽‍♂️

We can definitely fix this 👍🏽

Just some notes, mostly to myself:

- [ ] For the "stable" releases, this is straightforward.

- [ ] If we want also the "unstable" releases to have a "stable" versionIRI, that would even be resolvable, we can tag them with something like _e.g._ `unstable(1.26)20240920-1155`, and then let http://edamontology.org/EDAM_unstable(1.26)20240920-1155 resolve to something like [raw.githubusercontent.com/edamontology/edamontology/e4e0/EDAM_dev.owl](https://edamontology.github.io/edam-browser/#version=https://raw.githubusercontent.com/edamontology/edamontology/e4e0/EDAM_dev.owl), even with the visual browser if HTML requested.

**Comment by matuskalas** [comment]
I added the versionIRI in PR #899, please review whether this will solve your use case @vtoure @deepakunni3 @cthoyt.

This can be merged very soon, but it'll only be useful after the next (minor/'unstable') release, which will hopefully happen in the very next days.
