### ISSUE TITLE
Suggestion: define acronym on mainpage

### ISSUE THREAD

**Issue by incoherentian** [edamontology/edamontology#877]
Can the mainpage please be updated to include what EDAM is meant to spell out? 

The mainpage here doesn't spell it out.

The F1000 reference doesn't spell it out.

DAM was pretty easy to guess, but it wasn't terribly easy to uncover that EDAM=

E(uropean Model for Bioinformatics Research and Community Education) Data Analysis & Management

**Comment by matuskalas** [comment]
Dear @incoherentian, E standing for "EMBRACE" is long obsolete, but indeed if you're looking for historical reasons, it was the case for some time. It also had other meanings before and after.

Currently, EDAM is not an acronym anymore, but if you insist, you could consider
"theE Data Analysis and Management" ontology, or
"sciEntific Data Analysis, optimisation, modelling, and Management"
😊

Please let us know in case you think that not having a well-defined and well-documented acronym is unacceptable.

But yes, you're right that the main page should say something about it 👍🏽

**Comment by incoherentian** [comment]
Thanks @matuskalas.

Alternatively, just call it Edam! Then we can all just assume the progenitors of the project were hungry when brainstorming the name.
