### ISSUE TITLE
Changes to operation "Protein fragment weight comparison"

### ISSUE THREAD

**Issue by veitveit** [edamontology/edamontology#90]
Change definition to :"Calculate the molecular weight of a protein (or fragments) and compare it to another protein or reference data. Generally used for protein identification."
Synonyms: "Peptide Mass Fingerprinting" and "PMF"

**Comment by joncison** [comment]
Done in EDAM_1.14

Also added synonym "Protein fingerprinting" @veitveit  tell me if this is wrong
