### ISSUE TITLE
Dereferencing EDAM classes results in 404 on BioPortal

### ISSUE THREAD

**Issue by jaanisoe** [edamontology/edamontology#901]
Got word that EDAM class links do not work anymore.

For example, currently http://edamontology.org/data_0006 will redirect to https://bioportal.bioontology.org/ontologies/1498?p=terms&conceptid=data_0006 where the message "The page you are looking for wasn't found. Please try again." is displayed.

The correct redirection should now maybe be to https://bioportal.bioontology.org/ontologies/EDAM?p=classes&conceptid=data_0006 (1498 -> EDAM, terms -> classes).

**Comment by rioualen** [comment]
Hi, thank you for creating this issue! 

I've noticed this just a couple days ago but didn't have the time to act on it 😅

Can @hmenager or @matuskalas point me to the source of the problem?

**Comment by matuskalas** [comment]
Many thanks @jaanisoe and @rioualen for spotting this! 🙏🏽🙏🏽 This is indeed very bad, a legacy resolution that obviously now stopped working.
I'm at it trying to get it fixed...

**Comment by matuskalas** [comment]
This is now fixed 😌

**Comment by rioualen** [comment]
Thank you @matuskalas! Could you tell me more about how you fixed it some time? 😃

**Comment by matuskalas** [comment]
> Thank you @matuskalas! Could you tell me more about how you fixed it some time? 😃

It was exactly as jaanisoe wrote, a legacy redirect in the server config.
