### ISSUE TITLE
Add oxli countgraph format

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology#93]
It is coming from khmer, but allegedly used by some other tools too. And documented. Let's consider it.

http://www.iana.org/assignments/media-types/application/vnd.oxli.countgraph

File extension oxlicg

**Comment by joncison** [comment]
@matuskalas : please define parent of this concept (or otherwise the is_format_of relation)

**Comment by matuskalas** [comment]
Was added in 1.12, now refined for 1.15.
