### ISSUE TITLE
dbGaP format

### ISSUE THREAD

**Issue by smoe** [edamontology/edamontology#96]
Hello,
the SRA tools allow to export in that format.
http://www.ncbi.nlm.nih.gov/books/NBK154410/
Cheers,
Steffen

**Comment by joncison** [comment]
@emoe, any chance please you could provide a short (1 or 2 sentence) description of this format, what type of data it describes, and a link to the format specification?  Thanks!

**Comment by joncison** [comment]
@matuskalas : will you provide additional info for this please?

**Comment by joncison** [comment]
Done in EDAM_1.14
"dbGaP format"
http://edamontology.org/format_3729

 more details are needed though
