### ISSUE TITLE
Missing MCPD descriptors

### ISSUE THREAD

**Issue by germa** [edamontology/edamontology#99]
https://www.bioversityinternational.org/fileadmin/user_upload/online_library/publications/pdfs/FAO-Bioversity_multi_crop_passport_descriptors_V_2_Final_rev_1526.pdf

**Comment by joncison** [comment]
Hi @germa 

Thanks for the interest.

Could you explain please what your use-case is there please?  I mean, why would you like these included as EDAM concepts?

EDAM has the scope of bioinformatics, so while some biodiversity concepts are certainly in scope (species name etc.), many others (e.g. geodetic data, longitute etc.) may not be - and would be better placed in a specialised ontology. 

Cheers

Jon

**Comment by joncison** [comment]
Just giving this a nudge @germa  : pls. explain your use-case and we can find a way forward.

**Comment by germa** [comment]
MCPD (Multi Crop Passport Descriptors), 						https://www.bioversityinternational.org/e-library/publications/detail/faoipgri-multi-crop-passport-descriptors-mcpd/ 
is a data exchange format supported by the Genbank Information System (GBIS/I) at http://gbis.ipk-gatersleben.de/, 
which is part of the de.NBI network. We want to register GBIS/I in the Elixir registry

**Comment by matuskalas** [comment]
Added to EDAM version 1.16 that is going to be released today (hopefully, finally). ID: http://edamontology.org/format_3777

When registering GBIS/I in http://bio.tools, please fill in _**Cost**_ _"Commercial"_, even if the payment is symbolic and not really commercial. Perhaps that option in _bio.tools_ should instead be named more generally _"Paid"_.
